#! #!/usr/bin/env python
# -*- coding: utf-8 -*-


"""iPyPS -- An enhanced Interactive Python front-end to PIPS

This is inspired by the ipython script to lauch iPyPs instead of iPython

Ronan.Keryell@hpc-project.com
"""

# Load IPython:
import IPython.Shell
import sys

# Load PyPS:
from pyps import *

# Inject line arguments to set the default prompt to something with iPyPS:
sys.argv[1:1] = [ '-prompt_in1', 'iPyPS [\#]: ']
print sys.argv

IPython.Shell.start().mainloop()
