#!/bin/sh
# 
# Accept differences after validation.
#
# Use the validation error message as standard input to accept to update
# the validations suite. Create a new ~.result .
#
# Mail problem to jouvelot@ensmp.fr
#
# modified by Fabien COELHO
# - cut used instead of awk
# - theline variable added
# - mv instead if ed used to update the results
# - several files may be piped simultaneously
#
# SCCS Stuff:
# $RCSfile: Accept,v $ ($Date: 1994/07/15 19:23:53 $, ) version $Revision$,
# got on %D%, %T%
# $Id$
#

header="Diff Commands for"
pips_test_directory="$PIPSDIR/Tests/Validation"

scriptname="`basename $0` ($Revision$)"

error()
{
  echo "$scriptname error $1: $2" >&2
  exit $1
}


sed -n "/^$header/p" |
while read theline
do
  module=`echo $theline | cut -d' ' -f 4`
  file=`echo $theline | cut -d' ' -f 6`

  resultdir=`dirname $file`/`basename $file .f`.result
  outfile=$resultdir/$module.out
  reffile=$resultdir/$module

  [ -d $resultdir ] || error 1 "no $resultdir"
  [ -f $outfile ] || error 2 "no $outfile"

  echo "accepting for $file"

  rm -f $reffile
  mv $outfile $reffile
done

#
# that is all
#
