#!/bin/sh
# 
# Accept differences after validation.
#
# Use the validation error message as standard input to accept to update
# the validations suite. Create a new ~.result .
#
# Mail problem to jouvelot@ensmp.fr
#
# modified by Fabien COELHO, 08/03/94
# - cut used instead of awk
# - theline variable added
#
# SCCS Stuff:
# $RCSfile: Accept,v $ ($Date: 1994/03/24 10:44:48 $) version $Revision$, got on %D%, %T%
# %A%

pips_test_directory=/home/users/pips/Pips/Tests/Validation
tmp_mail=/tmp/accept.mail.$$
header="Diff Commands for"

cat > $tmp_mail

theline=`grep "^$header" < $tmp_mail`
module=`echo $theline | cut -d' ' -f 4`
file=`echo $theline | cut -d' ' -f 6`

result=`dirname $file`/`basename $file .f`.result

sed '1,/^Validate Message:$/d' < $tmp_mail | \
sed -e "1,/${header}/d;s/^X//" | \
ed -s $result/$module

rm -f $tmp_mail

#
# that's all
#
