#!/bin/sh
# 
# Accept differences after validation.
#
# Use the validation error message as standard input to accept to update
# the validations suite. Create a new ~.result .
#
# Mail problem to jouvelot@ensmp.fr
#
# modified by Fabien COELHO
# - sed and read are used to select the fields
# - mv instead if ed used to update the results
# - several files may be piped simultaneously
#
# SCCS Stuff:
# $RCSfile: Accept,v $ ($Date: 1996/11/11 13:46:23 $, ) version $Revision$,
# got on %D%, %T%
# $Id$
#

header="Differences for"
pips_test_directory="${PIPS_VALIDDIR:-$PIPS_ROOT/Validation}"

scriptname="`basename $0` ($Revision$)"

error()
{
  echo "$scriptname error $1: $2" >&2
  exit $1
}

sed -n "/^$header/s,^$header \([^ ]*\) in \([^ ]*\):,\1 \2,p" |
while read module file
do
  outfile=$file.out
  reffile=$file

  [ -f $outfile ] || error 2 "no $outfile"

  echo "accepting for $file"

  rm -f $reffile
  mv $outfile $reffile
done

#
# that is all
#
