#!/bin/sh

# transforms a program exhibiting a corrected bug into a validation program
# when no xxx.test procedure is required.

# Let's suppose you have Bugs/Syntax/capture.f; run:
#	bug-to-validate capture.f
# in directory Bugs/Syntax and capture.f, capture.result and
# capture.result/CAPTURE are set up in Validation/Syntax

# assumes that the filename and the modulename are the same; and that the
# bugged file is in Bugs/xxxx

# no tests are performed to check whether files and directories exist
# or not and whether Display terminates correctly; sorry, but I'm in
# a hurry

# no cleaning in Bugs is performed, just in case the installation in
# Validation fails

# it would be nice to run this directly from the source directory, e.g.
# Lib/syntax, but I do not know how to simply capitalize a string in shell:
#	syntax -> Syntax

# Francois Irigoin, 3 February 1992

file=$1
workspace=`${PIPS_BASENAME:-basename} $file .f`
module=`echo $workspace | tr a-z A-Z`
library=`pwd|sed 's;/.*/;;'`
echo file=$file module=$module workspace=$workspace library=$library

PIPSDBM_DEBUG_LEVEL=9
Init -d -f $file $workspace
if Display -v -m $module
then
	echo cp $file $PIPSDIR/Tests/Validation/$library
	cp $file $PIPSDIR/Tests/Validation/$library
	echo mkdir $PIPSDIR/Tests/Validation/$library/$workspace.result
	mkdir $PIPSDIR/Tests/Validation/$library/$workspace.result
	echo cp $workspace.database/$module.parf $PIPSDIR/Tests/Validation/$library/$workspace.result/$module
	cp $workspace.database/$module.parf $PIPSDIR/Tests/Validation/$library/$workspace.result/$module
	Delete $workspace.database
else
	echo pips does not work
	exit 1
fi


