#!/bin/sh

# This is used to create a new directory in Validation.
# Suppose you are testing some particular bugs on your special directory ~/xxx.
# You have finished your tests and want to transfer all the directory to /Validation.
# You just have to run dir-to-validate.
# It will :
#	create the new directory /Validation/xxx
#	run your ~.f files according to ~.test 
#			or default_test
#			or display parallelized code
#	put the result in /Validation/xxx/~.resource/
#	transfer ~.f,  ~.test and default_test if it exits.
# 
# So, this is a generalisation of bug-to-validate, very usefull to create
# a new directory with a default_test in it.
#
###############################################################################
#WARNING : to have a general default test for the whole directory,
#		you should write the file default_test as this one :
#
#	#!/bin/sh
#	Init -d -f $PIPSDIR/Tests/Validation/Static_controlize/tested_file.f tested_file >/dev/null 2>/dev/null
#	Display -v -m tested_file stco
#	Delete tested_file 2>/dev/null
#
#Notice that the module you will test should have the same name as the file.
#Those names are represented by 'tested_file' and 'tested_file.f'
# 
###############################################################################
#
# No tests are performed to check whether files and directories exist
# or not and whether Display terminates correctly.
#
# If you have any problem, mail me at leservot@cri.ensmp.fr
# Arnauld LESERVOT 10 09 92

#PIPSDBM_DEBUG_LEVEL=9

make_output()
{
	u_workspace=`echo $workspace | tr a-z A-Z`

	if [ -f $workspace.test ] ; then
		output=`echo test`
		sh $workspace.test > $output
		continue
	fi

	if [ -f default_test ] ; then 
		output=`echo test`
		sed "s/tested_file/$workspace/g;s/TESTED_FILE/$u_workspace/g" default_test\
					 > $workspace.test
		sh $workspace.test > $output
		rm $workspace.test
		continue
	fi

	Init -d -f $file $workspace
	if Display -v -m $module
	then
		output=`echo $workspace.database/$module.parf`
		Delete $workspace
	else 
		exit 1
	fi
}


# This is the command itself

if [ -f test ] ; then
	echo 'Attention ! You have a file named "test". Erase it, please.'
	exit 1
fi

library=`pwd|sed 's;/.*/;;'`
echo mkdir $PIPSDIR/Tests/Validation/$library
mkdir $PIPSDIR/Tests/Validation/$library

for file in *.f 
do
        workspace=`${PIPS_BASENAME:-basename} $file .f | tr A-Z a-z`
        module=`echo $workspace | tr a-z A-Z`
        echo file=$file module=$module workspace=$workspace library=$library

        echo cp $file $PIPSDIR/Tests/Validation/$library
        cp $file $PIPSDIR/Tests/Validation/$library

        make_output

        echo mkdir $PIPSDIR/Tests/Validation/$library/$workspace.result
        mkdir $PIPSDIR/Tests/Validation/$library/$workspace.result

	echo cp $output $PIPSDIR/Tests/Validation/$library/$workspace.result/$output
	cp $output $PIPSDIR/Tests/Validation/$library/$workspace.result/$output
	rm $output
done

echo cp default_test $PIPSDIR/Tests/Validation/$library
cp default_test $PIPSDIR/Tests/Validation/$library
