# $Id$

SCRIPTS = \
	pips_validate \
	manual_accept \
	pips_emacs_diff

INSTALL_UTL =	$(SCRIPTS)

# common stuff
ifdef PIPS_ROOT
ROOT    = $(PIPS_ROOT)
else
ROOT    = ../../..
endif

PROJECT = pips
include $(ROOT)/makes/main.mk
