#! /bin/bash
#
# $Id$

svn=
shopt -s nullglob

for dir
do
  if [[ -d $dir ]]
  then 
    pushd $dir > /dev/null
    for file in *.result/out
    do 
      ref=${file%\/out}/test

      # show differences
      if [ -f $file ]
      then
	echo "CONSIDERING $ref and $file"
        ${PIPS_DIFF:-diff -b -u} $ref $file 
      else
	echo "NEW OUTPUT $file"
	cat $file 
      fi | ${PIPS_MORE:-less}
      
      # accept if okay
      echo 
      echo "accept (y|n)?"
      read answer
      if [ "$answer" = 'y' -o "$answer" = 'Y' ] 
      then 
	  mv $file $ref
	  test -d .svn && svn=1
      fi
    done
    popd > /dev/null
  fi
done

[[ $svn ]] && echo "Consider running \"svn ci $@\" to commit changes"
