#! /bin/bash
#
# $Id$

svn=

for dir
do
  if [[ -d $dir ]]
  then 
    pushd $dir > /dev/null
    test -d .svn && svn=1
    for file in *.result/out
    do 
      ref=${file%\/out}/test
      echo CONSIDERING $ref and $file
      ${PIPS_DIFF:-diff -b -u} $ref $file | ${PIPS_MORE:-less}
      echo 
      echo "accept (y|n)?"
      read answer
      [ "$answer" = 'y' -o "$answer" = 'Y' ] && mv $file $ref
    done
    popd > /dev/null
  fi
done

[[ $svn ]] && echo "Consider running \"svn ci $@\" to commit changes"
