#! /bin/sh
#
# $RCSfile: manual_accept,v $ (version $Revision$)
# $Date: 1997/01/02 16:05:35 $, 
#

CD=$PWD

for dir
do
  if test -d $dir
  then 
    cd $dir
    for f in *.result/test.out
    do 
        if [ "$f" != "*.result/test.out" ] 
        then
	    ref="`dirname $f`/`basename $f .out`"
	    echo CONSIDERING $ref and $f
	    diff $ref $f | less
	    echo 
	    echo "accept (y|n)?"
	    read answer
	    [ "$answer" = 'y' -o "$answer" = 'Y' ] && mv $f $ref
	fi
    done
    cd $CD
  fi
done

# end of $RCSfile: manual_accept,v $
#
