#! /bin/bash

failed=0
success=0
list_lgt=0

function accept_one_file ()
{
    dir=$1
    log=$2
    if [ -d $dir ]; then
	if [ -f $dir/out ]
	then
	    cp $dir/out $dir/test
	    if [ -f $dir/test ]
	    then
		let success++
		echo "Success: reference changed in $dir" >> $log
	    else
		let failed++
		echo "ERROR:can not create test in $dir" >> $log
	    fi
	else
	    echo "ERROR:No output defined in directory $dir
	    Consider runing the validation first" >> $log
	    let failed++
	fi
    else
	echo "ERROR: Directory $dir does not exist" >> $log
	let failed++
    fi
}

echo "starting $0 script with folowing argument(s):"> /tmp/pips_force_accept.log
echo "$@" >> /tmp/pips_force_accept.log

if [[ "$1" == "-h" || "$1" == "--help" || $# == 0 ]]
then
    echo "usage: $0 [file | directory_list]"
    echo "  directory_list: a list of .result directory where  you want the previous"
    echo "                  validation output to be considered as the new reference"
    echo "                  for future validation tests"
    echo "  file          : a file with the validation SUMMARY format (check RESULT/SUMMARY"
    echo "                  file in validation folder). Basically the script will track all"
    echo "                  the changed line in the file and will make the changed result"
    echo "                  as the new reference"
   exit
else
    # in this case we want to process a SUMMARY file    
    if [[ $# == 1 && -f $1 ]]; then
	# generate a file with one .result directory per line
	awk_file=/tmp/pips_force_accept_gen_list_awk
	sed_file=/tmp/pips_force_accept_gen_list_sed
	# firstly select change result in summary file
	mawk '$1 ~ /^changed:.*/ {print $2}' $1 > $awk_file
	# secondly change extension to .result
	sed 's/\.f$\|\.F$\|\.tpips2$\|\.tpips$\|\.c$/.result/' $awk_file > $sed_file

	# check the PIPS_VALIDATE folder 
	if [ ! -d $PIPS_VALIDATE ]; then
	    echo "ERROR pips validation folder :$PIPS_VALIDATE does not exist" 
	    exit
	fi
	
        # go to PIPS_VALIDATE folder because it is use as the root in the
	# SUMMARY file
	cd $PIPS_VALIDATE 
	while read line
	do
	    let list_lgt++
	    accept_one_file $line /tmp/pips_force_accept.log
	done < $sed_file
	#go back to original folder
	cd -
    else
	list_lgt=$#
	for dir in $@
	do
	    accept_one_file $dir /tmp/pips_force_accept.log
	done
    fi
fi

echo "
$0 completes with following statistics :
$list_lgt directories processed
$success succeed
$failed failed" >> /tmp/pips_force_accept.log

echo "
$0 completes with following statistics :
$list_lgt directories processed
$success succeed
$failed failed
logs are in /tmp/pips_force_accept.log"