# Add source files here
TARGET = jacobi 
#EXECUTABLE = jacobi 
CFILES = jacobi-p4a.c
KERNELFILES = kernel1_wrapper.c kernel2_wrapper.c

P4A_ACCEL_DIR = ..

include $(P4A_ACCEL_DIR)/p4a_accel.mk
#include $(P4A_ACCEL_DIR)/p4a_accel-opencl_plusplus.mk
#include $(P4A_ACCEL_DIR)/p4a_accel-opencl.mk
#include $(P4A_ACCEL_DIR)/common.mk
