#! /bin/sh
#
# $RCSfile: install_pips_sources,v $ ($Date: 1996/08/26 12:09:26 $, )
# version $Revision$
# got on %D%, %T%
#

script=`basename $0`
VERBOSE=':'
DEBUG=':'

VERBOSE='verbose'
DEBUG='debug'

unset SOURCE_DIR TARGET_DIR COMMENT OPTIONS CLEAN_SCCS FILES
ONLYDIFF=':'

verbose()
{
  echo "$script:" "$@" 
}

debug()
{
  echo "$script:" "$@" 1>&2
}

error()
{
  echo "$script:" "$@" 1>&2
  exit 2
}

usage()
{
  cat 1>&2 <<-EOM
	Usage: $RCSfile: install_pips_sources,v $ [-hvdaDr] [-y comment] [-t dir] [-s dir] files
	  version $Revision$
	  -h: help
	  -v: verbose
	  -d: install only if different. (default)
	  -a: install all files.
	  -r: clean not installed files from SCCS
	  -D: debug
	  -t dir: target directory (default image of source in \$PIPS_SRCDIR)
	  -s dir: source directory (default .)
	  -y comment: comment for the installation
	EOM
  exit ${1:-1}
}

while getopts hvDdart:s:y: OPT
do
  case $OPT in
    h) usage 0 ;;
    v) VERBOSE='verbose' ; OPTIONS="$OPTIONS -v" ;;
    D) DEBUG='debug' ; OPTIONS="$OPTIONS -D" ;;
    d) ONLYDIFF=':' ; OPTIONS="$OPTIONS -d" ;;
    a) ONLYDIFF= ; OPTIONS="$OPTIONS -a" ;;
    r) CLEAN_SCCS='yes' ; OPTIONS="$OPTIONS -r" ;;
    t) TARGET_DIR="$OPTARG" ;;
    s) SOURCE_DIR="$OPTARG" ;;
    y) COMMENT="$OPTARG" ;;
    *) usage 1 ;;
  esac
done

shift `expr $OPTIND - 1`

#
# default values

[ "$COMMENT" ] || COMMENT='none'
[ "$SOURCE_DIR" ] || SOURCE_DIR=`pwd`
[ "$TARGET_DIR" ] || 
  TARGET_DIR=$PIPS_SRCDIR/`echo "$SOURCE_DIR" | sed 's,.*/\([^/]*/[^/]*\)$,\1,'`

$DEBUG "source directory is $SOURCE_DIR"
$DEBUG "target directory is $TARGET_DIR"

#
# main loop

$VERBOSE "entering directory $TARGET_DIR [$@]"

[ -d "$TARGET_DIR" ] || mkdir $TARGET_DIR 
cd $TARGET_DIR
[ -d OLD ] || mkdir OLD
[ -d SCCS ] || mkdir SCCS

[ "$ONLYDIFF" ] ||
{
  sccs edit SCCS
  rm -f `sccs tell`
}

# cd $TARGET_DIR

for item
do
  $VERBOSE "dealing with $item"
  src_item="$SOURCE_DIR/$item"
  trg_item="$TARGET_DIR/$item"

  if [ "`echo $item | sed 's,[^/],,g'`" ] 
  then
    $VERBOSE "something in a directory, recursing"
    eval $0 $OPTIONS -y "$COMMENT" \
    	-s "`dirname $src_item`" -t "`dirname $trg_item`" \
	"`basename $item`"
    $DEBUG "end of recursion"
    continue
  fi

  # else
  if [ -d "$src_item" ]
  then
    $VERBOSE "directory, recursing"
    $0 $OPTIONS -y "$COMMENT" -s "$src_item" -t "$trg_item" \
    	`cd $src_item ; ls -d * | sed '/~/d;/SCCS/d;/OLD/d'`
    $DEBUG "end of recursion"
    continue
  fi

  #else
  
  FILES="$FILES $item"

  if [ -f $src_item ] 
  then
    if [ "$ONLYDIFF" -a -f $trg_item ]
    then
      cmp -s $src_item $trg_item  && continue
      sccs edit $item 
      rm -f $item
    fi

    cp $src_item $trg_item

    if [ -f "$TARGET_DIR/SCCS/s.$item" ]
    then
      sccs delget -y"$COMMENT" "$item"
    else
      sccs create "$item"
      cmp -s $item ,$item && rm -f ,$item
    fi
  else
    error "$item is neither a file nor a directory"
  fi
done

LOST_FILES="`sccs tell`"
[ "$LOST_FILES" ] &&
{
  $VERBOSE "no more $LOST_FILES"
  sccs unedit $LOST_FILES
  rm -f $LOST_FILES

  #
  # clean the SCCS directory as well

  for f in $LOST_FILES ; 
  do 
    $VERBOSE "moving SCCS/s.$f in OLD"
    mv SCCS/s.$f OLD
  done
}

[ "$CLEAN_SCCS" ] &&
{
  [ "`sccs tell`" ] && error "some files being edited!"

  for item in `ls SCCS/s.* | sed 's,SCCS/s\.,,g'` ;
  do
    $DEBUG "whether $item was installed"
    if [ ! "`echo $FILES | grep $item`" ]
    then
      $VERBOSE "moving $item SCCS file in OLD"
      mv SCCS/s.$item OLD
      rm -f $item
    fi
  done
}

$VERBOSE "done"
