#!/bin/sh
#
# SCCS STuff
# $RCSfile: make-tags,v $ ($Date: 1994/03/10 14:24:59 $) version $Revision$, got on %D%, %T%
# %A%
#
# Tags computation for the PIPS project, using the Development version.
# To be run by cron for user pips on isatis

# Remi Triolet

# Modifications:
#  - add tags for Linear
#  - add recomputation of TAGS for Linear
#  - PIPS_ETAGS variable used
#  - awk -> cut
#  - NEWGENDIR used
#  - find removed, to disallow the recursive enumeration of files
#    (I haven't found a way to do it thru -prune) FC 10/03/94

HOME=`ypcat passwd | egrep '^pips:' | cut -d: -f 6`

# . /etc/profile
. ${HOME}/.profile

TAGS=/tmp/PIPS-TAGS
FILES=/tmp/PIPS-FILES

#
# only directories in this variable
#

PATHNAME_LIST="${DEVEDIR}/Lib/[a-z]* ${DEVEDIR}/Passes/[a-z]* ${INCLUDEDIR} ${EXTEDIR}"

# On saute les SCCS, RK 28/9/93.
# PATHNAME_LIST="${NEWGENDIR}/genClib.c ${NEWGENDIR}/hash.c \
# ${NEWGENDIR}/list.c ${NEWGENDIR}/set.c ${DEVEDIR}/Lib/[a-z]* \
# ${DEVEDIR}/Passes/[a-z]* ${INCLUDEDIR} ${EXTEDIR}"
# find ${PATHNAME_LIST} -name '*.[cyhl]' -print \
# | 	sed -e "/\/SCCS\//d;/\/,/d;/\/[Oo][Ll][Dd]\//d;/\/tmp\//d;" \
# 		> ${FILES} 2>/dev/null

rm -f $FILES $TAGS

# mere files

cat >> ${FILES} <<%
${NEWGENDIR}/genClib.c
${NEWGENDIR}/hash.c
${NEWGENDIR}/list.c
${NEWGENDIR}/set.c
%

# directories

for dir in $PATHNAME_LIST
do
  ls $dir/*.[chly] >> $FILES
done

# tags generation

${PIPS_ETAGS} -f ${TAGS} `cat ${FILES}` 2>/dev/null

cp ${TAGS} ${PIPSDIR}/Tags/TAGS

rm -f ${TAGS} ${FILES}
(cd $LINEARDIR/Development; rm -f TAGS; make TAGS)
cat ${HOME}/C3/Linear/Development/TAGS >>${PIPSDIR}/Tags/TAGS

#
# that's all
#
