#!/bin/sh
#
# SCCS STuff
# $RCSfile: make-tags,v $ ($Date: 1994/03/10 11:50:39 $) version $Revision$, got on %D%, %T%
# %A%
#
# Tags computation for the PIPS project, using the Development version.
# To be run by cron for user pips on isatis

# Remi Triolet

# Modifications:
#  - add tags for Linear
#  - add recomputation of TAGS for Linear
#  - PIPS_ETAGS variable used
#  - awk -> cut
#  - ,files, OLD, tmp, also removed

HOME=`ypcat passwd | egrep '^pips:' | cut -d: -f 6`

# . /etc/profile
. ${HOME}/.profile

TAGS=/tmp/PIPS-TAGS
FILES=/tmp/PIPS-FILES
PATHNAME_LIST="${HOME}/Newgen/genClib.c ${HOME}/Newgen/hash.c ${HOME}/Newgen/list.c ${HOME}/Newgen/set.c ${DEVEDIR}/Lib/[a-z]* ${DEVEDIR}/Passes/[a-z]* ${INCLUDEDIR} ${EXTEDIR}"

# On saute les SCCS, RK 28/9/93.
find ${PATHNAME_LIST} -name '*.[cyhl]' -print | \
	sed -e "/\/SCCS\//d;/\/,/d;/\/[Oo][Ll][Dd]\//d;/\/tmp\//d;" \
		> ${FILES} 2>/dev/null

${PIPS_ETAGS} -f ${TAGS} `cat ${FILES}` 2>/dev/null

cp ${TAGS} ${PIPSDIR}/Tags/TAGS

rm -f ${TAGS} ${FILES}
(cd $LINEARDIR/Development; rm TAGS; make TAGS)
cat ${HOME}/C3/Linear/Development/TAGS >>${PIPSDIR}/Tags/TAGS

#
# that's all
#
