#! /bin/sh
#
# install a file only if different from the one already installed.
#
# Fabien COELHO, 03/08/95
#
# $RCSfile: pips_install_file,v $ (version $Revision$)
# ($Date: 1996/07/15 13:15:02 $, )
#

RUN=':'
SCRIPT=`basename $0`

usage()
{
  echo "usage: $SCRIPT [-flx] directory files ($2)";
  exit ${1:-1}
}

while getopts flx opt
do
  case $opt in
    f) RUN=':' ;;
    l) if test "`type granlib|grep 'not found'`" ; 
       then RUN=ranlib; else RUN=granlib; fi;;
    x) RUN='chmod a+x' ;;
    *) usage 4 "unexpected option ($opt)" ;;
  esac
done

shift `expr $OPTIND - 1`

[ $# -eq 0 ] && usage 2 "invalid number of arguments"
directory=$1
shift
[ -f $directory ] && usage 3 "$directory is not a directory"
[ -d $directory ] || mkdir $directory

# test if different

for file
do
  target=$directory/`basename $file`
  if test -f $target && cmp -s $file $target
  then
    echo "$SCRIPT: skipping $file"
  else
    echo "$SCRIPT: copying $file"
    rm -f $target
    cp $file $directory
    eval $RUN $target
  fi
done

# that is all
#
