#! /bin/sh
#
# install a file only if different from the one already installed.
#
# Fabien COELHO, 03/08/95
#
# $RCSfile: pips_install_file,v $ (version $Revision$)
# ($Date: 1996/06/29 14:28:31 $, )
#

RUN=':'
SCRIPT=`basename $0`

usage()
{
  echo "usage: $SCRIPT [-flx] directory files ($2)";
  exit ${1:-1}
}

while getopts flx opt
do
  case $opt in
    f) RUN=':' ;;
    l) RUN='ranlib' ;;
    x) RUN='chmod a+x' ;;
    *) usage 4 "unexpected option ($opt)" ;;
  esac
done

shift `expr $OPTIND - 1`

[ $# -eq 0 ] && usage 2 "invalid number of arguments"
directory=$1
shift
[ -f $directory ] && usage 3 "$directory is not a directory"
[ -d $directory ] || mkdir $directory

# test if different

for file
do
  if test -f $file && cmp -s $file $directory/$file
  then
    echo "$SCRIPT: skipping $file"
  else
    echo "$SCRIPT: copying $file"
    rm -f $directory/$file
    cp $file $directory
    eval $RUN $directory/$file
  fi
done

# that is all
#
