#! /bin/sh
#
# install a file only if different from the one already installed.
#
# Fabien COELHO, 03/08/95
#
# $RCSfile: pips_install_file,v $ (version $Revision$)
# ($Date: 1995/08/07 13:54:34 $, )
#

RUN=':'

usage()
{
  echo "usage: `basename $0` [-flx] directory files ($2)";
  exit ${1:-1}
}

while getopts flx opt
do
  case $opt in
    f) RUN=':' ;;
    l) RUN='ranlib' ;;
    x) RUN='chmod a+x' ;;
    *) usage 4 "unexpected option ($opt)" ;;
  esac
done

shift `expr $OPTIND - 1`

[ $# -eq 0 ] && usage 2 "invalid number of arguments"
directory=$1
shift
[ -d $directory ] || usage 3 "$directory is not a directory"

# test if different

for file
do
  if test -f $file && cmp -s $file $directory/$file
  then
    echo "$file was not modified" 
  else
    echo "copying $file"
    cp $file $directory
    eval $RUN $directory/$file
  fi
done

# that is all
#
