# $Id$

SVNVERSION	= $(MAKE.d)/version.sh

ifdef NEWGEN_ROOT
ifndef NEWGEN_REV
NEWGEN_REV	:= $(shell $(SVNVERSION) $(NEWGEN_ROOT))
endif # NEWGEN_REV
CPPFLAGS	+= -DNEWGEN_REV=$(NEWGEN_REV)
endif # NEWGEN_ROOT

ifdef LINEAR_ROOT
ifndef LINEAR_REV
LINEAR_REV	:= $(shell $(SVNVERSION) $(LINEAR_ROOT))
endif # LINEAR_REV
CPPFLAGS	+= -DLINEAR_REV=$(LINEAR_REV)
endif # LINEAR_ROOT

ifdef PIPS_ROOT
ifndef PIPS_REV
PIPS_REV	:= $(shell $(SVNVERSION) $(PIPS_ROOT))
endif # PIPS_REV
ifndef NLPMAKE_REV
NLPMAKE_REV	:= $(shell $(SVNVERSION) $(PIPS_ROOT)/makes)
endif # NLPMAKE_REV
CPPFLAGS	+= -DPIPS_REV=$(PIPS_REV) -DNLPMAKE_REV=$(NLPMAKE_REV)
endif # PIPS_ROOT
