# $Id: Makefile 12534 2006-08-17 17:40:34Z coelho $
#
# pips shell simple tools
#

SCRIPTS =	pips_f2openmp

INSTALL_EXE =	$(SCRIPTS)

# common stuff
ifdef PIPS_ROOT
ROOT    = $(PIPS_ROOT)
else
ROOT    = ../../..
endif

#PROJECT = pips
include $(ROOT)/makes/main.mk
