# $Id$
#
# pips shell simple tools
#

SCRIPTS =	pips_c2openmp pips_f2openmp

INSTALL_EXE =	$(SCRIPTS)
INSTALL_SHR = simple_tools.bash

# common stuff
ifdef PIPS_ROOT
ROOT    = $(PIPS_ROOT)
else
ROOT    = ../../..
endif

#PROJECT = pips
include $(ROOT)/makes/main.mk
