# $Id$
#
# pips shell simple tools
#

SCRIPTS =	pips_f2openmp

INSTALL_EXE =	$(SCRIPTS)

# common stuff
ifdef PIPS_ROOT
ROOT    = $(PIPS_ROOT)
else
ROOT    = ../../..
endif

#PROJECT = pips
include $(ROOT)/makes/main.mk
