#! /bin/bash
#
# $Id$
#
# Copyright 1989-2009 MINES ParisTech
#
# This file is part of PIPS.
#
# PIPS is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# PIPS is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PIPS.  If not, see <http://www.gnu.org/licenses/>.
#


# Use $INSTALL_DIR if set or $PIPS_ROOT:
SHR_d=${INSTALL_DIR:-$PIPS_ROOT}/share

function display_usage_and_exit () {
    cat <<EOF
$0 [-h|--help] file.f ...
  Create a workspace from C source files and parallelize
  them with OpenMP syntax.

'$Id$'
EOF
    exit
}

source ${SHR_d}/simple_tools.bash

{
    create_workspace $*
    select_c_language
    select_most_precise_analysis
    privatize_scalar_variables
    #openmp_parallelization_rice
    #internalize_parallel_code
    openmp_parallelization_coarse_grain
    regenerate_source
} | tpips

echo "The parallelized code is in $workspace.database/Src"
