#! /bin/bash

# Use $INSTALL_DIR if set or $PIPS_ROOT:
SHR_d=${INSTALL_DIR:-$PIPS_ROOT}/share

function display_usage_and_exit () {
    cat <<EOF
$0 [-h|--help] file.f ...
  Create a workspace from C source files and parallelize
  them with OpenMP syntax.

'$Id$'
EOF
    exit
}

source ${SHR_d}/simple_tools.bash

{
    create_workspace $*
    select_c_language
    select_most_precise_analysis
    privatize_scalar_variables
    openmp_parallelization
    internalize_parallel_code
    select_omp_sequential_output
    regenerate_source
} | tpips

echo "The parallelized code is in $workspace.database/Src"
