#!/bin/csh -f

if ($?tpips_version == 1) then
    set tpips=$tpips_version
else
    set tpips=tpips
endif

# Get the file name without dir neither extension:
set a=$0
set a=$a:t
set a=$a:r

$tpips <<EOF
delete $a
create $a $a.f

# Set the EPips mode behaviour:
set PRETTYPRINT_ADD_EMACS_PROPERTIES TRUE
set PRETTYPRINT_ALL_DECLARATIONS TRUE
set PRETTYPRINT_HEADER_COMMENTS TRUE

display PRINTED_FILE

close
delete $a
quit
EOF

exit $status
