# $Id$

INSTALL_UTL =	stf \
		stf-workspace \
		stf-module \
		transformer-to-sc

# common stuff
ifdef PIPS_ROOT
ROOT    = $(PIPS_ROOT)
else
ROOT    = ../../..
endif

#PROJECT = pips
include $(ROOT)/makes/main.mk
