      SUBROUTINE GEN(N)
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      COMMON/FFT00/C(65),S(65),EIG(512)
      DATA NA/0/
      IF(N.GT.512.OR.N.LT.8)CALL ABRT('GEN--N OUT OF RANGE',19)
      END

      SUBROUTINE ABRT(MESS,NC)
      IMPLICIT DOUBLE PRECISION (A-H, O-Z)
      CHARACTER MESS(1)
      NW=(NC+9)/10
      PRINT 99, (MESS(I),I=1,NW)
 99   FORMAT(1X,8A10)
      STOP 'SOLVE'
      END
