ehrhart.c~ File Reference
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <string.h>
#include <unistd.h>
#include <assert.h>
#include <polylib/polylib.h>
Defines
#define EPRINT_ALL_VALIDITY_CONSTRAINTS
define this to print all constraints on the validity domains if not defined, only new constraints (not in validity domain given by the user) are printed.
#define REDUCE_DEGREE
Reduce the degree of resulting polynomials.
#define ALL_OVERFLOW_WARNINGS
define this to print one warning message per domain overflow these overflows should no longer happen since version 4.20.
#define EPRINT
#define MAXITER 100
This procedure finds an integer point contained in polyhedron D / first checks for positive values, then for negative values returns TRUE on success.
Functions
enode * new_enode (enode_type type, int size, int pos)
EHRHART POLYNOMIAL SYMBOLIC ALGEBRA SYSTEM.
void free_evalue_refs (evalue *e)
releases all memory referenced by e.
enode * ecopy (enode *e)
void print_evalue (FILE *DST, evalue *e, char **pname)
void print_enode (FILE *DST, enode *p, char **pname)
prints the enode to DST.
int eequal (evalue *e1, evalue *e2)
void reduce_evalue (evalue *e)
void emul (evalue *e1, evalue *e2, evalue *res)
multiplies two evalues and puts the result in res.
void eadd (evalue *e1, evalue *res)
adds one evalue to evalue 'res.
void edot (enode *v1, enode *v2, evalue *res)
computes the inner product of two vectors.
void aep_evalue (evalue *e, int *ref)
local recursive function used in the following ref contains the new position for each old index position.
void addeliminatedparams_evalue (evalue *e, Matrix *CT)
Comments.
int cherche_min (Value *min, Polyhedron *D, int pos)
Polyhedron * Polyhedron_Preprocess (Polyhedron *D, Value *size, unsigned MAXRAYS)
This procedure finds the smallest parallelepiped of size 'size[i]' for every dimension i, contained in polyhedron D If this is not possible, an empty polyhedron is returned.
Polyhedron * Polyhedron_Preprocess2 (Polyhedron *D, Value *size, Value *lcm, unsigned MAXRAYS)
This procedure finds an hypercube of size 'size', containing polyhedron D increases size and lcm if necessary (and not `too big`) If this is not possible, an empty polyhedron is returned.
Polyhedron * old_Polyhedron_Preprocess (Polyhedron *D, Value size, unsigned MAXRAYS)
This procedure adds additional constraints to D so that as each parameter is scanned, it will have a minimum of 'size' points If this is not possible, an empty polyhedron is returned.
int count_points (int pos, Polyhedron *P, Value *context)
PROCEDURES TO COMPUTE ENUMERATION.
enode * P_Enum (Polyhedron *L, Polyhedron *LQ, Value *context, int pos, int nb_param, int dim, Value *lcm)
void Scan_Vertices (Param_Polyhedron *PP, Param_Domain *Q, Matrix *CT, Value *lcm, int nbp)
Enumeration * Enumerate_NoParameters (Polyhedron *P, Polyhedron *C, Matrix *CT, Polyhedron *CEq, unsigned MAXRAYS)
Procedure to count points in a non-parameterized polytope.
Enumeration * Polyhedron_Enumerate (Polyhedron *Pi, Polyhedron *C, unsigned MAXRAYS)
Procedure to count points in a parameterized polytope.
Variables
int overflow_warning_flag = 1
EPRINT : print results while computing the ehrhart polynomial.
char ** param_name
Define Documentation
#define ALL_OVERFLOW_WARNINGS
define this to print one warning message per domain overflow these overflows should no longer happen since version 4.20.
Definition at line 72 of file ehrhart.c~.
#define EPRINT
Definition at line 97 of file ehrhart.c~.
#define EPRINT_ALL_VALIDITY_CONSTRAINTS
define this to print all constraints on the validity domains if not defined, only new constraints (not in validity domain given by the user) are printed.
Definition at line 27 of file ehrhart.c~.
#define MAXITER 100
This procedure finds an integer point contained in polyhedron D / first checks for positive values, then for negative values returns TRUE on success.
Result is in min. returns FALSE if no integer point is found
This is the maximum number of iterations for a given parameter to find a integer point inside the context. Kind of weird. cherche_min should
Parameters:
min
D
pos
Definition at line 634 of file ehrhart.c~.
#define REDUCE_DEGREE
Reduce the degree of resulting polynomials.
Definition at line 66 of file ehrhart.c~.
Function Documentation
Enumeration* Enumerate_NoParameters (Polyhedron * P, Polyhedron * C, Matrix * CT, Polyhedron * CEq, unsigned MAXRAYS)
Procedure to count points in a non-parameterized polytope.
Parameters:
P Polyhedron to count
C Parameter Context domain
CT Matrix to transform context to original
ma CEq additionnal equalities in context
Parameters:
MAXRAYS workspace size
Definition at line 1701 of file ehrhart.c~.
Referenced by Polyhedron_Enumerate().
enode* P_Enum (Polyhedron * L, Polyhedron * LQ, Value * context, int pos, int nb_param, int dim, Value * lcm) [static]
Definition at line 1232 of file ehrhart.c~.
Referenced by Enumerate_NoParameters(), P_Enum(), and Polyhedron_Enumerate().
Enumeration* Polyhedron_Enumerate (Polyhedron * Pi, Polyhedron * C, unsigned MAXRAYS)
Procedure to count points in a parameterized polytope.
Parameters:
P Polyhedron to enumerate
C Context Domain
MAXRAYS size of workspace
Returns:
a list of validity domains + evalues EP
Definition at line 1809 of file ehrhart.c~.
Referenced by Domain_Enumerate().
Polyhedron* Polyhedron_Preprocess (Polyhedron * D, Value * size, unsigned MAXRAYS)
This procedure finds the smallest parallelepiped of size 'size[i]' for every dimension i, contained in polyhedron D If this is not possible, an empty polyhedron is returned.
written by vin100, 2000, for version 4.19
modified 2002, version 5.10
It first finds the coordinates of the lexicographically smallest edge of the hypercube, obtained by transforming the constraints of D (by adding 'size' as many times as there are negative coeficients in each constraint), and finding the lexicographical min of this polyhedron. Then it builds the hypercube and returns it.
Parameters:
D
size
MAXRAYS
Definition at line 743 of file ehrhart.c~.
Referenced by Polyhedron_Enumerate().
Polyhedron* Polyhedron_Preprocess2 (Polyhedron * D, Value * size, Value * lcm, unsigned MAXRAYS)
This procedure finds an hypercube of size 'size', containing polyhedron D increases size and lcm if necessary (and not `too big`) If this is not possible, an empty polyhedron is returned.
 written by vin100, 2001, for version 4.19
Parameters:
D
size
lcm
MAXRAYS
Definition at line 898 of file ehrhart.c~.
Referenced by Polyhedron_Enumerate().
void Scan_Vertices (Param_Polyhedron * PP, Param_Domain * Q, Matrix * CT, Value * lcm, int nbp) [static]
Definition at line 1625 of file ehrhart.c~.
Referenced by Polyhedron_Enumerate().
void addeliminatedparams_evalue (evalue * e, Matrix * CT) [static]
Comments.
Definition at line 588 of file ehrhart.c~.
Referenced by Polyhedron_Enumerate().
void aep_evalue (evalue * e, int * ref) [static]
local recursive function used in the following ref contains the new position for each old index position.
Parameters:
e pointer to an evalue
ref transformation Matrix
Definition at line 568 of file ehrhart.c~.
Referenced by addeliminatedparams_evalue(), and aep_evalue().
int cherche_min (Value * min, Polyhedron * D, int pos)
Definition at line 635 of file ehrhart.c~.
Referenced by Polyhedron_Preprocess(), and cherche_min().
int count_points (int pos, Polyhedron * P, Value * context)
PROCEDURES TO COMPUTE ENUMERATION.
recursive procedure, recurse for each imbriquation
Parameters:
pos index position of current loop index (1..hdim-1)
P loop domain
context context values for fixed indices
Returns:
the number of integer points in this polyhedron
Definition at line 1141 of file ehrhart.c~.
Referenced by count_points().
void eadd (evalue * e1, evalue * res)
adds one evalue to evalue 'res.
result = res + e1
Parameters:
e1 an evalue
res
Definition at line 409 of file ehrhart.c~.
Referenced by eadd(), and edot().
enode* ecopy (enode * e)
Parameters:
e pointer to an evalue
Returns:
description
Definition at line 170 of file ehrhart.c~.
Referenced by Domain_Enumerate(), eadd(), ecopy(), and new_eadd().
void edot (enode * v1, enode * v2, evalue * res)
computes the inner product of two vectors.
Result = result (evalue) = v1.v2 (dot product)
Parameters:
v1 an enode (vector)
v2 an enode (vector of constants)
res result (evalue)
Definition at line 525 of file ehrhart.c~.
Referenced by P_Enum().
int eequal (evalue * e1, evalue * e2) [static]
Parameters:
e1 pointers to evalues
e2 pointers to evalues
Returns:
1 (true) if they are equal, 0 (false) if not
Definition at line 261 of file ehrhart.c~.
Referenced by eequal(), and reduce_evalue().
void emul (evalue * e1, evalue * e2, evalue * res) [static]
multiplies two evalues and puts the result in res.
Parameters:
e1 pointer to an evalue
e2 pointer to a constant evalue
res pointer to result evalue = e1 * e2
Definition at line 368 of file ehrhart.c~.
Referenced by edot(), and emul().
void free_evalue_refs (evalue * e)
releases all memory referenced by e.
(recursive)
Parameters:
e pointer to an evalue
Definition at line 143 of file ehrhart.c~.
Referenced by eadd(), edot(), free_evalue_refs(), and reduce_evalue().
enode* new_enode (enode_type type, int size, int pos)
EHRHART POLYNOMIAL SYMBOLIC ALGEBRA SYSTEM.
The newly allocated enode can be freed with a simple free(x)
Parameters:
type : enode type
size : degree+1 for polynomial, period for periodic
pos : 1..nb_param, position of parameter
Returns:
a newly allocated enode
Definition at line 117 of file ehrhart.c~.
Referenced by P_Enum(), ecopy(), emul(), and new_eadd().
Polyhedron* old_Polyhedron_Preprocess (Polyhedron * D, Value size, unsigned MAXRAYS)
This procedure adds additional constraints to D so that as each parameter is scanned, it will have a minimum of 'size' points If this is not possible, an empty polyhedron is returned.
Parameters:
D
size
MAXRAYS
Definition at line 1060 of file ehrhart.c~.
void print_enode (FILE * DST, enode * p, char ** pname)
prints the enode to DST.
Parameters:
DST destination file
p pointer to enode to be printed
pname array of strings, name of the parameters
Definition at line 216 of file ehrhart.c~.
Referenced by P_Enum(), and print_evalue().
void print_evalue (FILE * DST, evalue * e, char ** pname)
Parameters:
DST destination file
e pointer to evalue to be printed
Definition at line 192 of file ehrhart.c~.
Referenced by Enumerate_NoParameters(), P_Enum(), Polyhedron_Enumerate(), compute_poly(), main(), and print_enode().
void reduce_evalue (evalue * e) [static]
Parameters:
e pointer to an evalue
Definition at line 295 of file ehrhart.c~.
Referenced by Polyhedron_Enumerate(), and reduce_evalue().
Variable Documentation
int overflow_warning_flag = 1
EPRINT : print results while computing the ehrhart polynomial.
this is done by default if you build the executable ehrhart. (If EMAIN is defined). Don't define EMAIN here, it is defined when necessary in the makefile.
Notice: you may however define EPRINT without defining EMAIN, but in this case, you have to initialize the global variable param_name by calling Read_ParamNames before any call to ehrhart. This is NOT recommanded, unless you know what you do. EPRINT causes more debug messages to be printed.
Definition at line 93 of file ehrhart.c~.
char** param_name
Definition at line 100 of file ehrhart.c~.