eval_ehrhart.c File Reference
#include <stdio.h>
#include <math.h>
#include <assert.h>
#include <stdlib.h>
#include <polylib/polylib.h>
Functions
int in_domain (Polyhedron *P, Value *list_args)
double compute_enode (enode *p, Value *list_args)
double compute_evalue (evalue *e, Value *list_args)
Value * compute_poly (Enumeration *en, Value *list_args)
Function Documentation
double compute_enode (enode * p, Value * list_args) [static]
Definition at line 77 of file eval_ehrhart.c.
Referenced by compute_evalue().
double compute_evalue (evalue * e, Value * list_args)
Definition at line 120 of file eval_ehrhart.c.
Referenced by compute_enode(), and compute_poly().
Value* compute_poly (Enumeration * en, Value * list_args)
Definition at line 143 of file eval_ehrhart.c.
int in_domain (Polyhedron * P, Value * list_args)
Definition at line 26 of file eval_ehrhart.c.
Referenced by compute_poly().