ext_ehrhart.c File Reference
#include <stdlib.h>
#include <polylib/polylib.h>
Compounds
struct _Polyhedron_union
Defines
#define WS 200
Typedefs
typedef _Polyhedron_union Polyhedron_union
Functions
int ppcm1 (int a, int b)
Matrix * CalcBase (Matrix *R)
void Soustraire_ligne (Matrix *R, int l1, int l2, int piv)
int existepivot (Matrix *R, int l)
void swap_line (Matrix *R, int l1, int l2)
int pgcd1 (int a, int b)
void new_eadd (evalue *e1, evalue *res)
Matrix * Reduce_Matrix (Matrix *Mat)
void Scalar_product (Value *p1, Value *p2, unsigned length, Value *r)
void ppcm (Value a, Value b, Value *r)
Matrix * Orthogonal_Base (Matrix *Mat)
void Remove_Element (Enumeration *en, Enumeration **re, Enumeration *prev)
void Remove_RedundantDomains (Enumeration **Ures)
int IncludeInRes (Polyhedron *p, Enumeration *e, unsigned MR)
Polyhedron * DMUnion (Enumeration *en, unsigned MR)
void AffConstraints (Polyhedron *Poldisj)
int Degenerate (Enumeration *en)
Enumeration * Domain_Enumerate (Polyhedron *D, Polyhedron *C, unsigned MAXRAYS, char **pn)
Enumeration * Polyhedron_Image_Enumerate (Polyhedron *D, Polyhedron *C, Matrix *T, unsigned MAXRAYS, char **par_name)
Define Documentation
#define WS 200
Definition at line 4 of file ext_ehrhart.c.
Typedef Documentation
typedef struct _Polyhedron_union Polyhedron_union
Function Documentation
void AffConstraints (Polyhedron * Poldisj)
Definition at line 687 of file ext_ehrhart.c.
Referenced by Domain_Enumerate(), and Polyhedron_Image_Enumerate().
Matrix * CalcBase (Matrix * R)
Definition at line 29 of file ext_ehrhart.c.
Referenced by Polyhedron_Image_Enumerate().
Polyhedron* DMUnion (Enumeration * en, unsigned MR)
Definition at line 675 of file ext_ehrhart.c.
Referenced by Domain_Enumerate().
int Degenerate (Enumeration * en)
Definition at line 697 of file ext_ehrhart.c.
Referenced by Domain_Enumerate().
Enumeration* Domain_Enumerate (Polyhedron * D, Polyhedron * C, unsigned MAXRAYS, char ** pn)
Definition at line 709 of file ext_ehrhart.c.
Referenced by Polyhedron_Image_Enumerate(), and main().
int IncludeInRes (Polyhedron * p, Enumeration * e, unsigned MR)
Definition at line 665 of file ext_ehrhart.c.
Referenced by Domain_Enumerate().
Matrix* Orthogonal_Base (Matrix * Mat)
Definition at line 559 of file ext_ehrhart.c.
Enumeration* Polyhedron_Image_Enumerate (Polyhedron * D, Polyhedron * C, Matrix * T, unsigned MAXRAYS, char ** par_name)
Definition at line 832 of file ext_ehrhart.c.
Matrix* Reduce_Matrix (Matrix * Mat)
Definition at line 505 of file ext_ehrhart.c.
Referenced by Polyhedron_Image_Enumerate().
void Remove_Element (Enumeration * en, Enumeration ** re, Enumeration * prev)
Definition at line 629 of file ext_ehrhart.c.
Referenced by Remove_RedundantDomains().
void Remove_RedundantDomains (Enumeration ** Ures)
Definition at line 641 of file ext_ehrhart.c.
Referenced by Domain_Enumerate().
void Scalar_product (Value * p1, Value * p2, unsigned length, Value * r)
Definition at line 524 of file ext_ehrhart.c.
Referenced by Orthogonal_Base(), and Polyhedron_Image_Enumerate().
void Soustraire_ligne (Matrix * R, int l1, int l2, int piv) [static]
Definition at line 270 of file ext_ehrhart.c.
Referenced by CalcBase().
int existepivot (Matrix * R, int l) [static]
Definition at line 209 of file ext_ehrhart.c.
Referenced by CalcBase().
void new_eadd (evalue * e1, evalue * res)
Definition at line 313 of file ext_ehrhart.c.
Referenced by Domain_Enumerate().
int pgcd1 (int a, int b)
Definition at line 248 of file ext_ehrhart.c.
Referenced by ppcm1().
void ppcm (Value a, Value b, Value * r)
Definition at line 550 of file ext_ehrhart.c.
Referenced by Orthogonal_Base().
int ppcm1 (int a, int b) [static]
Definition at line 542 of file ext_ehrhart.c.
Referenced by new_eadd().
void swap_line (Matrix * R, int l1, int l2) [static]
Definition at line 232 of file ext_ehrhart.c.
Referenced by CalcBase().