Lattice.c File Reference
#include <stdlib.h>
#include <polylib/polylib.h>
Compounds
struct factor
Functions
factor allfactors (int num)
void PrintLatticeUnion (FILE *fp, char *format, LatticeUnion *Head)
void LatticeUnion_Free (LatticeUnion *Head)
LatticeUnion * LatticeUnion_Alloc (void)
Bool sameAffinepart (Lattice *A, Lattice *B)
Lattice * EmptyLattice (int dimension)
Bool isEmptyLattice (Lattice *A)
Bool isLinear (Lattice *A)
void AffineHermite (Lattice *A, Lattice **H, Matrix **U)
void AffineSmith (Lattice *A, Lattice **U, Lattice **V, Lattice **Diag)
Lattice * Homogenise (Lattice *A, Bool Forward)
Bool LatticeIncludes (Lattice *A, Lattice *B)
Bool sameLattice (Lattice *A, Lattice *B)
Lattice * ChangeLatticeDimension (Lattice *A, int dimension)
Lattice * ExtractLinearPart (Lattice *A)
Matrix * MakeDioEqforInter (Matrix *A, Matrix *B)
Lattice * LatticeIntersection (Lattice *X, Lattice *Y)
Matrix * MakeDioEqforInter (Lattice *A, Lattice *B)
void AddLattice (LatticeUnion *, Matrix *, Matrix *, int, int)
LatticeUnion * SplitLattice (Matrix *, Matrix *, Matrix *)
LatticeUnion * Lattice2LatticeUnion (Lattice *X, Lattice *Y)
LatticeUnion * LatticeDifference (Lattice *A, Lattice *B)
Method :.
LatticeUnion * SplitLattice (Lattice *B1, Lattice *B2, Matrix *C)
int FindHermiteBasisofDomain (Polyhedron *A, Matrix **B)
Lattice * LatticeImage (Lattice *A, Matrix *M)
Lattice * LatticePreimage (Lattice *L, Matrix *G)
Bool IsLattice (Matrix *m)
Bool isfulldim (Matrix *m)
Bool Simplify (LatticeUnion **InputList, LatticeUnion **ResultList, int dim)
int LinearPartCompare (const void *A, const void *B)
void LinearPartSort (LatticeUnion *Head)
int AffinePartCompare (const void *A, const void *B)
void AffinePartSort (LatticeUnion *List)
Bool AlmostSameAffinePart (LatticeUnion *A, LatticeUnion *B)
Bool AffinePartSimplify (LatticeUnion *curlist, LatticeUnion **newlist)
Bool SameLinearPart (LatticeUnion *A, LatticeUnion *B)
LatticeUnion * LatticeSimplify (LatticeUnion *latlist)
int intcompare (const void *a, const void *b)
int polylib_sqrt (int i)
Function Documentation
void AddLattice (LatticeUnion * Head, Matrix * B1, Matrix * B2, int NumofTimes, int Colnumber) [static]
Definition at line 912 of file Lattice.c.
Referenced by SplitLattice().
void AffineHermite (Lattice * A, Lattice ** H, Matrix ** U)
Definition at line 159 of file Lattice.c.
Referenced by AddLattice(), AddZPolytoZDomain(), CanonicalForm(), LatticeDifference(), LatticeIncludes(), LatticeIntersection(), SplitZpolyhedron(), and sameLattice().
int AffinePartCompare (const void * A, const void * B) [static]
Definition at line 1462 of file Lattice.c.
Bool AffinePartSimplify (LatticeUnion * curlist, LatticeUnion ** newlist) [static]
Definition at line 1527 of file Lattice.c.
Referenced by LatticeSimplify().
void AffinePartSort (LatticeUnion * List) [static]
Definition at line 1484 of file Lattice.c.
Referenced by AffinePartSimplify().
void AffineSmith (Lattice * A, Lattice ** U, Lattice ** V, Lattice ** Diag)
Definition at line 204 of file Lattice.c.
Bool AlmostSameAffinePart (LatticeUnion * A, LatticeUnion * B) [static]
Definition at line 1508 of file Lattice.c.
Referenced by AffinePartSimplify().
Lattice* ChangeLatticeDimension (Lattice * A, int dimension)
Definition at line 393 of file Lattice.c.
Referenced by CanonicalForm(), FindHermiteBasisofDomain(), and Lattice2LatticeUnion().
Lattice* EmptyLattice (int dimension)
Definition at line 78 of file Lattice.c.
Referenced by EmptyZPolyhedron(), LatticeImage(), LatticeIntersection(), and LatticePreimage().
Lattice* ExtractLinearPart (Lattice * A)
Definition at line 423 of file Lattice.c.
Referenced by Lattice2LatticeUnion().
int FindHermiteBasisofDomain (Polyhedron * A, Matrix ** B)
Definition at line 975 of file Lattice.c.
Referenced by CanonicalForm().
Lattice* Homogenise (Lattice * A, Bool Forward)
Definition at line 296 of file Lattice.c.
Referenced by AffineHermite(), AffineSmith(), and isinHnf().
Bool IsLattice (Matrix * m)
Definition at line 1217 of file Lattice.c.
Referenced by ZPolyhedron_Alloc().
LatticeUnion* Lattice2LatticeUnion (Lattice * X, Lattice * Y)
Definition at line 658 of file Lattice.c.
Referenced by LatticeDifference(), and SplitZpolyhedron().
LatticeUnion* LatticeDifference (Lattice * A, Lattice * B)
Method :.
Definition at line 798 of file Lattice.c.
Referenced by ZPolyhedronDifference().
Lattice* LatticeImage (Lattice * A, Matrix * M)
Definition at line 1104 of file Lattice.c.
Referenced by IntegraliseLattice(), and ZPolyhedronImage().
Bool LatticeIncludes (Lattice * A, Lattice * B)
Definition at line 324 of file Lattice.c.
Referenced by ZPolyhedronIncludes().
Lattice* LatticeIntersection (Lattice * X, Lattice * Y)
Definition at line 459 of file Lattice.c.
Referenced by Lattice2LatticeUnion(), LatticeIncludes(), and ZPolyhedronIntersection().
Lattice* LatticePreimage (Lattice * L, Matrix * G)
Definition at line 1143 of file Lattice.c.
Referenced by LatticeImage(), and ZPolyhedronPreimage().
LatticeUnion* LatticeSimplify (LatticeUnion * latlist)
Definition at line 1614 of file Lattice.c.
Referenced by LatticeDifference(), and ZDomainSimplify().
LatticeUnion* LatticeUnion_Alloc (void)
Definition at line 43 of file Lattice.c.
void LatticeUnion_Free (LatticeUnion * Head)
Definition at line 27 of file Lattice.c.
Referenced by ZDomainSimplify().
int LinearPartCompare (const void * A, const void * B) [static]
Definition at line 1407 of file Lattice.c.
void LinearPartSort (LatticeUnion * Head) [static]
Definition at line 1430 of file Lattice.c.
Referenced by LatticeSimplify().
Matrix* MakeDioEqforInter (Lattice * A, Lattice * B) [static]
Definition at line 553 of file Lattice.c.
Referenced by LatticeIntersection().
Matrix* MakeDioEqforInter (Matrix * A, Matrix * B) [static]
void PrintLatticeUnion (FILE * fp, char * format, LatticeUnion * Head)
Definition at line 15 of file Lattice.c.
Bool SameLinearPart (LatticeUnion * A, LatticeUnion * B) [static]
Definition at line 1598 of file Lattice.c.
Referenced by LatticeSimplify().
Bool Simplify (LatticeUnion ** InputList, LatticeUnion ** ResultList, int dim) [static]
Definition at line 1284 of file Lattice.c.
Referenced by AffinePartSimplify().
LatticeUnion* SplitLattice (Lattice * B1, Lattice * B2, Matrix * C)
Definition at line 885 of file Lattice.c.
Referenced by Lattice2LatticeUnion().
LatticeUnion* SplitLattice (Matrix *, Matrix *, Matrix *)
factor allfactors (int num) [static]
Definition at line 1655 of file Lattice.c.
Referenced by Simplify().
int intcompare (const void * a, const void * b)
Definition at line 1641 of file Lattice.c.
Bool isEmptyLattice (Lattice * A)
Definition at line 101 of file Lattice.c.
Referenced by IntegraliseLattice(), Lattice2LatticeUnion(), LatticeDifference(), LatticeIntersection(), SplitZpolyhedron(), ZPolyhedronImage(), ZPolyhedronIntersection(), ZPolyhedronPreimage(), ZPolyhedron_Alloc(), and isEmptyZPolyhedron().
Bool isLinear (Lattice * A)
Definition at line 128 of file Lattice.c.
Referenced by AffineHermite().
Bool isfulldim (Matrix * m)
Definition at line 1245 of file Lattice.c.
Referenced by ZPolyhedron_Alloc().
int polylib_sqrt (int i) [static]
Definition at line 1717 of file Lattice.c.
Referenced by allfactors().
Bool sameAffinepart (Lattice * A, Lattice * B)
Definition at line 57 of file Lattice.c.
Bool sameLattice (Lattice * A, Lattice * B)
Definition at line 355 of file Lattice.c.
Referenced by AddZPolytoZDomain(), and LatticeIncludes().