Matop.c File Reference
#include <stdlib.h>
#include <polylib/polylib.h>
Functions
Value * Lcm (Value i, Value j)
Matrix * Identity (unsigned size)
void ExchangeRows (Matrix *M, int Row1, int Row2)
void ExchangeColumns (Matrix *M, int Column1, int Column2)
Matrix * Transpose (Matrix *A)
Matrix * Matrix_Copy (Matrix *Src)
Bool isIntegral (Matrix *A)
Bool isinHnf (Matrix *A)
void PutRowLast (Matrix *X, int Rownumber)
void PutRowFirst (Matrix *X, int Rownumber)
void PutColumnFirst (Matrix *X, int Columnnumber)
void PutColumnLast (Matrix *X, int Columnnumber)
Matrix * AddANullRow (Matrix *M)
Matrix * AddANullColumn (Matrix *M)
Matrix * RemoveRow (Matrix *M, int Rownumber)
Matrix * RemoveColumn (Matrix *M, int Columnnumber)
int findHermiteBasis (Matrix *M, Matrix **Result)
Function Documentation
Matrix* AddANullColumn (Matrix * M)
Definition at line 297 of file Matop.c.
Referenced by findHermiteBasis().
Matrix* AddANullRow (Matrix * M)
Definition at line 279 of file Matop.c.
Referenced by RearrangeMatforSolveDio(), and findHermiteBasis().
void ExchangeColumns (Matrix * M, int Column1, int Column2)
Definition at line 64 of file Matop.c.
void ExchangeRows (Matrix * M, int Row1, int Row2)
Definition at line 41 of file Matop.c.
Referenced by RearrangeMatforSolveDio().
Matrix* Identity (unsigned size)
Definition at line 24 of file Matop.c.
Referenced by CanonicalForm(), FindHermiteBasisofDomain(), IntegraliseLattice(), and findHermiteBasis().
Value* Lcm (Value i, Value j)
Definition at line 7 of file Matop.c.
Referenced by FindHermiteBasisofDomain().
Matrix* Matrix_Copy (Matrix * Src)
Definition at line 101 of file Matop.c.
Referenced by AddLattice(), AffineHermite(), AffineSmith(), CanonicalForm(), FindHermiteBasisofDomain(), Hermite(), Homogenise(), Lattice2LatticeUnion(), LatticeDifference(), LatticeImage(), LatticeIntersection(), Polyhedron_Image_Enumerate(), RearrangeMatforSolveDio(), RemoveColumn(), RemoveRow(), Simplify(), SolveDiophantine(), SplitZpolyhedron(), ZDomainSimplify(), ZPolyhedron_Alloc(), and findHermiteBasis().
void PutColumnFirst (Matrix * X, int Columnnumber)
Definition at line 225 of file Matop.c.
Referenced by Homogenise().
void PutColumnLast (Matrix * X, int Columnnumber)
Definition at line 252 of file Matop.c.
Referenced by Homogenise(), and RemoveColumn().
void PutRowFirst (Matrix * X, int Rownumber)
Definition at line 198 of file Matop.c.
Referenced by Homogenise().
void PutRowLast (Matrix * X, int Rownumber)
Definition at line 170 of file Matop.c.
Referenced by Homogenise(), and RemoveRow().
Matrix* RemoveColumn (Matrix * M, int Columnnumber)
Definition at line 332 of file Matop.c.
Referenced by FindHermiteBasisofDomain().
Matrix* RemoveRow (Matrix * M, int Rownumber)
Definition at line 314 of file Matop.c.
Referenced by findHermiteBasis().
Matrix* Transpose (Matrix * A)
Definition at line 86 of file Matop.c.
Referenced by Hermite(), Polyhedron_Image_Enumerate(), and findHermiteBasis().
int findHermiteBasis (Matrix * M, Matrix ** Result)
Definition at line 353 of file Matop.c.
Referenced by FindHermiteBasisofDomain().
Bool isIntegral (Matrix * A)
Definition at line 117 of file Matop.c.
Bool isinHnf (Matrix * A)
Definition at line 140 of file Matop.c.
Referenced by LatticeDifference(), LatticeIntersection(), and SplitZpolyhedron().