matrix.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <polylib/polylib.h>
Functions
Matrix * Matrix_Alloc (unsigned NbRows, unsigned NbColumns)
void Matrix_Free (Matrix *Mat)
void Matrix_Print (FILE *Dst, char *Format, Matrix *Mat)
void Matrix_Read_Input (Matrix *Mat)
Matrix * Matrix_Read (void)
int hermite (Matrix *H, Matrix *U, Matrix *Q)
void right_hermite (Matrix *A, Matrix **Hp, Matrix **Up, Matrix **Qp)
void left_hermite (Matrix *A, Matrix **Hp, Matrix **Qp, Matrix **Up)
int MatInverse (Matrix *Mat, Matrix *MatInv)
void rat_prodmat (Matrix *S, Matrix *X, Matrix *P)
void Matrix_Vector_Product (Matrix *Mat, Value *p1, Value *p2)
void Vector_Matrix_Product (Value *p1, Matrix *Mat, Value *p2)
void Matrix_Product (Matrix *Mat1, Matrix *Mat2, Matrix *Mat3)
int Matrix_Inverse (Matrix *Mat, Matrix *MatInv)
Function Documentation
int MatInverse (Matrix * Mat, Matrix * MatInv)
Definition at line 556 of file matrix.c.
Referenced by traite_m_face().
Matrix* Matrix_Alloc (unsigned NbRows, unsigned NbColumns)
Definition at line 28 of file matrix.c.
Referenced by AddANullColumn(), AddANullRow(), AddConstraints(), AddRays(), AddZPolytoZDomain(), AffineSmith(), CalcBase(), CanonicalForm(), ChangeLatticeDimension(), Constraints2Polyhedron(), ConvertDarMattoPolMat(), DomainSimplify(), Elim_Columns(), EmptyLattice(), ExtractLinearPart(), FindHermiteBasisofDomain(), FindSimple(), Find_m_faces(), GenParamPolyhedron(), Identity(), Lattice2LatticeUnion(), LatticeImage(), LatticeIntersection(), LatticePreimage(), MakeDioEqforInter(), Matrix_Copy(), Matrix_Read(), Orthogonal_Base(), P_Enum(), Polyhedron2Constraints(), Polyhedron2Rays(), PolyhedronLTQ(), Polyhedron_Image(), Polyhedron_Image_Enumerate(), Polyhedron_Preimage(), Polyhedron_Preprocess(), Polyhedron_Preprocess2(), Polyhedron_Scan(), PreElim_Columns(), Rays2Polyhedron(), RearrangeMatforSolveDio(), RemoveColumn(), RemoveRow(), SimplifyConstraints(), SimplifyEqualities(), Smith(), SolveDiophantine(), Stras_DomainSimplify(), SubConstraint(), Transpose(), Union_Read(), VertexCT(), align_context(), findHermiteBasis(), left_hermite(), old_Polyhedron_Preprocess(), right_hermite(), and traite_m_face().
void Matrix_Free (Matrix * Mat)
Definition at line 85 of file matrix.c.
Referenced by AddConstraints(), AddLattice(), AddRays(), AddZPolytoZDomain(), AffineHermite(), AffineSmith(), CanonicalForm(), Constraints2Polyhedron(), DomainSimplify(), Elim_Columns(), EmptyZPolyhedron(), FindHermiteBasisofDomain(), FindSimple(), Find_m_faces(), Hermite(), IntegraliseLattice(), Lattice2LatticeUnion(), LatticeDifference(), LatticeImage(), LatticeIncludes(), LatticeIntersection(), LatticePreimage(), LatticeUnion_Free(), P_Enum(), Param_Vertices_Free(), PolyhedronLTQ(), Polyhedron_Image(), Polyhedron_Image_Enumerate(), Polyhedron_Preimage(), Polyhedron_Preprocess(), Polyhedron_Preprocess2(), Polyhedron_Scan(), Rays2Polyhedron(), RearrangeMatforSolveDio(), Scan_Vertices(), Simplify(), SimplifyConstraints(), SimplifyEqualities(), Smith(), SolveDiophantine(), SplitZpolyhedron(), Stras_DomainSimplify(), SubConstraint(), Union_Read(), ZPolyhedronDifference(), ZPolyhedronImage(), ZPolyhedronIntersection(), ZPolyhedronPreimage(), ZPolyhedron_Free(), align_context(), findHermiteBasis(), isfulldim(), isinHnf(), left_hermite(), old_Polyhedron_Preprocess(), and sameLattice().
int Matrix_Inverse (Matrix * Mat, Matrix * MatInv)
Definition at line 873 of file matrix.c.
Referenced by AffineSmith(), CanonicalForm(), FindHermiteBasisofDomain(), Lattice2LatticeUnion(), LatticeImage(), Smith(), and SolveDiophantine().
void Matrix_Print (FILE * Dst, char * Format, Matrix * Mat)
Definition at line 109 of file matrix.c.
Referenced by Chernikova(), Constraints2Polyhedron(), Elim_Columns(), Find_m_faces(), Gauss(), P_Enum(), PolyhedronLTQ(), Polyhedron_Image_Enumerate(), Polyhedron_Preprocess(), Polyhedron_Preprocess2(), PreElim_Columns(), PrintLatticeUnion(), Rays2Polyhedron(), Remove_Redundants(), ZPolyhedronPrint(), hermite(), and traite_m_face().
void Matrix_Product (Matrix * Mat1, Matrix * Mat2, Matrix * Mat3)
Definition at line 825 of file matrix.c.
Referenced by AddZPolytoZDomain(), CanonicalForm(), FindHermiteBasisofDomain(), Lattice2LatticeUnion(), and LatticeImage().
Matrix* Matrix_Read (void)
Definition at line 170 of file matrix.c.
Referenced by Union_Read().
void Matrix_Read_Input (Matrix * Mat)
Definition at line 133 of file matrix.c.
Referenced by Matrix_Read(), and Union_Read().
void Matrix_Vector_Product (Matrix * Mat, Value * p1, Value * p2)
Definition at line 753 of file matrix.c.
void Vector_Matrix_Product (Value * p1, Matrix * Mat, Value * p2)
Definition at line 791 of file matrix.c.
int hermite (Matrix * H, Matrix * U, Matrix * Q) [static]
Definition at line 192 of file matrix.c.
void left_hermite (Matrix * A, Matrix ** Hp, Matrix ** Qp, Matrix ** Up)
Definition at line 471 of file matrix.c.
void rat_prodmat (Matrix * S, Matrix * X, Matrix * P)
Definition at line 684 of file matrix.c.
Referenced by traite_m_face().
void right_hermite (Matrix * A, Matrix ** Hp, Matrix ** Up, Matrix ** Qp)
Definition at line 401 of file matrix.c.