polyparam.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <polylib/polylib.h>
Compounds
struct SatMatrix
Functions
void traite_m_face ()
void scan_m_face ()
Polyhedron * PDomainIntersection (Polyhedron *Pol1, Polyhedron *Pol2, unsigned NbMaxRays)
Polyhedron * PDomainDifference (Polyhedron *Pol1, Polyhedron *Pol2, unsigned NbMaxRays)
int TestRank (Matrix *Mat)
SatMatrix * SMAlloc (int rows, int cols)
void SMFree (SatMatrix *matrix)
Polyhedron * Add_CEqualities (Polyhedron *D)
void traite_m_face (Polyhedron *D, int *mf)
int count_sat (unsigned int *mf)
void scan_m_face (int pos, int nb_un, Polyhedron *D, unsigned int *mf)
SatMatrix * Poly2Sat (Polyhedron *Pol, unsigned int **L)
Param_Polyhedron * GenParamPolyhedron (Polyhedron *Pol)
Matrix * PreElim_Columns (Polyhedron *E, int *p, int *ref, int m)
Polyhedron * Elim_Columns (Polyhedron *A, Polyhedron *E, int *p, int *ref)
Param_Polyhedron * Find_m_faces (Polyhedron **Di, Polyhedron *C, int keep_dom, int working_space, Polyhedron **CEq, Matrix **CT)
void Compute_PDomains (Param_Domain *PD, int nb_domains, int working_space)
Param_Polyhedron * Polyhedron2Param_Vertices (Polyhedron *Din, Polyhedron *Cin, int working_space)
void Param_Vertices_Free (Param_Vertices *PV)
void Print_Vertex (FILE *DST, Matrix *V, char **param_names)
Matrix * VertexCT (Matrix *V, Matrix *CT)
void Print_Domain (FILE *DST, Polyhedron *D, char **pname)
void Param_Vertices_Print (FILE *DST, Param_Vertices *PV, char **param_names)
Param_Polyhedron * Polyhedron2Param_Domain (Polyhedron *Din, Polyhedron *Cin, int working_space)
Param_Polyhedron * Polyhedron2Param_SimplifiedDomain (Polyhedron **Din, Polyhedron *Cin, int working_space, Polyhedron **CEq, Matrix **CT)
void Param_Domain_Free (Param_Domain *PD)
void Param_Polyhedron_Free (Param_Polyhedron *P)
Variables
int m
int m_dim
int n
int ws
int nr
Polyhedron * CEqualities
SatMatrix * Sat
int * egalite
Matrix * Xi
Matrix * Pi
Matrix * PiTest
Matrix * PiInv
Matrix * RaysDi
int KD
int nbPV
Param_Vertices * PV_Result
Param_Domain * PDomains
int cntbit [256]
Function Documentation
Polyhedron* Add_CEqualities (Polyhedron * D) [static]
Definition at line 274 of file polyparam.c.
Referenced by Polyhedron2Param_Domain(), and traite_m_face().
void Compute_PDomains (Param_Domain * PD, int nb_domains, int working_space)
Definition at line 1189 of file polyparam.c.
Referenced by Polyhedron2Param_Domain(), and Polyhedron2Param_SimplifiedDomain().
Polyhedron* Elim_Columns (Polyhedron * A, Polyhedron * E, int * p, int * ref)
Definition at line 848 of file polyparam.c.
Referenced by Find_m_faces().
Param_Polyhedron* Find_m_faces (Polyhedron ** Di, Polyhedron * C, int keep_dom, int working_space, Polyhedron ** CEq, Matrix ** CT)
Definition at line 912 of file polyparam.c.
Referenced by Polyhedron2Param_Domain(), Polyhedron2Param_SimplifiedDomain(), and Polyhedron2Param_Vertices().
Param_Polyhedron* GenParamPolyhedron (Polyhedron * Pol)
Definition at line 707 of file polyparam.c.
Referenced by Find_m_faces().
Polyhedron* PDomainDifference (Polyhedron * Pol1, Polyhedron * Pol2, unsigned NbMaxRays)
Definition at line 86 of file polyparam.c.
Referenced by Compute_PDomains().
Polyhedron* PDomainIntersection (Polyhedron * Pol1, Polyhedron * Pol2, unsigned NbMaxRays)
Definition at line 50 of file polyparam.c.
Referenced by Compute_PDomains().
void Param_Domain_Free (Param_Domain * PD)
Definition at line 1655 of file polyparam.c.
Referenced by Param_Polyhedron_Free().
void Param_Polyhedron_Free (Param_Polyhedron * P)
Definition at line 1672 of file polyparam.c.
void Param_Vertices_Free (Param_Vertices * PV)
Definition at line 1386 of file polyparam.c.
Referenced by Param_Polyhedron_Free().
void Param_Vertices_Print (FILE * DST, Param_Vertices * PV, char ** param_names)
Definition at line 1555 of file polyparam.c.
SatMatrix* Poly2Sat (Polyhedron * Pol, unsigned int ** L) [static]
Definition at line 654 of file polyparam.c.
Referenced by Find_m_faces().
Param_Polyhedron* Polyhedron2Param_Domain (Polyhedron * Din, Polyhedron * Cin, int working_space)
Definition at line 1580 of file polyparam.c.
Param_Polyhedron* Polyhedron2Param_SimplifiedDomain (Polyhedron ** Din, Polyhedron * Cin, int working_space, Polyhedron ** CEq, Matrix ** CT)
Definition at line 1616 of file polyparam.c.
Referenced by Polyhedron_Enumerate().
Param_Polyhedron* Polyhedron2Param_Vertices (Polyhedron * Din, Polyhedron * Cin, int working_space)
Definition at line 1360 of file polyparam.c.
Matrix* PreElim_Columns (Polyhedron * E, int * p, int * ref, int m)
Definition at line 775 of file polyparam.c.
Referenced by Find_m_faces().
void Print_Domain (FILE * DST, Polyhedron * D, char ** pname)
Definition at line 1505 of file polyparam.c.
Referenced by Enumerate_NoParameters(), Param_Vertices_Print(), Polyhedron_Enumerate(), compute_poly(), and main().
void Print_Vertex (FILE * DST, Matrix * V, char ** param_names)
Definition at line 1402 of file polyparam.c.
Referenced by Param_Vertices_Print(), and Scan_Vertices().
SatMatrix* SMAlloc (int rows, int cols) [static]
Definition at line 205 of file polyparam.c.
Referenced by BuildSat(), Constraints2Polyhedron(), FindSimple(), Poly2Sat(), Rays2Polyhedron(), and TransformSat().
void SMFree (SatMatrix * matrix) [static]
Definition at line 229 of file polyparam.c.
Referenced by AddConstraints(), AddRays(), BuildSat(), Constraints2Polyhedron(), FindSimple(), Find_m_faces(), Rays2Polyhedron(), SimplifyConstraints(), and SubConstraint().
int TestRank (Matrix * Mat) [static]
Definition at line 127 of file polyparam.c.
Referenced by traite_m_face().
Matrix* VertexCT (Matrix * V, Matrix * CT)
Definition at line 1475 of file polyparam.c.
Referenced by Scan_Vertices().
int count_sat (unsigned int * mf) [static]
Definition at line 482 of file polyparam.c.
Referenced by scan_m_face().
void scan_m_face (int pos, int nb_un, Polyhedron * D, unsigned int * mf) [static]
Definition at line 539 of file polyparam.c.
void scan_m_face () [static]
Referenced by Find_m_faces(), and scan_m_face().
void traite_m_face (Polyhedron * D, int * mf) [static]
Definition at line 303 of file polyparam.c.
void traite_m_face () [static]
Referenced by scan_m_face().
Variable Documentation
Polyhedron* CEqualities [static]
Definition at line 249 of file polyparam.c.
int KD [static]
Definition at line 258 of file polyparam.c.
Param_Domain* PDomains [static]
Definition at line 263 of file polyparam.c.
Param_Vertices* PV_Result [static]
Definition at line 262 of file polyparam.c.
Matrix * Pi [static]
Definition at line 252 of file polyparam.c.
Matrix* PiInv [static]
Definition at line 254 of file polyparam.c.
Matrix* PiTest [static]
Definition at line 253 of file polyparam.c.
Matrix* RaysDi [static]
Definition at line 256 of file polyparam.c.
SatMatrix* Sat [static]
Definition at line 250 of file polyparam.c.
Matrix* Xi [static]
Definition at line 252 of file polyparam.c.
int cntbit[256]
Initial value:
 {                              
0, 1, 1, 2, 1, 2, 2, 3, 1, 2, 2, 3, 2, 3, 3, 4,
1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5,
1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5,
2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6,

1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5,
2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6,
2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6,
3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7,

1, 2, 2, 3, 2, 3, 3, 4, 2, 3, 3, 4, 3, 4, 4, 5,
2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6,
2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6,
3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7,

2, 3, 3, 4, 3, 4, 4, 5, 3, 4, 4, 5, 4, 5, 5, 6,
3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7,
3, 4, 4, 5, 4, 5, 5, 6, 4, 5, 5, 6, 5, 6, 6, 7,
4, 5, 5, 6, 5, 6, 6, 7, 5, 6, 6, 7, 6, 7, 7, 8 }
Definition at line 461 of file polyparam.c.
int* egalite [static]
Definition at line 251 of file polyparam.c.
int m [static]
Definition at line 243 of file polyparam.c.
int m_dim [static]
Definition at line 244 of file polyparam.c.
int n [static]
Definition at line 245 of file polyparam.c.
int nbPV [static]
Definition at line 261 of file polyparam.c.
int nr [static]
Definition at line 247 of file polyparam.c.
int ws [static]
Definition at line 246 of file polyparam.c.