polyhedron.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <polylib/polylib.h>
Compounds
struct SatMatrix
Defines
#define WSIZE (8*sizeof(int))
#define bexchange(a, b, l)
#define exchange(a, b, t) { (t)=(a); (a)=(b); (b)=(t); }
#define SMVector_Copy(p1, p2, length) memcpy((char *)(p2), (char *)(p1), (int)((length)*sizeof(int)))
#define SMVector_Init(p1, length) memset((char *)(p1), 0, (int)((length)*sizeof(int)))
Functions
void errormsg1 (char *f, char *msgname, char *msg)
SatMatrix * SMAlloc (int rows, int cols)
void SMFree (SatMatrix **matrix)
void SMPrint (SatMatrix *matrix)
void SatVector_OR (int *p1, int *p2, int *p3, unsigned length)
void Combine (Value *p1, Value *p2, Value *p3, int pos, unsigned length)
SatMatrix * TransformSat (Matrix *Mat, Matrix *Ray, SatMatrix *Sat)
void RaySort (Matrix *Ray, SatMatrix *Sat, int NbBid, int NbRay, int *equal_bound, int *sup_bound, unsigned RowSize1, unsigned RowSize2, unsigned bx, unsigned jx)
int Chernikova (Matrix *Mat, Matrix *Ray, SatMatrix *Sat, unsigned NbBid, unsigned NbMaxRays, unsigned FirstConstraint, unsigned dual)
int Gauss (Matrix *Mat, int NbEq, int Dimension)
Polyhedron * Remove_Redundants (Matrix *Mat, Matrix *Ray, SatMatrix *Sat, unsigned *Filter)
Polyhedron * Polyhedron_Alloc (unsigned Dimension, unsigned NbConstraints, unsigned NbRays)
void Polyhedron_Free (Polyhedron *Pol)
void Domain_Free (Polyhedron *Pol)
void Polyhedron_Print (FILE *Dst, char *Format, Polyhedron *Pol)
void PolyPrint (Polyhedron *Pol)
Polyhedron * Empty_Polyhedron (unsigned Dimension)
Polyhedron * Universe_Polyhedron (unsigned Dimension)
Polyhedron * Constraints2Polyhedron (Matrix *Constraints, unsigned NbMaxRays)
Matrix * Polyhedron2Constraints (Polyhedron *Pol)
Polyhedron * Rays2Polyhedron (Matrix *Ray, unsigned NbMaxConstrs)
SatMatrix * BuildSat (Matrix *Mat, Matrix *Ray, unsigned NbConstraints, unsigned NbMaxRays)
Polyhedron * AddConstraints (Value *Con, unsigned NbConstraints, Polyhedron *Pol, unsigned NbMaxRays)
int PolyhedronIncludes (Polyhedron *Pol1, Polyhedron *Pol2)
Polyhedron * AddPolyToDomain (Polyhedron *Pol, Polyhedron *PolDomain)
Polyhedron * SubConstraint (Value *Con, Polyhedron *Pol, unsigned NbMaxRays, int Pass)
Polyhedron * DomainIntersection (Polyhedron *Pol1, Polyhedron *Pol2, unsigned NbMaxRays)
Matrix * Polyhedron2Rays (Polyhedron *Pol)
Polyhedron * AddRays (Value *AddedRays, unsigned NbAddedRays, Polyhedron *Pol, unsigned NbMaxConstrs)
Polyhedron * DomainAddRays (Polyhedron *Pol, Matrix *Ray, unsigned NbMaxConstrs)
Polyhedron * Polyhedron_Copy (Polyhedron *Pol)
Polyhedron * Domain_Copy (Polyhedron *Pol)
void addToFilter (int k, unsigned *Filter, SatMatrix *Sat, Value *tmpR, Value *tmpC, int NbRays, int NbConstraints)
void FindSimple (Polyhedron *P1, Polyhedron *P2, unsigned *Filter, unsigned NbMaxRays)
int SimplifyConstraints (Polyhedron *Pol1, Polyhedron *Pol2, unsigned *Filter, unsigned NbMaxRays)
void SimplifyEqualities (Polyhedron *Pol1, Polyhedron *Pol2, unsigned *Filter)
Polyhedron * DomainSimplify (Polyhedron *Pol1, Polyhedron *Pol2, unsigned NbMaxRays)
Polyhedron * Stras_DomainSimplify (Polyhedron *Pol1, Polyhedron *Pol2, unsigned NbMaxRays)
Polyhedron * DomainUnion (Polyhedron *Pol1, Polyhedron *Pol2, unsigned NbMaxRays)
Polyhedron * DomainConvex (Polyhedron *Pol, unsigned NbMaxConstrs)
Polyhedron * DomainDifference (Polyhedron *Pol1, Polyhedron *Pol2, unsigned NbMaxRays)
Polyhedron * align_context (Polyhedron *Pol, int align_dimension, int NbMaxRays)
Polyhedron * Polyhedron_Scan (Polyhedron *D, Polyhedron *C, unsigned NbMaxRays)
int lower_upper_bounds (int pos, Polyhedron *P, Value *context, Value *LBp, Value *UBp)
Polyhedron * Polyhedron_Preimage (Polyhedron *Pol, Matrix *Func, unsigned NbMaxRays)
Polyhedron * DomainPreimage (Polyhedron *Pol, Matrix *Func, unsigned NbMaxRays)
Polyhedron * Polyhedron_Image (Polyhedron *Pol, Matrix *Func, unsigned NbMaxConstrs)
Polyhedron * DomainImage (Polyhedron *Pol, Matrix *Func, unsigned NbMaxConstrs)
Interval * DomainCost (Polyhedron *Pol, Value *Cost)
Polyhedron * DomainAddConstraints (Polyhedron *Pol, Matrix *Mat, unsigned NbMaxRays)
Polyhedron * Disjoint_Domain (Polyhedron *P, int flag, unsigned NbMaxRays)
void Polyhedron_PrintConstraints (FILE *Dst, char *Format, Polyhedron *Pol)
Variables
int Pol_status
Define Documentation
#define SMVector_Copy(p1, p2, length) memcpy((char *)(p2), (char *)(p1), (int)((length)*sizeof(int)))
Definition at line 178 of file polyhedron.c.
Referenced by Chernikova().
#define SMVector_Init(p1, length) memset((char *)(p1), 0, (int)((length)*sizeof(int)))
Definition at line 184 of file polyhedron.c.
Referenced by BuildSat(), Constraints2Polyhedron(), DomainSimplify(), FindSimple(), Rays2Polyhedron(), Stras_DomainSimplify(), and TransformSat().
#define WSIZE (8*sizeof(int))
Definition at line 52 of file polyhedron.c.
#define bexchange(a, b, l)
Value:
{\
  char *t = (char *)malloc(l*sizeof(char));\
  memcpy((t), (char *)(a), (int)(l));\
  memcpy((char *)(a), (char *)(b), (int)(l));\
  memcpy((char *)(b), (t), (int)(l));\
  free(t); \
}
Definition at line 54 of file polyhedron.c.
Referenced by RaySort(), and Remove_Redundants().
#define exchange(a, b, t) { (t)=(a); (a)=(b); (b)=(t); }
Definition at line 63 of file polyhedron.c.
Referenced by Remove_Redundants().
Function Documentation
Polyhedron* AddConstraints (Value * Con, unsigned NbConstraints, Polyhedron * Pol, unsigned NbMaxRays)
Definition at line 2209 of file polyhedron.c.
Referenced by Add_CEqualities(), Disjoint_Domain(), DomainAddConstraints(), DomainIntersection(), FindSimple(), PDomainIntersection(), PolyhedronLTQ(), Polyhedron_Image_Enumerate(), and old_Polyhedron_Preprocess().
Polyhedron* AddPolyToDomain (Polyhedron * Pol, Polyhedron * PolDomain)
Definition at line 2318 of file polyhedron.c.
Referenced by Disjoint_Domain(), DomainDifference(), DomainImage(), DomainIntersection(), DomainPreimage(), DomainSimplify(), PDomainDifference(), PDomainIntersection(), and Polyhedron_Image_Enumerate().
Polyhedron* AddRays (Value * AddedRays, unsigned NbAddedRays, Polyhedron * Pol, unsigned NbMaxConstrs)
Definition at line 2528 of file polyhedron.c.
Referenced by DomainAddRays(), DomainConvex(), and PolyhedronLTQ().
SatMatrix* BuildSat (Matrix * Mat, Matrix * Ray, unsigned NbConstraints, unsigned NbMaxRays) [static]
Definition at line 2147 of file polyhedron.c.
Referenced by AddConstraints(), AddRays(), SimplifyConstraints(), and SubConstraint().
int Chernikova (Matrix * Mat, Matrix * Ray, SatMatrix * Sat, unsigned NbBid, unsigned NbMaxRays, unsigned FirstConstraint, unsigned dual) [static]
Definition at line 340 of file polyhedron.c.
Referenced by AddConstraints(), AddRays(), Constraints2Polyhedron(), Rays2Polyhedron(), SimplifyConstraints(), and SubConstraint().
void Combine (Value * p1, Value * p2, Value * p3, int pos, unsigned length) [static]
Definition at line 197 of file polyhedron.c.
Referenced by Chernikova(), and Gauss().
Polyhedron* Constraints2Polyhedron (Matrix * Constraints, unsigned NbMaxRays)
Definition at line 1919 of file polyhedron.c.
Referenced by DomainSimplify(), Elim_Columns(), Find_m_faces(), Param_Vertices_Print(), Polyhedron_Preimage(), Polyhedron_Preprocess(), Polyhedron_Preprocess2(), Stras_DomainSimplify(), Union_Read(), and align_context().
Polyhedron* Disjoint_Domain (Polyhedron * P, int flag, unsigned NbMaxRays)
Definition at line 4129 of file polyhedron.c.
Referenced by Domain_Enumerate().
Polyhedron* DomainAddConstraints (Polyhedron * Pol, Matrix * Mat, unsigned NbMaxRays)
Definition at line 4076 of file polyhedron.c.
Polyhedron* DomainAddRays (Polyhedron * Pol, Matrix * Ray, unsigned NbMaxConstrs)
Definition at line 2605 of file polyhedron.c.
Referenced by Find_m_faces(), and Polyhedron_Scan().
Polyhedron* DomainConvex (Polyhedron * Pol, unsigned NbMaxConstrs)
Definition at line 3415 of file polyhedron.c.
Interval* DomainCost (Polyhedron * Pol, Value * Cost)
Definition at line 3951 of file polyhedron.c.
Polyhedron* DomainDifference (Polyhedron * Pol1, Polyhedron * Pol2, unsigned NbMaxRays)
Definition at line 3447 of file polyhedron.c.
Referenced by Domain_Enumerate(), ZDomainSimplify(), ZPolyhedronDifference(), and ZPolyhedronIncludes().
Polyhedron* DomainImage (Polyhedron * Pol, Matrix * Func, unsigned NbMaxConstrs)
Definition at line 3915 of file polyhedron.c.
Referenced by AddZPolytoZDomain(), CanonicalForm(), FindHermiteBasisofDomain(), IntegraliseLattice(), Polyhedron_Image_Enumerate(), ZDomainSimplify(), ZPolyhedronDifference(), ZPolyhedronImage(), ZPolyhedronIncludes(), ZPolyhedronIntersection(), and ZPolyhedronPreimage().
Polyhedron* DomainIntersection (Polyhedron * Pol1, Polyhedron * Pol2, unsigned NbMaxRays)
Definition at line 2476 of file polyhedron.c.
Referenced by Domain_Enumerate(), Enumerate_NoParameters(), Find_m_faces(), PolyhedronLTQ(), Polyhedron_Enumerate(), Polyhedron_Scan(), ZPolyhedronDifference(), and ZPolyhedronIntersection().
Polyhedron* DomainPreimage (Polyhedron * Pol, Matrix * Func, unsigned NbMaxRays)
Definition at line 3810 of file polyhedron.c.
Referenced by IntegraliseLattice(), ZDomainSimplify(), ZPolyhedronDifference(), ZPolyhedronImage(), ZPolyhedronIntersection(), and ZPolyhedronPreimage().
Polyhedron* DomainSimplify (Polyhedron * Pol1, Polyhedron * Pol2, unsigned NbMaxRays)
Definition at line 3109 of file polyhedron.c.
Referenced by Find_m_faces(), Polyhedron_Enumerate(), and Polyhedron_Scan().
Polyhedron* DomainUnion (Polyhedron * Pol1, Polyhedron * Pol2, unsigned NbMaxRays)
Definition at line 3334 of file polyhedron.c.
Referenced by AddZPolytoZDomain(), and DMUnion().
Polyhedron* Domain_Copy (Polyhedron * Pol)
Definition at line 2674 of file polyhedron.c.
Referenced by AddZPolytoZDomain(), DomainDifference(), ZDomainSimplify(), ZPolyhedronDifference(), and ZPolyhedron_Alloc().
void Domain_Free (Polyhedron * Pol)
Definition at line 1744 of file polyhedron.c.
Referenced by AddZPolytoZDomain(), Add_CEqualities(), Compute_PDomains(), Disjoint_Domain(), EmptyZPolyhedron(), Enumerate_NoParameters(), Find_m_faces(), IntegraliseLattice(), Param_Domain_Free(), Param_Vertices_Print(), PolyhedronLTQ(), Polyhedron_Enumerate(), Polyhedron_Not_Empty(), Polyhedron_Preprocess(), Polyhedron_Scan(), ZDomainSimplify(), ZPolyhedronDifference(), ZPolyhedronImage(), ZPolyhedronIncludes(), ZPolyhedronIntersection(), ZPolyhedronPreimage(), and ZPolyhedron_Free().
Polyhedron* Empty_Polyhedron (unsigned Dimension)
Definition at line 1852 of file polyhedron.c.
Referenced by DomainDifference(), DomainIntersection(), DomainSimplify(), EmptyZPolyhedron(), Polyhedron_Image(), Polyhedron_Preimage(), Rays2Polyhedron(), Remove_Redundants(), and Stras_DomainSimplify().
void FindSimple (Polyhedron * P1, Polyhedron * P2, unsigned * Filter, unsigned NbMaxRays) [static]
Definition at line 2753 of file polyhedron.c.
Referenced by SimplifyConstraints().
int Gauss (Matrix * Mat, int NbEq, int Dimension)
Definition at line 699 of file polyhedron.c.
Referenced by P_Enum(), Remove_Redundants(), and SimplifyEqualities().
void PolyPrint (Polyhedron * Pol)
Definition at line 1841 of file polyhedron.c.
Matrix* Polyhedron2Constraints (Polyhedron * Pol)
Definition at line 2015 of file polyhedron.c.
Referenced by Elim_Columns(), and traite_m_face().
Matrix* Polyhedron2Rays (Polyhedron * Pol)
Definition at line 2508 of file polyhedron.c.
Referenced by GenParamPolyhedron().
int PolyhedronIncludes (Polyhedron * Pol1, Polyhedron * Pol2)
Definition at line 2278 of file polyhedron.c.
Referenced by AddPolyToDomain(), DomainAddConstraints(), DomainAddRays(), DomainUnion(), IncludeInRes(), Polyhedron_Enumerate(), and Remove_RedundantDomains().
Polyhedron* Polyhedron_Alloc (unsigned Dimension, unsigned NbConstraints, unsigned NbRays)
Definition at line 1675 of file polyhedron.c.
Referenced by Empty_Polyhedron(), Polyhedron_Copy(), Remove_Redundants(), and Universe_Polyhedron().
Polyhedron* Polyhedron_Copy (Polyhedron * Pol)
Definition at line 2648 of file polyhedron.c.
Referenced by Add_CEqualities(), Disjoint_Domain(), DomainConvex(), DomainUnion(), Domain_Copy(), FindSimple(), and Polyhedron_Image_Enumerate().
void Polyhedron_Free (Polyhedron * Pol)
Definition at line 1724 of file polyhedron.c.
Referenced by AddConstraints(), AddPolyToDomain(), AddRays(), CanonicalForm(), Constraints2Polyhedron(), Disjoint_Domain(), DomainConvex(), DomainImage(), DomainPreimage(), Enumerate_NoParameters(), FindSimple(), Find_m_faces(), PDomainDifference(), PDomainIntersection(), Polyhedron_Enumerate(), Polyhedron_Image(), Polyhedron_Image_Enumerate(), Polyhedron_Preimage(), Polyhedron_Preprocess(), Rays2Polyhedron(), Remove_Redundants(), SimplifyConstraints(), Stras_DomainSimplify(), SubConstraint(), align_context(), and traite_m_face().
Polyhedron* Polyhedron_Image (Polyhedron * Pol, Matrix * Func, unsigned NbMaxConstrs)
Definition at line 3838 of file polyhedron.c.
Referenced by DomainImage().
Polyhedron* Polyhedron_Preimage (Polyhedron * Pol, Matrix * Func, unsigned NbMaxRays)
Definition at line 3733 of file polyhedron.c.
Referenced by DomainPreimage(), Enumerate_NoParameters(), and Polyhedron_Enumerate().
void Polyhedron_Print (FILE * Dst, char * Format, Polyhedron * Pol)
Definition at line 1767 of file polyhedron.c.
Referenced by Compute_PDomains(), Constraints2Polyhedron(), Elim_Columns(), Enumerate_NoParameters(), Find_m_faces(), PolyPrint(), PolyhedronLTQ(), Polyhedron_Enumerate(), Polyhedron_Preprocess(), PreElim_Columns(), Rays2Polyhedron(), ZPolyhedronPrint(), and traite_m_face().
void Polyhedron_PrintConstraints (FILE * Dst, char * Format, Polyhedron * Pol)
Definition at line 4351 of file polyhedron.c.
Referenced by AffConstraints().
Polyhedron* Polyhedron_Scan (Polyhedron * D, Polyhedron * C, unsigned NbMaxRays)
Definition at line 3570 of file polyhedron.c.
Referenced by Enumerate_NoParameters(), Polyhedron_Enumerate(), Polyhedron_Not_Empty(), and Polyhedron_Preprocess().
void RaySort (Matrix * Ray, SatMatrix * Sat, int NbBid, int NbRay, int * equal_bound, int * sup_bound, unsigned RowSize1, unsigned RowSize2, unsigned bx, unsigned jx) [static]
Definition at line 284 of file polyhedron.c.
Referenced by Chernikova().
Polyhedron* Rays2Polyhedron (Matrix * Ray, unsigned NbMaxConstrs)
Definition at line 2036 of file polyhedron.c.
Referenced by Polyhedron_Image(), and traite_m_face().
Polyhedron* Remove_Redundants (Matrix * Mat, Matrix * Ray, SatMatrix * Sat, unsigned * Filter) [static]
Definition at line 824 of file polyhedron.c.
Referenced by AddConstraints(), AddRays(), Constraints2Polyhedron(), Rays2Polyhedron(), SimplifyConstraints(), and SubConstraint().
SatMatrix* SMAlloc (int rows, int cols) [static]
Definition at line 92 of file polyhedron.c.
void SMFree (SatMatrix ** matrix) [static]
Definition at line 128 of file polyhedron.c.
void SMPrint (SatMatrix * matrix) [static]
Definition at line 141 of file polyhedron.c.
Referenced by Chernikova(), Constraints2Polyhedron(), and Rays2Polyhedron().
void SatVector_OR (int * p1, int * p2, int * p3, unsigned length) [static]
Definition at line 159 of file polyhedron.c.
Referenced by Chernikova().
int SimplifyConstraints (Polyhedron * Pol1, Polyhedron * Pol2, unsigned * Filter, unsigned NbMaxRays) [static]
Definition at line 2976 of file polyhedron.c.
Referenced by DomainSimplify(), and Stras_DomainSimplify().
void SimplifyEqualities (Polyhedron * Pol1, Polyhedron * Pol2, unsigned * Filter) [static]
Definition at line 3056 of file polyhedron.c.
Referenced by DomainSimplify().
Polyhedron* Stras_DomainSimplify (Polyhedron * Pol1, Polyhedron * Pol2, unsigned NbMaxRays)
Definition at line 3215 of file polyhedron.c.
Polyhedron* SubConstraint (Value * Con, Polyhedron * Pol, unsigned NbMaxRays, int Pass)
Definition at line 2388 of file polyhedron.c.
Referenced by Disjoint_Domain(), DomainDifference(), and PDomainDifference().
SatMatrix* TransformSat (Matrix * Mat, Matrix * Ray, SatMatrix * Sat) [static]
Definition at line 245 of file polyhedron.c.
Referenced by AddRays(), and Rays2Polyhedron().
Polyhedron* Universe_Polyhedron (unsigned Dimension)
Definition at line 1883 of file polyhedron.c.
Referenced by Constraints2Polyhedron(), Enumerate_NoParameters(), Find_m_faces(), GenParamPolyhedron(), Polyhedron_Enumerate(), and Polyhedron_Preprocess().
void addToFilter (int k, unsigned * Filter, SatMatrix * Sat, Value * tmpR, Value * tmpC, int NbRays, int NbConstraints) [static]
Definition at line 2712 of file polyhedron.c.
Referenced by FindSimple().
Polyhedron* align_context (Polyhedron * Pol, int align_dimension, int NbMaxRays)
Definition at line 3498 of file polyhedron.c.
Referenced by Find_m_faces(), and Polyhedron_Scan().
void errormsg1 (char * f, char * msgname, char * msg)
Definition at line 28 of file errormsg.c.
Referenced by AddConstraints(), AddRays(), Chernikova(), Constraints2Polyhedron(), Disjoint_Domain(), DomainAddConstraints(), DomainAddRays(), DomainCost(), DomainDifference(), DomainIntersection(), DomainSimplify(), DomainUnion(), Empty_Polyhedron(), FindSimple(), Gauss(), GaussSimplify(), Matrix_Alloc(), Matrix_Read(), Matrix_Read_Input(), Polyhedron2Constraints(), Polyhedron2Rays(), PolyhedronLTQ(), Polyhedron_Alloc(), Polyhedron_Copy(), Polyhedron_Image(), Polyhedron_Preimage(), Polyhedron_Scan(), Rays2Polyhedron(), Remove_Redundants(), SMAlloc(), SimplifyConstraints(), SimplifyEqualities(), Stras_DomainSimplify(), SubConstraint(), Universe_Polyhedron(), Vector_Alloc(), Vector_Read(), align_context(), exist_points(), hermite(), left_hermite(), and right_hermite().
int lower_upper_bounds (int pos, Polyhedron * P, Value * context, Value * LBp, Value * UBp)
Definition at line 3625 of file polyhedron.c.
Referenced by P_Enum(), cherche_min(), count_points(), and exist_points().
Variable Documentation
int Pol_status
Definition at line 72 of file polyhedron.c.