SolveDio.c File Reference
#include <stdlib.h>
#include <polylib/polylib.h>
Functions
void RearrangeMatforSolveDio (Matrix *M)
When rank < hermi->NbRows; Verifying whether the solution agrees with the remaining n-rank rows as well.
int SolveDiophantine (Matrix *M, Matrix **U, Vector **X)
Function Documentation
void RearrangeMatforSolveDio (Matrix * M) [static]
When rank < hermi->NbRows; Verifying whether the solution agrees with the remaining n-rank rows as well.
*
Definition at line 233 of file SolveDio.c.
Referenced by SolveDiophantine().
int SolveDiophantine (Matrix * M, Matrix ** U, Vector ** X)
Definition at line 64 of file SolveDio.c.
Referenced by LatticeIntersection(), LatticePreimage(), and findHermiteBasis().