vector.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <polylib/polylib.h>
Functions
void Factorial (int n, Value *fact)
void Binomial (int n, int p, Value *result)
void CNP (int a, int b, Value *result)
void Gcd (Value a, Value b, Value *result)
int First_Non_Zero (Value *p, unsigned length)
Vector * Vector_Alloc (unsigned length)
void Vector_Free (Vector *vector)
void Vector_Print (FILE *Dst, char *Format, Vector *vector)
Vector * Vector_Read ()
void Vector_Set (Value *p, int n, unsigned length)
void Vector_Exchange (Value *p1, Value *p2, unsigned length)
void Vector_Copy (Value *p1, Value *p2, unsigned length)
void Vector_Add (Value *p1, Value *p2, Value *p3, unsigned length)
void Vector_Sub (Value *p1, Value *p2, Value *p3, unsigned length)
void Vector_Or (Value *p1, Value *p2, Value *p3, unsigned length)
void Vector_Scale (Value *p1, Value *p2, Value lambda, unsigned length)
void Vector_AntiScale (Value *p1, Value *p2, Value lambda, unsigned length)
void Inner_Product (Value *p1, Value *p2, unsigned length, Value *ip)
void Vector_Max (Value *p, unsigned length, Value *max)
void Vector_Min (Value *p, unsigned length, Value *min)
void Vector_Combine (Value *p1, Value *p2, Value *p3, Value lambda, Value mu, unsigned length)
int Vector_Equal (Value *Vec1, Value *Vec2, unsigned n)
void Vector_Min_Not_Zero (Value *p, unsigned length, int *index, Value *min)
void Vector_Gcd (Value *p, unsigned length, Value *min)
void Vector_Map (Value *p1, Value *p2, Value *p3, unsigned length, Value *(*f)())
void Vector_Normalize (Value *p, unsigned length)
void Vector_Normalize_Positive (Value *p, int length, int pos)
void Vector_Reduce (Value *p, unsigned length, void(*f)(Value, Value *), Value *r)
void Vector_Sort (Value *vector, unsigned n)
Function Documentation
void Binomial (int n, int p, Value * result)
Definition at line 44 of file vector.c.
void CNP (int a, int b, Value * result)
Definition at line 72 of file vector.c.
void Factorial (int n, Value * fact)
Definition at line 26 of file vector.c.
Referenced by Binomial().
int First_Non_Zero (Value * p, unsigned length)
Definition at line 120 of file vector.c.
void Gcd (Value a, Value b, Value * result)
Definition at line 99 of file vector.c.
Referenced by CalcBase(), Combine(), GaussSimplify(), Lcm(), MatInverse(), Matrix_Inverse(), Orthogonal_Base(), P_Enum(), Print_Vertex(), Scan_Vertices(), Soustraire_ligne(), TestRank(), eadd(), emul(), new_eadd(), old_Polyhedron_Preprocess(), ppcm(), and rat_prodmat().
void Inner_Product (Value * p1, Value * p2, unsigned length, Value * ip)
Definition at line 362 of file vector.c.
Referenced by lower_upper_bounds().
void Vector_Add (Value * p1, Value * p2, Value * p3, unsigned length)
Definition at line 269 of file vector.c.
Vector* Vector_Alloc (unsigned length)
Definition at line 137 of file vector.c.
Referenced by Orthogonal_Base(), Polyhedron_Image_Enumerate(), SolveDiophantine(), and Vector_Read().
void Vector_AntiScale (Value * p1, Value * p2, Value lambda, unsigned length)
Definition at line 344 of file vector.c.
void Vector_Combine (Value * p1, Value * p2, Value * p3, Value lambda, Value mu, unsigned length)
Definition at line 422 of file vector.c.
Referenced by Combine(), GaussSimplify(), and old_Polyhedron_Preprocess().
void Vector_Copy (Value * p1, Value * p2, unsigned length)
Definition at line 252 of file vector.c.
Referenced by AddConstraints(), AddRays(), Chernikova(), DomainSimplify(), FindSimple(), Find_m_faces(), Polyhedron2Constraints(), Polyhedron2Rays(), Polyhedron_Copy(), Polyhedron_Preprocess(), Remove_Redundants(), SimplifyConstraints(), SimplifyEqualities(), Stras_DomainSimplify(), SubConstraint(), right_hermite(), and traite_m_face().
int Vector_Equal (Value * Vec1, Value * Vec2, unsigned n)
Definition at line 453 of file vector.c.
void Vector_Exchange (Value * p1, Value * p2, unsigned length)
Definition at line 239 of file vector.c.
Referenced by Chernikova(), Gauss(), GaussSimplify(), RaySort(), Remove_Redundants(), and hermite().
void Vector_Free (Vector * vector)
Definition at line 162 of file vector.c.
Referenced by LatticeIntersection(), LatticePreimage(), Polyhedron_Image_Enumerate(), and findHermiteBasis().
void Vector_Gcd (Value * p, unsigned length, Value * min)
Definition at line 513 of file vector.c.
Referenced by Gauss(), GaussSimplify(), MatInverse(), Matrix_Inverse(), Orthogonal_Base(), Vector_Normalize(), and Vector_Normalize_Positive().
void Vector_Map (Value * p1, Value * p2, Value * p3, unsigned length, Value *(* f)())
Definition at line 562 of file vector.c.
void Vector_Max (Value * p, unsigned length, Value * max)
Definition at line 385 of file vector.c.
void Vector_Min (Value * p, unsigned length, Value * min)
Definition at line 402 of file vector.c.
void Vector_Min_Not_Zero (Value * p, unsigned length, int * index, Value * min)
Definition at line 475 of file vector.c.
Referenced by Vector_Gcd().
void Vector_Normalize (Value * p, unsigned length)
Definition at line 582 of file vector.c.
Referenced by Combine(), GaussSimplify(), and old_Polyhedron_Preprocess().
void Vector_Normalize_Positive (Value * p, int length, int pos)
Definition at line 610 of file vector.c.
Referenced by MatInverse(), and rat_prodmat().
void Vector_Or (Value * p1, Value * p2, Value * p3, unsigned length)
Definition at line 307 of file vector.c.
void Vector_Print (FILE * Dst, char * Format, Vector * vector)
Definition at line 176 of file vector.c.
Vector* Vector_Read ()
Definition at line 198 of file vector.c.
void Vector_Reduce (Value * p, unsigned length, void(* f)(Value, Value *), Value * r)
Definition at line 630 of file vector.c.
void Vector_Scale (Value * p1, Value * p2, Value lambda, unsigned length)
Definition at line 326 of file vector.c.
void Vector_Set (Value * p, int n, unsigned length)
Definition at line 223 of file vector.c.
Referenced by Constraints2Polyhedron(), Empty_Polyhedron(), Enumerate_NoParameters(), FindSimple(), Find_m_faces(), MatInverse(), Matrix_Inverse(), PolyhedronLTQ(), Polyhedron_Enumerate(), Polyhedron_Not_Empty(), Polyhedron_Scan(), Rays2Polyhedron(), Remove_Redundants(), Universe_Polyhedron(), align_context(), left_hermite(), and right_hermite().
void Vector_Sort (Value * vector, unsigned n)
Definition at line 646 of file vector.c.
void Vector_Sub (Value * p1, Value * p2, Value * p3, unsigned length)
Definition at line 288 of file vector.c.