Zpolyhedron.c File Reference
#include <polylib/polylib.h>
Compounds
struct forsimplify
Typedefs
typedef forsimplify ForSimplify
Functions
ZPolyhedron * ZPolyhedronIntersection (ZPolyhedron *, ZPolyhedron *)
ZPolyhedron * ZPolyhedron_Copy (ZPolyhedron *A)
void ZPolyhedron_Free (ZPolyhedron *Zpol)
ZPolyhedron * ZPolyhedronDifference (ZPolyhedron *, ZPolyhedron *)
ZPolyhedron * ZPolyhedronImage (ZPolyhedron *, Matrix *)
ZPolyhedron * ZPolyhedronPreimage (ZPolyhedron *, Matrix *)
ZPolyhedron * AddZPolytoZDomain (ZPolyhedron *A, ZPolyhedron *Head)
void ZPolyhedronPrint (FILE *fp, char *format, ZPolyhedron *A)
Bool isEmptyZPolyhedron (ZPolyhedron *Zpol)
ZPolyhedron * ZPolyhedron_Alloc (Lattice *Lat, Polyhedron *Poly)
void ZDomain_Free (ZPolyhedron *Head)
ZPolyhedron * ZDomain_Copy (ZPolyhedron *Head)
ZPolyhedron * AddZPoly2ZDomain (ZPolyhedron *Zpol, ZPolyhedron *Result)
ZPolyhedron * EmptyZPolyhedron (int dimension)
Bool ZDomainIncludes (ZPolyhedron *A, ZPolyhedron *B)
Bool ZPolyhedronIncludes (ZPolyhedron *A, ZPolyhedron *B)
void ZDomainPrint (FILE *fp, char *format, ZPolyhedron *A)
ZPolyhedron * ZDomainUnion (ZPolyhedron *A, ZPolyhedron *B)
ZPolyhedron * ZDomainIntersection (ZPolyhedron *A, ZPolyhedron *B)
ZPolyhedron * ZDomainDifference (ZPolyhedron *A, ZPolyhedron *B)
ZPolyhedron * ZDomainImage (ZPolyhedron *A, Matrix *Func)
ZPolyhedron * ZDomainPreimage (ZPolyhedron *A, Matrix *Func)
void CanonicalForm (ZPolyhedron *Zpol, ZPolyhedron **Result, Matrix **Basis)
ZPolyhedron * IntegraliseLattice (ZPolyhedron *A)
ZPolyhedron * ZDomainSimplify (ZPolyhedron *ZDom)
ZPolyhedron * SplitZpolyhedron (ZPolyhedron *ZPol, Lattice *B)
Typedef Documentation
typedef struct forsimplify ForSimplify
Function Documentation
ZPolyhedron* AddZPoly2ZDomain (ZPolyhedron * Zpol, ZPolyhedron * Result) [static]
Definition at line 122 of file Zpolyhedron.c.
Referenced by SplitZpolyhedron(), ZDomainDifference(), and ZPolyhedronDifference().
ZPolyhedron * AddZPolytoZDomain (ZPolyhedron * A, ZPolyhedron * Head) [static]
Definition at line 149 of file Zpolyhedron.c.
Referenced by ZDomainDifference(), ZDomainImage(), ZDomainIntersection(), ZDomainPreimage(), ZDomainUnion(), and ZPolyhedronDifference().
void CanonicalForm (ZPolyhedron * Zpol, ZPolyhedron ** Result, Matrix ** Basis)
Definition at line 741 of file Zpolyhedron.c.
Referenced by AddZPolytoZDomain().
ZPolyhedron* EmptyZPolyhedron (int dimension)
Definition at line 243 of file Zpolyhedron.c.
Referenced by IntegraliseLattice(), ZDomainDifference(), ZDomainImage(), ZDomainIntersection(), ZDomainPreimage(), ZDomainSimplify(), ZPolyhedronDifference(), ZPolyhedronIntersection(), and ZPolyhedronPreimage().
ZPolyhedron* IntegraliseLattice (ZPolyhedron * A)
Definition at line 832 of file Zpolyhedron.c.
Referenced by ZPolyhedron_Alloc().
ZPolyhedron* SplitZpolyhedron (ZPolyhedron * ZPol, Lattice * B)
Definition at line 949 of file Zpolyhedron.c.
ZPolyhedron* ZDomainDifference (ZPolyhedron * A, ZPolyhedron * B)
Definition at line 412 of file Zpolyhedron.c.
Referenced by ZDomainIncludes().
ZPolyhedron* ZDomainImage (ZPolyhedron * A, Matrix * Func)
Definition at line 466 of file Zpolyhedron.c.
Bool ZDomainIncludes (ZPolyhedron * A, ZPolyhedron * B)
Definition at line 268 of file Zpolyhedron.c.
ZPolyhedron* ZDomainIntersection (ZPolyhedron * A, ZPolyhedron * B)
Definition at line 375 of file Zpolyhedron.c.
ZPolyhedron* ZDomainPreimage (ZPolyhedron * A, Matrix * Func)
Definition at line 494 of file Zpolyhedron.c.
void ZDomainPrint (FILE * fp, char * format, ZPolyhedron * A)
Definition at line 317 of file Zpolyhedron.c.
ZPolyhedron* ZDomainSimplify (ZPolyhedron * ZDom)
Definition at line 865 of file Zpolyhedron.c.
ZPolyhedron* ZDomainUnion (ZPolyhedron * A, ZPolyhedron * B)
Definition at line 353 of file Zpolyhedron.c.
Referenced by ZDomainSimplify().
ZPolyhedron* ZDomain_Copy (ZPolyhedron * Head)
Definition at line 97 of file Zpolyhedron.c.
Referenced by CanonicalForm(), and ZPolyhedronDifference().
void ZDomain_Free (ZPolyhedron * Head)
Definition at line 72 of file Zpolyhedron.c.
Referenced by AddZPoly2ZDomain(), AddZPolytoZDomain(), ZDomainDifference(), and ZDomainIncludes().
ZPolyhedron * ZPolyhedronDifference (ZPolyhedron * A, ZPolyhedron * B) [static]
Definition at line 572 of file Zpolyhedron.c.
Referenced by ZDomainDifference().
ZPolyhedron * ZPolyhedronImage (ZPolyhedron * ZPol, Matrix * Func) [static]
Definition at line 649 of file Zpolyhedron.c.
Referenced by ZDomainImage().
Bool ZPolyhedronIncludes (ZPolyhedron * A, ZPolyhedron * B)
Definition at line 285 of file Zpolyhedron.c.
Referenced by AddZPolytoZDomain().
ZPolyhedron * ZPolyhedronIntersection (ZPolyhedron * A, ZPolyhedron * B) [static]
Definition at line 527 of file Zpolyhedron.c.
Referenced by ZDomainIntersection().
ZPolyhedron * ZPolyhedronPreimage (ZPolyhedron * Zpol, Matrix * G) [static]
Definition at line 699 of file Zpolyhedron.c.
Referenced by ZDomainPreimage().
void ZPolyhedronPrint (FILE * fp, char * format, ZPolyhedron * A) [static]
Definition at line 337 of file Zpolyhedron.c.
Referenced by ZDomainPrint().
ZPolyhedron* ZPolyhedron_Alloc (Lattice * Lat, Polyhedron * Poly)
Definition at line 37 of file Zpolyhedron.c.
Referenced by AddZPolytoZDomain(), CanonicalForm(), EmptyZPolyhedron(), IntegraliseLattice(), SplitZpolyhedron(), ZDomainSimplify(), ZPolyhedronDifference(), ZPolyhedronImage(), ZPolyhedronIntersection(), ZPolyhedronPreimage(), and ZPolyhedron_Copy().
ZPolyhedron * ZPolyhedron_Copy (ZPolyhedron * A) [static]
Definition at line 110 of file Zpolyhedron.c.
Referenced by AddZPoly2ZDomain(), ZDomainDifference(), ZDomainSimplify(), and ZDomain_Copy().
void ZPolyhedron_Free (ZPolyhedron * Zpol) [static]
Definition at line 84 of file Zpolyhedron.c.
Referenced by AddZPolytoZDomain(), SplitZpolyhedron(), ZDomainImage(), ZDomainIntersection(), ZDomainPreimage(), ZDomainSimplify(), ZDomain_Free(), ZPolyhedronDifference(), ZPolyhedronIntersection(), and ZPolyhedron_Alloc().
Bool isEmptyZPolyhedron (ZPolyhedron * Zpol)
Definition at line 22 of file Zpolyhedron.c.
Referenced by AddZPoly2ZDomain(), AddZPolytoZDomain(), CanonicalForm(), ZDomainIncludes(), and ZPolyhedronDifference().