// Make sure that useful scooping is not lost


// The C source code is wrong on purpose. This is designed to track a
// bug in the code generated by PIPS and shown by Fabien in FREIA OOP
// application

void foo(int x)
{
}

void sequence01()
{
  int i = 4;

  {
    int j;
  }

  foo(j);
  //j = 2;

  return;
}
