// Make sure that useful scoping is not lost: the sequence containing
// "int j;" must stay a block. simplify_control must delete the spurious
// declaration "int j;".

// Apparently, simplify_control fails to clean up the declaration list
// at the block level, which may explain why the empty block is
// preserved. So the current output is correct, but buggy. An internal
// consistency check would probably detect the issue.


// The C source code is wrong on purpose. This is designed to track a
// bug in the code generated by PIPS and shown by Fabien in FREIA OOP
// application

void foo(int x)
{
}

void sequence01()
{
  int i = 4;

  {
    int j;
  }

  foo(j);
  //j = 2;

  return;
}
