// lhs and rhs with store dependent subscripts
// also tests elimination of syntactically equivalent pointer_values
// generated by b[++i] = a (b[*] == a(may) is redundant with a==b[*] (may))

// b[i] must be initialized to obey rule by Pierre Jouvelot about
// undefined values

#include <stdlib.h>

int main()
{
  int *a;
  int * b[10];
  int i = 5;
  b[i] = &i;
  a = b[i];
  b[++i] = a;
  return(0);
}
