# $Id$

INSTALL_EXE = \
	make_all_specs\
	newgen

INSTALL_UTL = \
	test_newgen_type_translation.sh \
	test_newgen_type_translation.pl \
	tabulated_count.pl

ROOT	= ../..
include $(ROOT)/makes/main.mk
