      program test2
 9060 FORMAT (/10X, 114HLOCALIZATION HAS BEEN UNSUCESSFUL. PROGRAM WILL 
     +RESTART WITH NEW RANDOM NUMBER AND ROTATION SEQUENCE FOR ORBITALS.
     +)
      print 9060
      end
