// Simplify control must be applied twice to get rid of the useless
// subsequence

// Surprisingly, the calls to foo(), which have no memory effect, are
// not removed. Note that they can have a control effect if the called
// function does not return.


// The C source code is wrong on purpose. This is designed to track a
// bug in the code generated by PIPS and shown by Fabien in FREIA OOP
// application

void foo(int x)
{
}

void sequence02()
{
  int i = 4;

  {
    int j;
    if(j!=j) {
      int k = 3;
      i = k;
    }
  }

  foo(j);
  foo(i);

  return;
}
