#
# $Id: makefile,v 1.1 2002/10/14 15:07:16 olaru Exp $
#

ROOT  = ../..

LIBRARY = ehrhart

# C files in this directory
SRCS = \
	ehrhart.c \
	ext_ehrhart.c \
	eval_ehrhart.c
	
#ehrhart_union.c \

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

