#
# $Id: makefile,v 1.2 2002/10/16 15:18:18 loechner Exp $
#

ROOT  = ../..

LIBRARY = ehrhart

# C files in this directory
SRCS = \
	ehrhart.c \
	ext_ehrhart.c \
	eval_ehrhart.c


# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

