#
# $Id: makefile,v 1.1 2002/10/14 15:06:21 olaru Exp $
#

ROOT  = ../..

LIBRARY = kernel

# C files in this directory
SRCS = \
	Lattice.c \
	NormalForms.c \
	Zpolyhedron.c \
	errormsg.c \
	param.c \
	polyparam.c \
	Matop.c \
	SolveDio.c \
	alpha.c \
	matrix.c \
	polyhedron.c \
	vector.c

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

