#
# $Id: makefile,v 1.1 2002/10/14 15:08:03 olaru Exp $
#

ROOT  = ../..

ME = source/arith

LIBRARY = arith

# C files in this directory
SRCS = \
	errors.c 

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

