# $Id$
#
# Copyright 1989-2014 MINES ParisTech
#
# This file is part of PIPS.
#
# PIPS is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# PIPS is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PIPS.  If not, see <http://www.gnu.org/licenses/>.
#

SCRIPTS = \
	Cdavinci \
	Fdavinci \
	Rdavinci \
	dg2dv.pl \
	cg2dot.pl \
	onegraph.pl \
	display_pips_daVinci \
	pips_graph2daVinci \
	pips_unstructured2daVinci \
	pips_unstructured2dot \
	pips_graph_display

INSTALL_UTL =	$(SCRIPTS)

# common stuff
ROOT    = ../../..
#PROJECT = pips
include $(ROOT)/makes/main.mk
