#! /bin/sh

#
# Build [-v] [-w wspace] [-m module] resource
#

USAGE="Usage: Build [-v] [-w wspace] [-m module] resource"

if [ $# -eq 0 ]
then	echo $USAGE >&2
	exit 2
fi

while getopts vw:m: opt
do
	case $opt in
	v)	VERBOSE=TRUE;;
	w)	OPT_PGM=$OPTARG;;
	m)	OPT_MOD=$OPTARG;;
	\?)	echo $USAGE >&2
		exit 2;;
	esac
done
shift `expr $OPTIND - 1`

if [ $# -eq 1 ]
then
	RES=$1
	shift
else
	echo $USAGE >&2
	exit 1
fi

if [ -z "$VERBOSE" ]
then
	Pips -w "$OPT_PGM" -m "$OPT_MOD" -b $RES 1>/dev/null || exit 1;
else
	Pips -w "$OPT_PGM" -m "$OPT_MOD" -b $RES 1>&2 || exit 1;
fi
