#! /bin/sh

#
# Perform [-w wspace] [-m module] rule
#

USAGE="Usage: Perform [-w wspace] [-m module] [-v] rule"

if [ $# -eq 0 ]
then	echo $USAGE >&2
	exit 2
fi

while getopts w:m:v opt
do
	case $opt in
	w)	OPT_PGM=$OPTARG;;
	m)	OPT_MOD=$OPTARG;;
	v)	VERBOSE=TRUE;;
	\?)	echo $USAGE >&2
		exit 2;;
	esac
done
shift `expr $OPTIND - 1`

if [ $# -eq 1 ]
then
	RULE=$1
	shift
else
	echo $USAGE >&2
	exit 1
fi

if [ -z "$VERBOSE" ]
then
	Pips -w "$OPT_PGM" -m "$OPT_MOD" -p $RULE 1>/dev/null || exit 1;
else
	Pips -w "$OPT_PGM" -m "$OPT_MOD" -p $RULE 1>&2 || exit 1;
fi
