# $Id: Makefile 2766 2010-11-17 15:37:14Z coelho $

PARALLEL_VALIDATION = 1
include ../validate.mk

#clean: local-clean
#local-clean:
#	$(RM) test.c threshold-sse.c threshold0 threshold1 filtre0 filtre1
#	$(RM) -r coremark.tmpdir
