# $Id$

SCRIPTS = \
	Cdavinci \
	Fdavinci \
	Rdavinci \
	filtre.pl \
	onegraph.pl \
	display_pips_daVinci \
	pips_graph2daVinci \
	pips_unstructured2daVinci

INSTALL_UTL =	$(SCRIPTS)

# common stuff
ifdef PIPS_ROOT
ROOT    = $(PIPS_ROOT)
else
ROOT    = ../../..
endif

#PROJECT = pips
include $(ROOT)/makes/main.mk
