DOCUMENT = trans
SOURCES = $(DOCUMENT).tex environnement.tex retro-ingenierie.tex synthese-code.tex
INSTALL_SUBDIR = $(INSTALL_DIR)/cours
INSTALL_DIR=$(HOME)/public_html/Presentations/Brest_2006
include $(HOME)/TeX/Makefile/trans.Makefile
