//Generated by c2fsm -s 
model apache1 {
var c,tk_sz;
//@parameters tk_sz;
states start,lbl_4,lbl_6;
transition t_14 :={
  from  := start;
  to    := lbl_4;
  guard := true;
  action:= c' = 0;
};
transition t_10 :={
  from  := lbl_4;
  to    := lbl_6;
  guard := true;
  action:=;
};
transition t_12 :={
  from  := lbl_6;
  to    := lbl_4;
  guard := true;
  action:=;
};
transition t_13 :={
  from  := lbl_6;
  to    := lbl_4;
  guard := (c+2 <= tk_sz);
  action:= c' = c+1;
};
}
strategy dumb {
    Region init := { state = start && (0 < tk_sz) };
}

