//Generated by c2fsm -s 
model dummy4 {
var t,t0,z;
//@parameters t0;
states stop,start,lbl_5;
transition t_19 :={
  from  := start;
  to    := lbl_5;
  guard := true;
  action:= t' = t0, z' = 0;
};
transition t_14 :={
  from  := lbl_5;
  to    := stop;
  guard := (54 <= z);
  action:=;
};
transition t_17 :={
  from  := lbl_5;
  to    := lbl_5;
  guard := (z <= 53);
  action:= t' = t+1, z' = z+3;
};
}
strategy dumb {
    Region init := { state = start && (0 < t0) };
}

