//Generated by c2fsm -s 
model esop_goubault1b {
var i,j;
//@parameters;
states stop,start,lbl_13,lbl_8;
transition t_34 :={
  from  := start;
  to    := lbl_8;
  guard := true;
  action:= i' = 3, j' = 9;
};
transition t_21 :={
  from  := lbl_13;
  to    := stop;
  guard := (j+1 <= i);
  action:=;
};
transition t_24 :={
  from  := lbl_13;
  to    := lbl_13;
  guard := (i <= j);
  action:= i' = i+2, j' = j-1;
};
transition t_28 :={
  from  := lbl_8;
  to    := lbl_13;
  guard := true;
  action:= i' = i+2, j' = j-1;
};
transition t_30 :={
  from  := lbl_8;
  to    := lbl_13;
  guard := true;
  action:= i' = i+2, j' = j-1;
};
}
strategy dumb {
    Region init := { state = start && true };
}

