#!/usr/local/bin/perl

# This takes a PIPS output file in the GRAPH format in stdin
# and generates a new one in the daVinci format on stdout.

# 	%A% ($Date: 1995/09/08 12:42:30 $, ) version $Revision$, got on %D%, %T% [%P%].\n Copyright (c) École des Mines de Paris Proprietary.	

# Ronan.Keryell@cri.ensmp.fr, 5/09/1995.

$statement_number = 0;
$indent_level = 0;
$output_statement_buffer = "";
@node_attribute_to_add = ();
@edge_attribute_to_add = ();

sub indent_string {
    local($i) = $indent_level;

    return " " x $indent_level;
}


sub output_indent {
    print &indent_string;
}


sub indent_plus {
    $indent_level += 2;
}

sub indent_minus {
    $indent_level -= 2;
}

sub output_a_statement_begin {
    local($label, $comment) = @_;
    &output_indent;
    print "l(\"$label\",\n";
    $indent_level += 2;
    &output_indent;
    print "n(\"$comment\",\n";
    $indent_level += 2;
    &output_indent;
    # Remove the \ and n at the end:
    chop $output_statement_buffer;
    chop $output_statement_buffer;
    print "[\n";
    &indent_plus;
    &add_a_node_attribute("OBJECT", $output_statement_buffer);
    &add_a_node_attribute("FONTFAMILY", "courier");
    $output_statement_buffer = "";
    &output_some_other_node_attributes;
    &indent_minus ;
    &output_indent;
    print "],\n";
    &output_indent;
    print "[\n";
    &indent_plus ;
}


sub output_a_successor {
    local($successor, $comment) = @_;

    &output_indent;
    print "e(\"$comment\", [";
    &output_some_other_edge_attributes;
    print "], r(\"$successor\")),\n";
}


sub output_a_statement_end {
    &indent_minus;
    &output_indent;
    print "]\n";
    &indent_minus;
    &output_indent;
    print " )\n";
    &indent_minus;
    &output_indent;
    print " ),\n";
}


sub output_some_other_node_attributes {
    while ($value = pop(@node_attribute_to_add)) {
	&output_indent;
	print "a(\"" . pop(@node_attribute_to_add) . "\", \"$value\"),\n";
    }
}
sub add_a_node_attribute {
    local($attribute, $value) = @_;
    push(@node_attribute_to_add, $attribute, $value);
}


sub output_some_other_edge_attributes {
    while ($value = pop(@edge_attribute_to_add)) {
	&output_indent;
	print "a(\"" . pop(@edge_attribute_to_add) . "\", \"$value\"),\n";
    }
}
sub add_an_edge_attribute {
    local($attribute, $value) = @_;
    push(@edge_attribute_to_add, $attribute, $value);
}


sub output_a_node {
    local($label, $name, $successors, $comment) = @_;
    &output_indent;
    print "l(\"$label\",\n";
    $indent_level += 2;
    &output_indent;
    print "n(\"$comment\",\n";
    $indent_level += 2;
    &output_indent;
    # Remove the \ and n at the end:
    chop $output_statement_buffer;
    chop $output_statement_buffer;
    print "[\n";
    &indent_plus ;
    &add_a_node_attribute("OBJECT", $name);
    &output_some_other_node_attributes;
    &indent_minus ;
    &output_indent;
    print "],\n";
    &output_indent;
    print "[\n";
    &indent_plus ;
    foreach $successor (split(/ /, $successors)) {
	&output_a_successor($successor, $comment);
    }
    &indent_minus;
    &output_indent;
    print "]\n";
    &indent_minus;
    &output_indent;
    print " )\n";
    &indent_minus;
    &output_indent;
    print " ),\n";
}


sub keep_for_output {
    local($string) = @_;
    $output_statement_buffer .= $string . "\\n";
}


print "[\n";
$indent_level += 2;
# The label of the statement:
$control = $statement_number;
&add_a_node_attribute("COLOR", "yellow");

while (<>) {
    #print;
    chop;
    # daVinci do not like at all TABs:
    s/\t/        /g;
    # Protect the "" :
    s/"/\\"/g;
    ($a_command_line = $_) =~ s/.(.*)/$1/;

    /^\200Unstructured (.*) end: (.*)$/ && do {
	# €Unstructured 0x3c79f0 end: 0x3c8f30
	$unstructured_begin = $1;
	$unstructured_end = $2;
	&output_a_statement_begin($control,
				  "Statement not from an unstructured");
	&output_a_successor($unstructured_begin,
			    "Go to the entry of the unstructured");
	&output_a_statement_end();
	$statement_number ++;
	# Keep track of the number of the statement that should follow
	# this unstructured at its exit:
	push(@statement_number_stack, $statement_number);
	&add_a_node_attribute("_GO", "ellipse");
	&add_a_node_attribute("COLOR", "lightgreen");
	next;
    };

    /^\201Unstructured End (.*) end: (.*)$/ && do {
	# Unstructured End 0x3cfa40 end: 0x3cfa40
	$unstructured_begin = $1;
	$unstructured_end = $2;
	$control = pop(@statement_number_stack);

	next;
    };

    /^\202Unstructured Item (.*)$/ && do {
	# \202Unstructured Item 0x3c79f0
	$control = $1;
	next;
    };

    /^\203Unstructured Successor ->(.*)$/ && do {
	# \203Unstructured Successor 0x3c8280
	@successors = split(/ /, $1);
	# Be careful, if there is something in the the successors, the first
	# blank generated a void element...
#	print "\n**** @successors, $#successors\n";
	if ($#successors == -1) {
	    &add_a_node_attribute("_GO", "ellipse");
	    &add_a_node_attribute("COLOR", "lightgray");   
	    &output_a_statement_begin($control, $a_command_line);
	    &output_a_successor($statement_number_stack[$#statement_number_stack],
				"The unstructured end point to the statement following the unstructured");
	}
	elsif ($#successors == 2) {
	    # 2 successors, that is an "if then else":
	    &add_a_node_attribute("_GO", "rhombus");
	    &add_a_node_attribute("COLOR", "cyan");
	    &output_a_statement_begin($control, $a_command_line);
	    &add_an_edge_attribute("EDGECOLOR", "red");
	    &output_a_successor("then_$statement_number", $a_command_line);
	    &add_an_edge_attribute("EDGECOLOR", "blue");
	    &output_a_successor("else_$statement_number", $a_command_line);
	    &output_a_statement_end();
	    &add_a_node_attribute("COLOR", "lightred");
	    &add_a_node_attribute("_GO", "text");
	    &add_a_node_attribute("FONTFAMILY", "helvetica");
	    &add_a_node_attribute("FONTSTYLE", "bold_italic");
	    &add_an_edge_attribute("EDGECOLOR", "red");
	    &output_a_node("then_$statement_number", "THEN",
			   $successors[1], $a_command_line);
	    &add_a_node_attribute("COLOR", "lightblue");
	    &add_a_node_attribute("_GO", "text");
	    &add_a_node_attribute("FONTFAMILY", "helvetica");
	    &add_a_node_attribute("FONTSTYLE", "bold_italic");
	    &add_an_edge_attribute("EDGECOLOR", "blue");
	    &output_a_node("else_$statement_number", "ELSE",
			   $successors[2], $a_command_line);
	    $statement_number ++;
	    next;
	    }
	    else {
		# Just a sequence I guess: */
		&output_a_statement_begin($control, $a_command_line);
		&output_a_successor($successors[1], $a_command_line);
	    }
	&output_a_statement_end();
	next;
    };

    # By default, put the statement with a an explicit \ n for daVinci:
    &keep_for_output($_);
}

&output_a_statement_begin($control,
			  "Statement not from an unstructured");
&output_a_statement_end();

print "]\n";
