#!/bin/sh
#
# $Id$
#
# a shell wrapper for "JPips", the java-based pips interface.
#
# $Log: jpips,v $
# Revision 1.9  1998/11/12 14:24:14  coelho
# -e option added to be used by emacs.
#
# Revision 1.8  1998/11/12 14:21:53  ancourt
# Tpips is a shell to 1
#
# Revision 1.7  1998/11/06 10:38:19  ancourt
# tpips is a shell for jpips.
#
# Revision 1.6  1998/10/17 10:00:09  coelho
# zip -> jar.
#
# Revision 1.5  1998/10/16 17:17:08  coelho
# updated and fixes for 1.2b4
#
# Revision 1.4  1998/07/03 07:06:01  coelho
# default menu is "basic" now.
#
# Revision 1.3  1998/07/02 17:10:34  coelho
# -d option added.
#
# Revision 1.2  1998/07/02 15:46:47  coelho
# fix for -n option.
#
# Revision 1.1  1998/07/01 16:15:32  coelho
# Initial revision
#
#

usage()
{
    cat <<-EOF >&2
	jpips [-m menu] [-h] [-n] [-d] [-e]
	-m menu: the type of menu that should be used (default: test)
	-h: some help
	-n: no console with jpips
	-d: debug
	-e: launched by emacs
EOF
}

error()
{
    ret=${1}
    shift
    echo "jpips: $@" >&2
    usage
    exit ${ret}
}

unset jpips forward menu_type

props="";
java_root=${JAVA_ROOT:-/usr/local/jdk1.2beta4}
jar=jpips.jar
gif=DownArrow.gif

while getopts m:hnde opt
do
    case ${opt} in
	m) menu_type=$OPTARG ;;
	h) usage ;;
	n) forward="${forward} -n" ;;
	d) props="${props} -Djava.compiler=NONE";;
	e) props="${props} -Djpips.emacs=true";;
	*) error 1 "unexpected option ${opt}" ;;
    esac
done

shift `expr $OPTIND - 1`

forward="${forward} $@"

# default menu is jpips_menus.basic.
men=jpips_menus.${menu_type:-basic}

#
# which jpips.zip file

if [ -f ${jar} ]
then
    jpips=${jar}
else
    if [ -f ${PIPS_ROOT}/Share/${jar} ]
    then
	jpips=${PIPS_ROOT}/Share/${jar}
    fi
fi

[ "$jpips" ] || error 2 "cannot find jpips.jar"

#
# which DownArrow.gif file

if [ -f ${gif} ]
then
    props="${props} -Djpips.downarrow=${gif}"
else
    if [ -f ${PIPS_ROOT}/Share/${gif} ]
    then
	props="${props} -Djpips.downarrow=${PIPS_ROOT}/Share/${gif}"
    fi
fi

#
# which menu

if [ -f ${men} ]
then
    props="${props} -Djpips.menus=${men}"
    unset men
else
    if [ -f ${PIPS_ROOT}/Share/${men} ]
    then
	props="${props} -Djpips.menus=${PIPS_ROOT}/Share/${men}"
	unset men
    fi
fi

[ ! "${men}" ] || error 3 "menu ${men} not found"

PATH="${JAVA_ROOT:-/usr/local/jdk1.2beta3}/bin:${PATH}"

#
# now do the job

export CLASSPATH

# always as a shell...

TPIPS_IS_A_SHELL=1

export TPIPS_IS_A_SHELL

# verbose execution...
set -x
CLASSPATH=${jpips}:${java_root}/lib/classes.zip:${CLASSPATH}
exec ${java_root}/bin/java ${props} JPips.JPips ${forward}
