/*
Declaration des intrinseques lies a la runtime de STEP
Fichier inclus par : src/Libs/bootstrap/bootstrap.c
*/

  {RT_STEP_get_myloopslice,1,overloaded_to_void_type,0,0},
  {RT_STEP_get_i_low,1,overloaded_to_void_type,0,0},
  {RT_STEP_get_i_up,1,overloaded_to_void_type,0,0},
  {RT_STEP_Init,0,overloaded_to_void_type,0,0},
  {RT_STEP_Finalize,0,overloaded_to_void_type,0,0},
  {RT_STEP_Barrier,0,overloaded_to_void_type,0,0},
  {RT_STEP_Get_size,1,overloaded_to_void_type,0,0},
  {RT_STEP_Get_rank,1,overloaded_to_void_type,0,0},
  {RT_STEP_Get_thread_num,1,void_to_integer_type,0,0},
  {RT_STEP_ComputeLoopSlices,6,overloaded_to_void_type,0,0},
  {RT_STEP_SizeRegion,2,integer_to_integer_type,0,0},
  {RT_STEP_WaitAll,2,overloaded_to_void_type,0,0},

  {RT_STEP_InitReduction "_I1",3,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction "_I1",3,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllScalar "_I1",2,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion "_I1",5,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion "_I1",10,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced "_I1",4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge "_I1",12,overloaded_to_void_type,0,0},
  {RT_STEP_InitReduction "_I2",3,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction "_I2",3,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllScalar "_I2",2,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion "_I2",5,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion "_I2",10,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced "_I2",4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge "_I2",12,overloaded_to_void_type,0,0},
  {RT_STEP_InitReduction "_I4",3,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction "_I4",3,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllScalar "_I4",2,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion "_I4",5,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion "_I4",10,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced "_I4",4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge "_I4",12,overloaded_to_void_type,0,0},
  {RT_STEP_InitReduction "_I8",3,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction "_I8",3,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllScalar "_I8",2,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion "_I8",5,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion "_I8",10,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced "_I8",4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge "_I8",12,overloaded_to_void_type,0,0},
  {RT_STEP_InitReduction "_R4",3,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction "_R4",3,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllScalar "_R4",2,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion "_R4",5,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion "_R4",10,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced "_R4",4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge "_R4",12,overloaded_to_void_type,0,0},
  {RT_STEP_InitReduction "_R8",3,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction "_R8",3,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllScalar "_R8",2,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion "_R8",5,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion "_R8",10,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced "_R8",4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge "_R8",12,overloaded_to_void_type,0,0},
  {RT_STEP_InitReduction "_C8",3,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction "_C8",3,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllScalar "_C8",2,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion "_C8",5,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion "_C8",10,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced "_C8",4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge "_C8",12,overloaded_to_void_type,0,0},
  {RT_STEP_InitReduction "_C16",3,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction "_C16",3,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllScalar "_C16",2,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion "_C16",5,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion "_C16",10,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced "_C16",4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge "_C16",12,overloaded_to_void_type,0,0},
