/*
Declaration des handlers des intrinseques lies a la runtime de STEP pour le prettyprinter
Fichier inclus par : src/Libs/ri-utils/prettyprint.c

Par defaut les appels aux intrinseques sont affiches sans "CALL" or dans le cas de subroutine il est necessaire.
*/


  {RT_STEP_get_myloopslice,words_call_intrinsic,0},
  {RT_STEP_get_i_low,words_call_intrinsic,0},
  {RT_STEP_get_i_up,words_call_intrinsic,0},
  {RT_STEP_Init,words_call_intrinsic,0},
  {RT_STEP_Finalize,words_call_intrinsic,0},
  {RT_STEP_Barrier,words_call_intrinsic,0},
  {RT_STEP_Get_size,words_call_intrinsic,0},
  {RT_STEP_Get_rank,words_call_intrinsic,0},
  {RT_STEP_Get_thread_num,words_call_intrinsic,0},
  {RT_STEP_ComputeLoopSlices,words_call_intrinsic,0},
  /*  {RT_STEP_SizeRegion,words_call_intrinsic,0}, c'est une function ! */
  {RT_STEP_WaitAll,words_call_intrinsic,0},

  {RT_STEP_InitReduction "_I1",words_call_intrinsic,0},
  {RT_STEP_Reduction "_I1",words_call_intrinsic,0},
  {RT_STEP_MasterToAllScalar "_I1",words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion "_I1",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion "_I1",words_call_intrinsic,0},
  {RT_STEP_InitInterlaced "_I1",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge "_I1",words_call_intrinsic,0},
  {RT_STEP_InitReduction "_I2",words_call_intrinsic,0},
  {RT_STEP_Reduction "_I2",words_call_intrinsic,0},
  {RT_STEP_MasterToAllScalar "_I2",words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion "_I2",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion "_I2",words_call_intrinsic,0},
  {RT_STEP_InitInterlaced "_I2",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge "_I2",words_call_intrinsic,0},
  {RT_STEP_InitReduction "_I4",words_call_intrinsic,0},
  {RT_STEP_Reduction "_I4",words_call_intrinsic,0},
  {RT_STEP_MasterToAllScalar "_I4",words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion "_I4",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion "_I4",words_call_intrinsic,0},
  {RT_STEP_InitInterlaced "_I4",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge "_I4",words_call_intrinsic,0},
  {RT_STEP_InitReduction "_I8",words_call_intrinsic,0},
  {RT_STEP_Reduction "_I8",words_call_intrinsic,0},
  {RT_STEP_MasterToAllScalar "_I8",words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion "_I8",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion "_I8",words_call_intrinsic,0},
  {RT_STEP_InitInterlaced "_I8",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge "_I8",words_call_intrinsic,0},
  {RT_STEP_InitReduction "_R4",words_call_intrinsic,0},
  {RT_STEP_Reduction "_R4",words_call_intrinsic,0},
  {RT_STEP_MasterToAllScalar "_R4",words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion "_R4",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion "_R4",words_call_intrinsic,0},
  {RT_STEP_InitInterlaced "_R4",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge "_R4",words_call_intrinsic,0},
  {RT_STEP_InitReduction "_R8",words_call_intrinsic,0},
  {RT_STEP_Reduction "_R8",words_call_intrinsic,0},
  {RT_STEP_MasterToAllScalar "_R8",words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion "_R8",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion "_R8",words_call_intrinsic,0},
  {RT_STEP_InitInterlaced "_R8",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge "_R8",words_call_intrinsic,0},
  {RT_STEP_InitReduction "_C8",words_call_intrinsic,0},
  {RT_STEP_Reduction "_C8",words_call_intrinsic,0},
  {RT_STEP_MasterToAllScalar "_C8",words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion "_C8",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion "_C8",words_call_intrinsic,0},
  {RT_STEP_InitInterlaced "_C8",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge "_C8",words_call_intrinsic,0},
  {RT_STEP_InitReduction "_C16",words_call_intrinsic,0},
  {RT_STEP_Reduction "_C16",words_call_intrinsic,0},
  {RT_STEP_MasterToAllScalar "_C16",words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion "_C16",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion "_C16",words_call_intrinsic,0},
  {RT_STEP_InitInterlaced "_C16",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge "_C16",words_call_intrinsic,0},
