/*
Declaration des intrinseques lies a la runtime de STEP
Fichier inclus par : src/Libs/bootstrap/bootstrap.c
*/
  {DIR_CALL,1,overloaded_to_void_type,0,0},
  {RT_STEP_get_myloopslice,1,overloaded_to_void_type,0,0},
  {RT_STEP_get_i_low,1,overloaded_to_void_type,0,0},
  {RT_STEP_get_i_up,1,overloaded_to_void_type,0,0},
  {RT_STEP_Init_Fortran_Order,0,overloaded_to_void_type,0,0},
  {RT_STEP_Init_C_Order,0,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_Spawn,0,overloaded_to_void_type,0,0},
  {RT_STEP_Finalize,0,overloaded_to_void_type,0,0},
  {RT_STEP_Barrier,0,overloaded_to_void_type,0,0},
  {RT_STEP_Get_Commsize,1,overloaded_to_void_type,0,0},
  {RT_STEP_Get_rank,1,overloaded_to_void_type,0,0},
  {RT_STEP_Get_thread_num,1,void_to_integer_type,0,0},
  {RT_STEP_ComputeLoopSlices,4,overloaded_to_void_type,0,0},
  {RT_STEP_GetLoopBounds,3,overloaded_to_void_type,0,0},
  {RT_STEP_SizeRegion,2,integer_to_integer_type,0,0},
  {RT_STEP_WaitAll,0,overloaded_to_void_type,0,0},
  {RT_STEP_Begin,1,overloaded_to_void_type,0,0},
  {RT_STEP_End,1,overloaded_to_void_type,0,0},
  {RT_STEP_Request,1,overloaded_to_void_type,0,0},
  {RT_STEP_Release,1,overloaded_to_void_type,0,0},
  {RT_STEP_Get_Nextprocess,1,overloaded_to_void_type,0,0},

  {RT_STEP_InitReduction,4,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction,4,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllScalar,6,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion,8,overloaded_to_void_type,0,0},
  {RT_STEP_AllToMasterRegion,8,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar,6,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion,8,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar,6,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion,8,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateScalar,6,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateRegion,8,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_Check_n_threads ,4,overloaded_to_void_type,0,0},
 
  {RT_STEP_AlltoAllRegion,11,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced,4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge,13,overloaded_to_void_type,0,0},

  {RT_STEP_InitArrayRegions,(INT_MAX),overloaded_to_void_type,0,0},
  {RT_STEP_Set_SendRegions,3,overloaded_to_void_type,0,0},
  {RT_STEP_Set_InterlacedSendRegions,3,overloaded_to_void_type,0,0},
  {RT_STEP_Set_ReductionSendRegions,3,overloaded_to_void_type,0,0},
  {RT_STEP_Set_RecvRegions,3,overloaded_to_void_type,0,0},
  {RT_STEP_AllToAll_Full,3,overloaded_to_void_type,0,0},
  {RT_STEP_AllToAll_FullInterlaced,3,overloaded_to_void_type,0,0},
  {RT_STEP_AllToAll_Partial,3,overloaded_to_void_type,0,0},
  {RT_STEP_AllToAll_PartialInterlaced,3,overloaded_to_void_type,0,0},

  {RT_STEP_InitReduction "_I1",3,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction "_I1",3,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_Check_n_threads "_I1",3,overloaded_to_void_type,0,0}, 	
  {RT_STEP_MasterToAllScalar "_I1",2,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion "_I1",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar "_I1",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion "_I1",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar "_I1",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion "_I1",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateScalar "_I1",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateRegion "_I1",5,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion "_I1",10,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced "_I1",4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge "_I1",12,overloaded_to_void_type,0,0},
  {RT_STEP_InitReduction "_I2",3,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction "_I2",3,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_Check_n_threads "_I2",3,overloaded_to_void_type,0,0}, 	
  {RT_STEP_MasterToAllScalar "_I2",2,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion "_I2",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar "_I2",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion "_I2",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar "_I2",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion "_I2",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateScalar "_I2",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateRegion "_I2",5,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion "_I2",10,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced "_I2",4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge "_I2",12,overloaded_to_void_type,0,0},
  {RT_STEP_InitReduction "_I4",3,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction "_I4",3,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_Check_n_threads "_I4",3,overloaded_to_void_type,0,0}, 	
  {RT_STEP_MasterToAllScalar "_I4",2,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion "_I4",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar "_I4",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion "_I4",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar "_I4",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion "_I4",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateScalar "_I4",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateRegion "_I4",5,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion "_I4",10,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced "_I4",4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge "_I4",12,overloaded_to_void_type,0,0},
  {RT_STEP_InitReduction "_I8",3,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction "_I8",3,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_Check_n_threads "_I8",3,overloaded_to_void_type,0,0}, 	
  {RT_STEP_MasterToAllScalar "_I8",2,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion "_I8",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar "_I8",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion "_I8",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar "_I8",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion "_I8",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateScalar "_I8",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateRegion "_I8",5,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion "_I8",10,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced "_I8",4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge "_I8",12,overloaded_to_void_type,0,0},
  {RT_STEP_InitReduction "_R4",3,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction "_R4",3,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_Check_n_threads "_R4",3,overloaded_to_void_type,0,0}, 	
  {RT_STEP_MasterToAllScalar "_R4",2,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion "_R4",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar "_R4",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion "_R4",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar "_R4",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion "_R4",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateScalar "_R4",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateRegion "_R4",5,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion "_R4",10,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced "_R4",4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge "_R4",12,overloaded_to_void_type,0,0},
  {RT_STEP_InitReduction "_R8",3,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction "_R8",3,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_Check_n_threads "_R8",3,overloaded_to_void_type,0,0}, 	
  {RT_STEP_MasterToAllScalar "_R8",2,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion "_R8",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar "_R8",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion "_R8",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar "_R8",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion "_R8",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateScalar "_R8",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateRegion "_R8",5,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion "_R8",10,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced "_R8",4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge "_R8",12,overloaded_to_void_type,0,0},
  {RT_STEP_InitReduction "_C8",3,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction "_C8",3,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_Check_n_threads "_C8",3,overloaded_to_void_type,0,0}, 	
  {RT_STEP_MasterToAllScalar "_C8",2,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion "_C8",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar "_C8",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion "_C8",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar "_C8",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion "_C8",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateScalar "_C8",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateRegion "_C8",5,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion "_C8",10,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced "_C8",4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge "_C8",12,overloaded_to_void_type,0,0},
  {RT_STEP_InitReduction "_C16",3,overloaded_to_void_type,0,0},
  {RT_STEP_Reduction "_C16",3,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_Check_n_threads "_C16",3,overloaded_to_void_type,0,0}, 	
  {RT_STEP_MasterToAllScalar "_C16",2,overloaded_to_void_type,0,0},
  {RT_STEP_MasterToAllRegion "_C16",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar "_C16",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion "_C16",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar "_C16",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion "_C16",5,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateScalar "_C16",2,overloaded_to_void_type,0,0},
  {RT_STEP_Critical_FinalUptodateRegion "_C16",5,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion "_C16",10,overloaded_to_void_type,0,0},
  {RT_STEP_InitInterlaced "_C16",4,overloaded_to_void_type,0,0},
  {RT_STEP_AlltoAllRegion_Merge "_C16",12,overloaded_to_void_type,0,0},
