#include <stdlib.h>
#include <stdio.h>
/* For strdup: */
// FI: already defined elsewhere
// #define _GNU_SOURCE
#include <string.h>

#include "genC.h"
#include "linear.h"
#include "ri.h"
#include "effects.h"
#include "database.h"
#include "ri-util.h"
#include "effects-util.h"
#include "constants.h"
#include "misc.h"
#include "parser_private.h"
#include "top-level.h"
#include "text-util.h"
#include "text.h"
#include "properties.h"
#include "effects-generic.h"
#include "effects-simple.h"
#include "effects-convex.h"
#include "pipsdbm.h"
#include "resources.h"
#include "newgen_set.h"
#include "points_to_private.h"
#include "alias-classes.h"
/* Points-to interprocedural analysis is inspired by the work of Wilson[95]. The documentation 
   of this phase is a chapter of Amira Mensi thesis. */



/*  Foreach real argument r and its corresponding formal one f  create the assignment f = r
    then compute points-to set s generated by the assignment.
    The result is the union of pt_caller and s
*/
set compute_points_to_binded_set(entity called_func, list real_args, set pt_caller)
{ 
  set s = set_generic_make(set_private, points_to_equal_p,
			   points_to_rank);
  set pt_binded = set_generic_make(set_private, points_to_equal_p,
				   points_to_rank);

  cons *pc;
  int ipc;
  s = set_assign(s, pt_caller);
  for (ipc = 1, pc = real_args; pc != NIL; pc = CDR(pc), ipc++) {
    expression rhs = EXPRESSION(CAR(pc));
    entity pf = find_ith_parameter(called_func, ipc);
    expression lhs = entity_to_expression(pf);
    //statement stmt = make_assign_statement(lhs, rhs);
    //s = set_assign(s, points_to_assignment(stmt, lhs, rhs, s));	
    s = set_assign(s, assignment_to_points_to(lhs, rhs, s));	
  }

  SET_FOREACH(points_to, pt, s) {
    reference r = cell_any_reference(points_to_sink(pt));
    entity e = reference_variable(r);
    if(entity_stub_sink_p(e))
      s = set_del_element(s,s,(void*)pt);
  }
  pt_binded = set_union(pt_binded, s, pt_caller);
  return pt_binded;
}


/* Filter out written effects on pointers */
list written_pointers_set(list eff) {
  list written_l = NIL;
  list wr_eff = effects_write_effects(eff);
  FOREACH(effect, ef, wr_eff) {
    if(effect_pointer_type_p(ef)){
      cell c = effect_cell(ef);
      written_l = gen_nconc(CONS(CELL, c, NIL), written_l);
    }
  }

  return written_l; 

}

/* For each stub cell e  find its formal corresponding parameter and add to it a dereferencing dimension */
/* cell formal_access_paths(cell e, list args, set pt_in) */
/* { */
/*   cell f_a = cell_undefined; */
/*   bool find_p = false; */

/*   FOREACH(CELL, c, args) { */
/*     SET_FOREACH(points_to, pt, pt_in) { */
/*       if(points_to_cell_equal_p(c, points_to_source(pt)) && points_to_cell_equal_p(e, points_to_sink(pt))) */
/* 	{ */
/* 	  find_p = true; */
/* 	  f_a = add_array_dimension(c); */
/* 	  break ; */
/* 	} */
/*     } */
/*     if(!find_p && points_to_cell_equal_p(e, points_to_sink(pt))) */
/*       { */
/* 	cell new_e = points_to_source(pt); */
/* 	cell c  = formal_access_paths(new_e, args, pt_in); */
/* 	f_a = add_array_dimension(c); */
/* 	break ; */
/*       } */
/*     } */

  
/*   if(cell_undefined_p(f_a))  */
/*     pips_user_error("Formal acces paths undefined \n"); */

/*   return f_a; */
/* } */

/* For each stub cell e  find its formal corresponding parameter and add to it a dereferencing dimension */
cell formal_access_paths(cell e, list args, set pt_in)
{
  int i;
  cell f_a = cell_undefined;
  reference r1 = cell_any_reference(e);
  reference r = reference_undefined;
  entity v1 = reference_variable(r1);
  const char * en1 = entity_local_name(v1);
  list sl = NIL; 
  bool change_p = false ;
  while(!ENDP(args) && !change_p) {
    cell c = CELL(CAR(args));
    reference r2 = cell_to_reference(c);
    entity v2 = reference_variable(r2);
    const char * en2 = entity_local_name(v2);
    char *cmp = strstr(en1, en2);
    r = copy_reference(r2);
    for(i = 0; cmp != NULL && cmp[i]!= '\0' ; i++) {
      if(cmp[i]== '_') 	{
	expression s =  int_to_expression(0);
	sl = CONS(EXPRESSION, s, sl);
	change_p = true;
      }
    }
    if(change_p) {
      reference_indices(r) = gen_nconc(reference_indices(r), sl);
      f_a = make_cell_reference(r);  
      break ;
    }
    args = CDR(args);
  }
 
  if(cell_undefined_p(f_a)) 
    pips_user_error("Formal acces paths undefined \n");

  return f_a;
}


/* Evalute c using points-to relation already computed */ 
list actual_access_paths(cell c, set pt_binded)
{
  bool exact_p = false;
  set_methods_for_proper_simple_effects();
  list l_in = set_to_sorted_list(pt_binded,
				 (int(*)(const void*, const void*))
				 points_to_compare_location);
  list l = eval_cell_with_points_to(c, l_in, &exact_p);
  generic_effects_reset_all_methods();
  return l;
}



/* Translate each element of E into the caller's scope */
list caller_addresses(cell c, list args, set pt_in, set pt_binded)
{
  
  cell c_f = formal_access_paths(c, args, pt_in);
  list a_p = actual_access_paths(c_f, pt_binded);
  return a_p;
}


/* Add cells referencing a points-to stub found in parameter "s" are
 * copied and added to list "osl".
 *
 * The stubs are returned as cells not as entities.
 *
 * New cells are allocated. No sharing is created between parameter
 * "s" and result "sl".
 */
list points_to_set_to_stub_cell_list(pt_map s, list osl)
{
  list sl = osl;
  SET_FOREACH(points_to, pt, s) {
    cell sink = points_to_sink(pt);
    reference r1 = cell_any_reference(sink);
    entity e1 = reference_variable(r1);
    if(entity_stub_sink_p(e1) && !points_to_cell_in_list_p(sink, sl))
      sl = CONS(CELL, copy_cell(sink), sl);
      
    cell source = points_to_source(pt);
    reference r2 = cell_any_reference(source);
    entity e2 = reference_variable(r2);
    if(entity_stub_sink_p(e2) && !points_to_cell_in_list_p(source, sl))
      sl = CONS(CELL, copy_cell(source), sl);
  }
  
  gen_sort_list(sl, (gen_cmp_func_t) points_to_compare_ptr_cell );
  ifdebug(1) print_points_to_cells(sl);
  return sl;
}


/* returns all the element of E, the set of stubs created when the callee is analyzed.
 *
 * E = {e in pt_in U pt_out|entity_stub_sink_p(e)}
 *
 * FI->AM: a[*][*] or p[next] really are elements of set E?
 */
list stubs_list(pt_map pt_in, pt_map pt_out)
{
  list sli = points_to_set_to_stub_cell_list(pt_in, NIL);
  list slo = points_to_set_to_stub_cell_list(pt_out, sli);
  return slo;
}

/* Check compatibility of points-to set pt_in of the callee and
 * pt_binded of the call site in the caller.
 *
 * Parameter "stubs" is the set E in the intraprocedural and
 * interprocedural analysis chapters of Amira Mensi's PhD
 * dissertation. The list "stubs" contains all the stubs generated
 * when the callee is analyzed.
 *
 * Parameter "args" is a list of cells. Each cell is a reference to a
 * formal parameter of the callee.
 */
bool sets_binded_and_in_compatibles_p(list stubs, list args, set pt_binded, set pt_in, set pt_out)
{
  bool compatible_p = true;
  list tmp = gen_full_copy_list(stubs);
  gen_sort_list(args, (gen_cmp_func_t) points_to_compare_ptr_cell );
  pt_map io = new_pt_map();
  io = set_union(io, pt_in, pt_out);

  while(!ENDP(stubs) && compatible_p) {
    cell st = CELL(CAR(stubs));
    FOREACH(CELL, c, tmp) {
      if(! points_to_cell_equal_p(c, st)) {
	list act1 = caller_addresses(c, args, io, pt_binded);
	list act2 = caller_addresses(st, args, io, pt_binded);
	points_to_cell_list_and(&act1, act2);
	if(!ENDP(act1)) {
	  entity ne = entity_null_locations();
	  reference nr = make_reference(ne, NIL);
	  cell nc = make_cell_reference(nr);
	  entity he =  entity_all_heap_locations();
	  reference hr = make_reference(he, NIL);
	  cell hc = make_cell_reference(hr);
	  
	  if((int)gen_length(act1) == 1 && (points_to_cell_in_list_p(nc, act1)|| points_to_cell_in_list_p(hc, act1)))
	    compatible_p = false;
	  break;
	}
	gen_free_list(act1);
	gen_free_list(act2);
      }
    }
    stubs = CDR(stubs);
  }
  gen_full_free_list(tmp);
  free_pt_map(io);
  return compatible_p;

}






/* Translate the out set into the scope of the caller */ 
set compute_points_to_kill_set(list written, set pt_caller, list args, set pt_in, set pt_binded)
{
  set kill = set_generic_make(set_private,
			     points_to_equal_p,points_to_rank);
  list written_cs = NIL, tmp = NIL;
  /* Translate written cells at the level of the call site */
  FOREACH(CELL, c, written) {
    reference r1 = cell_any_reference(c);
    list ind1 = reference_indices(r1);
    reference_indices_(r1) = NIL;
    tmp = caller_addresses(c, args, pt_in, pt_binded);
    FOREACH(CELL, cel, tmp) {
      r1 = cell_any_reference(cel);
      reference_indices_(r1) = gen_nconc(ind1, NIL);
      cel = make_cell_reference(r1);
      written_cs = gen_nconc(CONS(CELL, cel, NIL), written_cs);
    }
  }

  FOREACH(CELL, c, written_cs) {
    SET_FOREACH(points_to, pt, pt_caller) {
      if(points_to_cell_equal_p(c, points_to_source(pt)))
	set_add_element(kill, kill, (void*)pt);
    }
  }
  return kill;
}



set compute_points_to_gen_set(list args, set pt_out, set pt_in, set pt_binded)
{
  set gen = set_generic_make(set_private,
 			     points_to_equal_p,points_to_rank);
  list addr_l1 = NIL;  list addr_l2 = NIL, new_addr_l1 = NIL, new_addr_l2 = NIL ;

  SET_FOREACH(points_to, pt, pt_out) {
    reference r1 = cell_any_reference(points_to_source(pt));
    list ind1 = reference_indices(r1);
    reference r2 = cell_any_reference(points_to_sink(pt));
    entity e1 = reference_variable(r1);
    entity e2 = reference_variable(r2);
    bool stub_p1 = entity_stub_sink_p(e1);
    bool stub_p2 = entity_stub_sink_p(e2);
    if(stub_p1) {
      reference_indices_(r1) = NIL;
      cell e = make_cell_reference(r1);
      addr_l1 = caller_addresses(e, args, pt_in, pt_binded);
      FOREACH(CELL, c, addr_l1) {
	reference nr = cell_any_reference(c);
	reference_indices_(nr) = gen_nconc(ind1, NIL);
	c = make_cell_reference(nr);
	new_addr_l1 = gen_nconc(CONS(CELL, c, NIL), new_addr_l1);	
      }      
    }
    
    if(stub_p2) {
      reference_indices_(r2) = NIL;
      cell e = make_cell_reference(r2);
      addr_l2 = caller_addresses(e, args, pt_in, pt_binded);
      FOREACH(CELL, c, addr_l1) {
	reference nr = cell_any_reference(c);
	reference_indices_(nr) = gen_nconc(ind1, NIL);
	c = make_cell_reference(nr);
	new_addr_l2 = gen_nconc(CONS(CELL, c, NIL), new_addr_l2);	
      }    
    }
    
    if( (!stub_p1 && !stub_p2 ) || 
	(ENDP(new_addr_l1) && ENDP(new_addr_l2)) )
      set_add_element(gen, gen, (void*)pt);
    if(!ENDP(new_addr_l1)) {
      FOREACH(CELL, c_source, addr_l1) {
	if(ENDP(new_addr_l2)) {
	  points_to  new_pt = make_points_to(c_source, points_to_sink(pt), points_to_approximation(pt), make_descriptor_none());
	  set_add_element(gen, gen, (void*)new_pt);
	}
	else {
	  FOREACH(CELL, c_sink, addr_l2) {
	    points_to new_pt = make_points_to(c_source, c_sink, points_to_approximation(pt), make_descriptor_none());
	    set_add_element(gen, gen, (void*)new_pt);
	  }
	}
      }
    }
  }
  return gen;  
}




