/* The table that describes the transform menu: */

{
   PRIVATIZE_TRANSFORM, BUILDER_PRIVATIZE_MODULE 
      },
{
   ARRAY_PRIVATIZE_TRANSFORM, BUILDER_ARRAY_PRIVATIZER 
      },
{
   DISTRIBUTE_TRANSFORM, BUILDER_DISTRIBUTER
      },
{
   PARTIAL_EVAL_TRANSFORM, BUILDER_PARTIAL_EVAL
      },
{
   FULL_UNROLL_TRANSFORM, BUILDER_FULL_UNROLL
      },
{
   UNROLL_TRANSFORM, BUILDER_UNROLL
      },
{
   STRIP_MINE_TRANSFORM, BUILDER_STRIP_MINE
      },
{
   LOOP_INTERCHANGE_TRANSFORM, BUILDER_LOOP_INTERCHANGE
      },
{
   LOOP_NORMALIZE_TRANSFORM, BUILDER_LOOP_NORMALIZE
      },
{
   SUPPRESS_DEAD_CODE_TRANSFORM, BUILDER_SUPPRESS_DEAD_CODE
      },
{
   UNSPAGHETTIFY_TRANSFORM, BUILDER_UNSPAGHETTIFY
      },
{
   ATOMIZER_TRANSFORM, BUILDER_ATOMIZER
      },
{
   NEW_ATOMIZER_TRANSFORM, BUILDER_NEW_ATOMIZER
      },
/* {
   REDUCTIONS_TRANSFORM, BUILDER_REDUCTIONS
      }, */
{
   STF_TRANSFORM, BUILDER_STF
      },
{
   "Use-Def elimination", BUILDER_USE_DEF_ELIMINATION
      },
