#!/bin/sh
# called as psolve 'mypoly' 'symbolic variable name'
# prints out first positive answer
scilab-cli -nb <<EOF
n=poly(0,'$2');
p=$1;
r=roots(p);
for x =r'
	if conj(x)==x & abs(x) == x
		mfprintf(6,"%f\n",x);
		exit(0)
	end
end
exit(1)
EOF
