/* callgraph.h
   include file for callgraphs
 */

#ifndef CALLGRAPH_INCLUDED
#define CALLGRAPH_INCLUDED

#define CALLGRAPH_NOT_FOUND NULL

#define CALLGRAPH_DRAW "CALLGRAPH_DRAW"
#define CALLGRAPH_DEBUG "CALLGRAPH_DEBUG"
#define CALLGRAPH_DEBUG_LEVEL "CALLGRAPH_DEBUG_LEVEL"
#define CALLGRAPH_SHORT_NAMES "CALLGRAPH_SHORT_NAMES"

#define CALLGRAPH_INDENT 4

enum CALLGRAPH_DECOR {
    CG_DECOR_NONE,
    CG_DECOR_PROPER_EFFECTS,
    CG_DECOR_CUMULATED_EFFECTS,
    CG_DECOR_REGIONS,
    CG_DECOR_IN_REGIONS,
    CG_DECOR_OUT_REGIONS,
    CG_DECOR_PRECONDITIONS,
    CG_DECOR_TOTAL_PRECONDITIONS,
    CG_DECOR_TRANSFORMERS,
    CG_DECOR_COMPLEXITIES
};

#endif /* CALLGRAPH_INCLUDED */
