ifeq ($(FWD_TARGET),phase0)
fwd-misc:fwd-properties
fwd-properties:fwd-pipsdbm
fwd-properties:fwd-top-level
fwd-text-util:fwd-properties
fwd-text-util:fwd-ri-util
fwd-pipsdbm:fwd-ri-util
fwd-top-level:fwd-bootstrap
fwd-top-level:fwd-pipsdbm
fwd-top-level:fwd-pipsmake
fwd-top-level:fwd-preprocessor
fwd-top-level:fwd-properties
fwd-top-level:fwd-ri-util
fwd-ri-util:fwd-control
fwd-ri-util:fwd-c_syntax
fwd-ri-util:fwd-pipsdbm
fwd-ri-util:fwd-pipsmake
fwd-ri-util:fwd-preprocessor
fwd-ri-util:fwd-prettyprint
fwd-ri-util:fwd-properties
fwd-ri-util:fwd-syntax
fwd-ri-util:fwd-text-util
fwd-ri-util:fwd-top-level
fwd-conversion:fwd-effects-convex
fwd-conversion:fwd-effects-generic
fwd-conversion:fwd-effects-util
fwd-conversion:fwd-properties
fwd-conversion:fwd-ri-util
fwd-conversion:fwd-text-util
fwd-movements:fwd-ri-util
fwd-movements:fwd-text-util
fwd-comp_sections:fwd-prettyprint
fwd-comp_sections:fwd-text-util
fwd-comp_sections:fwd-top-level
fwd-transformer:fwd-alias-classes
fwd-transformer:fwd-effects-util
fwd-transformer:fwd-preprocessor
fwd-transformer:fwd-properties
fwd-transformer:fwd-ri-util
fwd-bootstrap:fwd-pipsdbm
fwd-bootstrap:fwd-properties
fwd-bootstrap:fwd-ri-util
fwd-control:fwd-pipsdbm
fwd-control:fwd-preprocessor
fwd-control:fwd-properties
fwd-control:fwd-ri-util
fwd-control:fwd-text-util
fwd-flint:fwd-bootstrap
fwd-flint:fwd-effects-util
fwd-flint:fwd-pipsdbm
fwd-flint:fwd-properties
fwd-flint:fwd-ri-util
fwd-syntax:fwd-control
fwd-syntax:fwd-effects-util
fwd-syntax:fwd-pipsdbm
fwd-syntax:fwd-pipsmake
fwd-syntax:fwd-prettyprint
fwd-syntax:fwd-properties
fwd-syntax:fwd-ri-util
fwd-c_syntax:fwd-pipsdbm
fwd-c_syntax:fwd-pipsmake
fwd-c_syntax:fwd-properties
fwd-c_syntax:fwd-ri-util
fwd-c_syntax:fwd-syntax
fwd-c_syntax:fwd-text-util
fwd-prettyprint:fwd-complexity
fwd-prettyprint:fwd-control
fwd-prettyprint:fwd-effects-convex
fwd-prettyprint:fwd-effects-generic
fwd-prettyprint:fwd-effects-simple
fwd-prettyprint:fwd-effects-util
fwd-prettyprint:fwd-pipsdbm
fwd-prettyprint:fwd-properties
fwd-prettyprint:fwd-ri-util
fwd-prettyprint:fwd-semantics
fwd-prettyprint:fwd-syntax
fwd-prettyprint:fwd-text-util
fwd-prettyprint:fwd-top-level
fwd-alias-classes:fwd-bootstrap
fwd-alias-classes:fwd-control
fwd-alias-classes:fwd-effects-convex
fwd-alias-classes:fwd-effects-generic
fwd-alias-classes:fwd-effects-simple
fwd-alias-classes:fwd-effects-util
fwd-alias-classes:fwd-pipsdbm
fwd-alias-classes:fwd-pipsmake
fwd-alias-classes:fwd-preprocessor
fwd-alias-classes:fwd-prettyprint
fwd-alias-classes:fwd-properties
fwd-alias-classes:fwd-ricedg
fwd-alias-classes:fwd-ri-util
fwd-alias-classes:fwd-semantics
fwd-alias-classes:fwd-syntax
fwd-alias-classes:fwd-text-util
fwd-alias-classes:fwd-top-level
fwd-alias-classes:fwd-transformations
fwd-alias-classes:fwd-transformer
fwd-pointer_values:fwd-effects-generic
fwd-pointer_values:fwd-effects-simple
fwd-pointer_values:fwd-effects-util
fwd-pointer_values:fwd-pipsdbm
fwd-pointer_values:fwd-prettyprint
fwd-pointer_values:fwd-ri-util
fwd-pointer_values:fwd-text-util
fwd-effects-generic:fwd-effects-convex
fwd-effects-generic:fwd-effects-util
fwd-effects-generic:fwd-pipsdbm
fwd-effects-generic:fwd-pointer_values
fwd-effects-generic:fwd-preprocessor
fwd-effects-generic:fwd-prettyprint
fwd-effects-generic:fwd-properties
fwd-effects-generic:fwd-ri-util
fwd-effects-generic:fwd-semantics
fwd-effects-generic:fwd-text-util
fwd-effects-generic:fwd-top-level
fwd-effects-generic:fwd-transformer
fwd-effects-simple:fwd-effects-generic
fwd-effects-simple:fwd-effects-util
fwd-effects-simple:fwd-pipsdbm
fwd-effects-simple:fwd-pointer_values
fwd-effects-simple:fwd-properties
fwd-effects-simple:fwd-ri-util
fwd-effects-simple:fwd-text-util
fwd-semantics:fwd-accel-util
fwd-semantics:fwd-alias-classes
fwd-semantics:fwd-control
fwd-semantics:fwd-conversion
fwd-semantics:fwd-c_syntax
fwd-semantics:fwd-effects-convex
fwd-semantics:fwd-effects-generic
fwd-semantics:fwd-effects-simple
fwd-semantics:fwd-effects-util
fwd-semantics:fwd-pipsdbm
fwd-semantics:fwd-preprocessor
fwd-semantics:fwd-prettyprint
fwd-semantics:fwd-properties
fwd-semantics:fwd-ri-util
fwd-semantics:fwd-text-util
fwd-semantics:fwd-top-level
fwd-semantics:fwd-transformations
fwd-semantics:fwd-transformer
fwd-complexity:fwd-effects-generic
fwd-complexity:fwd-effects-simple
fwd-complexity:fwd-effects-util
fwd-complexity:fwd-pipsdbm
fwd-complexity:fwd-preprocessor
fwd-complexity:fwd-prettyprint
fwd-complexity:fwd-properties
fwd-complexity:fwd-ri-util
fwd-complexity:fwd-semantics
fwd-complexity:fwd-text-util
fwd-complexity:fwd-top-level
fwd-complexity:fwd-transformer
fwd-continuation:fwd-effects-generic
fwd-continuation:fwd-effects-util
fwd-continuation:fwd-pipsdbm
fwd-continuation:fwd-prettyprint
fwd-continuation:fwd-properties
fwd-continuation:fwd-ri-util
fwd-continuation:fwd-semantics
fwd-continuation:fwd-text-util
fwd-continuation:fwd-top-level
fwd-continuation:fwd-transformer
fwd-reductions:fwd-callgraph
fwd-reductions:fwd-control
fwd-reductions:fwd-effects-util
fwd-reductions:fwd-expressions
fwd-reductions:fwd-pipsdbm
fwd-reductions:fwd-prettyprint
fwd-reductions:fwd-properties
fwd-reductions:fwd-ricedg
fwd-reductions:fwd-ri-util
fwd-reductions:fwd-semantics
fwd-reductions:fwd-syntax
fwd-reductions:fwd-text-util
fwd-effects-convex:fwd-conversion
fwd-effects-convex:fwd-effects-generic
fwd-effects-convex:fwd-effects-simple
fwd-effects-convex:fwd-effects-util
fwd-effects-convex:fwd-pipsdbm
fwd-effects-convex:fwd-pipsmake
fwd-effects-convex:fwd-pointer_values
fwd-effects-convex:fwd-preprocessor
fwd-effects-convex:fwd-properties
fwd-effects-convex:fwd-ri-util
fwd-effects-convex:fwd-semantics
fwd-effects-convex:fwd-text-util
fwd-effects-convex:fwd-top-level
fwd-effects-convex:fwd-transformer
fwd-effects-util:fwd-preprocessor
fwd-effects-util:fwd-properties
fwd-effects-util:fwd-ri-util
fwd-effects-util:fwd-text-util
fwd-effects-util:fwd-top-level
fwd-callgraph:fwd-complexity
fwd-callgraph:fwd-effects-convex
fwd-callgraph:fwd-effects-generic
fwd-callgraph:fwd-effects-simple
fwd-callgraph:fwd-effects-util
fwd-callgraph:fwd-pipsdbm
fwd-callgraph:fwd-pipsmake
fwd-callgraph:fwd-ri-util
fwd-callgraph:fwd-semantics
fwd-callgraph:fwd-text-util
fwd-icfg:fwd-complexity
fwd-icfg:fwd-control
fwd-icfg:fwd-effects-convex
fwd-icfg:fwd-effects-generic
fwd-icfg:fwd-effects-simple
fwd-icfg:fwd-effects-util
fwd-icfg:fwd-pipsdbm
fwd-icfg:fwd-properties
fwd-icfg:fwd-ri-util
fwd-icfg:fwd-semantics
fwd-icfg:fwd-text-util
fwd-ricedg:fwd-effects-util
fwd-ricedg:fwd-rice
fwd-ricedg:fwd-ri-util
fwd-ricedg:fwd-transformations
fwd-chains:fwd-effects-generic
fwd-chains:fwd-effects-simple
fwd-chains:fwd-effects-util
fwd-chains:fwd-pipsdbm
fwd-chains:fwd-properties
fwd-chains:fwd-ricedg
fwd-chains:fwd-ri-util
fwd-rice:fwd-effects-generic
fwd-rice:fwd-effects-simple
fwd-rice:fwd-transformations
fwd-hyperplane:fwd-control
fwd-hyperplane:fwd-conversion
fwd-hyperplane:fwd-effects-generic
fwd-hyperplane:fwd-effects-simple
fwd-hyperplane:fwd-effects-util
fwd-hyperplane:fwd-pipsdbm
fwd-hyperplane:fwd-properties
fwd-hyperplane:fwd-ri-util
fwd-hyperplane:fwd-transformations
fwd-transformations:fwd-accel-util
fwd-transformations:fwd-alias-classes
fwd-transformations:fwd-callgraph
fwd-transformations:fwd-chains
fwd-transformations:fwd-complexity
fwd-transformations:fwd-control
fwd-transformations:fwd-conversion
fwd-transformations:fwd-effects-convex
fwd-transformations:fwd-effects-generic
fwd-transformations:fwd-effects-simple
fwd-transformations:fwd-effects-util
fwd-transformations:fwd-expressions
fwd-transformations:fwd-instrumentation
fwd-transformations:fwd-pipsdbm
fwd-transformations:fwd-pipsmake
fwd-transformations:fwd-preprocessor
fwd-transformations:fwd-prettyprint
fwd-transformations:fwd-properties
fwd-transformations:fwd-reductions
fwd-transformations:fwd-ricedg
fwd-transformations:fwd-ri-util
fwd-transformations:fwd-semantics
fwd-transformations:fwd-syntax
fwd-transformations:fwd-text-util
fwd-transformations:fwd-top-level
fwd-transformations:fwd-transformer
fwd-accel-util:fwd-alias-classes
fwd-accel-util:fwd-callgraph
fwd-accel-util:fwd-complexity
fwd-accel-util:fwd-control
fwd-accel-util:fwd-conversion
fwd-accel-util:fwd-effects-convex
fwd-accel-util:fwd-effects-generic
fwd-accel-util:fwd-effects-simple
fwd-accel-util:fwd-effects-util
fwd-accel-util:fwd-expressions
fwd-accel-util:fwd-hpfc
fwd-accel-util:fwd-pipsdbm
fwd-accel-util:fwd-pipsmake
fwd-accel-util:fwd-preprocessor
fwd-accel-util:fwd-properties
fwd-accel-util:fwd-ricedg
fwd-accel-util:fwd-ri-util
fwd-accel-util:fwd-semantics
fwd-accel-util:fwd-text-util
fwd-accel-util:fwd-transformations
fwd-accel-util:fwd-transformer
fwd-hwac:fwd-callgraph
fwd-hwac:fwd-control
fwd-hwac:fwd-effects-generic
fwd-hwac:fwd-effects-util
fwd-hwac:fwd-pipsdbm
fwd-hwac:fwd-properties
fwd-hwac:fwd-ri-util
fwd-expressions:fwd-callgraph
fwd-expressions:fwd-control
fwd-expressions:fwd-effects-generic
fwd-expressions:fwd-effects-simple
fwd-expressions:fwd-effects-util
fwd-expressions:fwd-pipsdbm
fwd-expressions:fwd-properties
fwd-expressions:fwd-ricedg
fwd-expressions:fwd-ri-util
fwd-expressions:fwd-semantics
fwd-expressions:fwd-text-util
fwd-expressions:fwd-transformer
fwd-locality:fwd-control
fwd-locality:fwd-conversion
fwd-locality:fwd-hyperplane
fwd-locality:fwd-pipsdbm
fwd-locality:fwd-ri-util
fwd-locality:fwd-transformations
fwd-instrumentation:fwd-alias-classes
fwd-instrumentation:fwd-control
fwd-instrumentation:fwd-conversion
fwd-instrumentation:fwd-effects-convex
fwd-instrumentation:fwd-effects-generic
fwd-instrumentation:fwd-effects-simple
fwd-instrumentation:fwd-effects-util
fwd-instrumentation:fwd-pipsdbm
fwd-instrumentation:fwd-pipsmake
fwd-instrumentation:fwd-properties
fwd-instrumentation:fwd-ri-util
fwd-instrumentation:fwd-semantics
fwd-instrumentation:fwd-text-util
fwd-instrumentation:fwd-top-level
fwd-instrumentation:fwd-transformations
fwd-instrumentation:fwd-transformer
fwd-hpfc:fwd-control
fwd-hpfc:fwd-conversion
fwd-hpfc:fwd-effects-convex
fwd-hpfc:fwd-effects-generic
fwd-hpfc:fwd-effects-simple
fwd-hpfc:fwd-effects-util
fwd-hpfc:fwd-expressions
fwd-hpfc:fwd-pipsdbm
fwd-hpfc:fwd-semantics
fwd-hpfc:fwd-transformations
fwd-atomizer:fwd-control
fwd-atomizer:fwd-effects-generic
fwd-atomizer:fwd-effects-simple
fwd-atomizer:fwd-effects-util
fwd-atomizer:fwd-expressions
fwd-atomizer:fwd-pipsdbm
fwd-atomizer:fwd-ri-util
fwd-atomizer:fwd-text-util
fwd-safescale:fwd-preprocessor
fwd-sac:fwd-accel-util
fwd-sac:fwd-callgraph
fwd-sac:fwd-complexity
fwd-sac:fwd-control
fwd-sac:fwd-effects-convex
fwd-sac:fwd-effects-generic
fwd-sac:fwd-effects-simple
fwd-sac:fwd-effects-util
fwd-sac:fwd-hyperplane
fwd-sac:fwd-pipsdbm
fwd-sac:fwd-preprocessor
fwd-sac:fwd-properties
fwd-sac:fwd-reductions
fwd-sac:fwd-ricedg
fwd-sac:fwd-ri-util
fwd-sac:fwd-text-util
fwd-sac:fwd-transformations
fwd-phrase:fwd-callgraph
fwd-phrase:fwd-control
fwd-phrase:fwd-conversion
fwd-phrase:fwd-effects-convex
fwd-phrase:fwd-effects-generic
fwd-phrase:fwd-effects-simple
fwd-phrase:fwd-effects-util
fwd-phrase:fwd-pipsdbm
fwd-phrase:fwd-pipsmake
fwd-phrase:fwd-preprocessor
fwd-phrase:fwd-prettyprint
fwd-phrase:fwd-properties
fwd-phrase:fwd-ri-util
fwd-phrase:fwd-semantics
fwd-phrase:fwd-text-util
fwd-phrase:fwd-transformer
fwd-wp65:fwd-control
fwd-wp65:fwd-conversion
fwd-wp65:fwd-effects-convex
fwd-wp65:fwd-effects-generic
fwd-wp65:fwd-effects-util
fwd-wp65:fwd-movements
fwd-wp65:fwd-pipsdbm
fwd-wp65:fwd-prettyprint
fwd-wp65:fwd-properties
fwd-wp65:fwd-rice
fwd-wp65:fwd-ricedg
fwd-wp65:fwd-ri-util
fwd-wp65:fwd-text-util
fwd-wp65:fwd-top-level
fwd-preprocessor:fwd-control
fwd-preprocessor:fwd-c_syntax
fwd-preprocessor:fwd-effects-util
fwd-preprocessor:fwd-pipsdbm
fwd-preprocessor:fwd-pipsmake
fwd-preprocessor:fwd-properties
fwd-preprocessor:fwd-ri-util
fwd-preprocessor:fwd-text-util
fwd-pipsmake:fwd-pipsdbm
fwd-pipsmake:fwd-preprocessor
fwd-pipsmake:fwd-properties
fwd-pipsmake:fwd-ri-util
fwd-pipsmake:fwd-top-level
fwd-step:fwd-accel-util
fwd-step:fwd-bootstrap
fwd-step:fwd-control
fwd-step:fwd-c_syntax
fwd-step:fwd-pipsmake
fwd-step:fwd-preprocessor
fwd-step:fwd-ricedg
fwd-step:fwd-semantics
fwd-step:fwd-syntax
fwd-step:fwd-transformer
fwd-to_begin_with:fwd-callgraph
fwd-to_begin_with:fwd-control
fwd-to_begin_with:fwd-pipsdbm
fwd-to_begin_with:fwd-properties
fwd-to_begin_with:fwd-ri-util
fwd-to_begin_with:fwd-syntax
fwd-gpu:fwd-accel-util
fwd-gpu:fwd-callgraph
fwd-gpu:fwd-control
fwd-gpu:fwd-effects-generic
fwd-gpu:fwd-effects-simple
fwd-gpu:fwd-effects-util
fwd-gpu:fwd-pipsdbm
fwd-gpu:fwd-properties
fwd-gpu:fwd-ri-util
fwd-gpu:fwd-text-util
fwd-scalopes:fwd-accel-util
fwd-scalopes:fwd-callgraph
fwd-scalopes:fwd-control
fwd-scalopes:fwd-effects-convex
fwd-scalopes:fwd-effects-generic
fwd-scalopes:fwd-effects-simple
fwd-scalopes:fwd-effects-util
fwd-scalopes:fwd-pipsdbm
fwd-scalopes:fwd-properties
fwd-scalopes:fwd-ri-util
fwd-scalopes:fwd-text-util
fwd-static_controlize:fwd-alias-classes
fwd-static_controlize:fwd-control
fwd-static_controlize:fwd-effects-generic
fwd-static_controlize:fwd-effects-util
fwd-static_controlize:fwd-paf-util
fwd-static_controlize:fwd-pipsdbm
fwd-static_controlize:fwd-prettyprint
fwd-static_controlize:fwd-properties
fwd-static_controlize:fwd-ri-util
fwd-static_controlize:fwd-text-util
fwd-paf-util:fwd-ri-util
fwd-paf-util:fwd-static_controlize
fwd-paf-util:fwd-text-util
fwd-pocc-interface:fwd-control
fwd-pocc-interface:fwd-conversion
fwd-pocc-interface:fwd-effects-generic
fwd-pocc-interface:fwd-effects-simple
fwd-pocc-interface:fwd-effects-util
fwd-pocc-interface:fwd-paf-util
fwd-pocc-interface:fwd-pipsdbm
fwd-pocc-interface:fwd-properties
fwd-pocc-interface:fwd-ri-util
fwd-pocc-interface:fwd-static_controlize
fwd-pocc-interface:fwd-text-util
fwd-pocc-interface:fwd-transformations
fwd-taskify:fwd-accel-util
fwd-taskify:fwd-callgraph
fwd-taskify:fwd-control
fwd-taskify:fwd-effects-convex
fwd-taskify:fwd-effects-generic
fwd-taskify:fwd-effects-simple
fwd-taskify:fwd-effects-util
fwd-taskify:fwd-expressions
fwd-taskify:fwd-gpu
fwd-taskify:fwd-pipsdbm
fwd-taskify:fwd-pipsmake
fwd-taskify:fwd-preprocessor
fwd-taskify:fwd-properties
fwd-taskify:fwd-ri-util
fwd-taskify:fwd-text-util
fwd-rstream_interface:fwd-accel-util
fwd-rstream_interface:fwd-callgraph
fwd-rstream_interface:fwd-control
fwd-rstream_interface:fwd-conversion
fwd-rstream_interface:fwd-effects-generic
fwd-rstream_interface:fwd-effects-simple
fwd-rstream_interface:fwd-effects-util
fwd-rstream_interface:fwd-paf-util
fwd-rstream_interface:fwd-pipsdbm
fwd-rstream_interface:fwd-pocc-interface
fwd-rstream_interface:fwd-preprocessor
fwd-rstream_interface:fwd-properties
fwd-rstream_interface:fwd-ri-util
fwd-rstream_interface:fwd-static_controlize
fwd-rstream_interface:fwd-text-util
fwd-rstream_interface:fwd-transformations
fwd-regions_to_loops:fwd-accel-util
fwd-regions_to_loops:fwd-callgraph
fwd-regions_to_loops:fwd-control
fwd-regions_to_loops:fwd-conversion
fwd-regions_to_loops:fwd-c_syntax
fwd-regions_to_loops:fwd-effects-convex
fwd-regions_to_loops:fwd-effects-generic
fwd-regions_to_loops:fwd-effects-simple
fwd-regions_to_loops:fwd-effects-util
fwd-regions_to_loops:fwd-paf-util
fwd-regions_to_loops:fwd-phrase
fwd-regions_to_loops:fwd-pipsdbm
fwd-regions_to_loops:fwd-pocc-interface
fwd-regions_to_loops:fwd-preprocessor
fwd-regions_to_loops:fwd-properties
fwd-regions_to_loops:fwd-ri-util
fwd-regions_to_loops:fwd-semantics
fwd-regions_to_loops:fwd-static_controlize
fwd-regions_to_loops:fwd-syntax
fwd-regions_to_loops:fwd-text-util
fwd-regions_to_loops:fwd-transformations
fwd-task_parallelization:fwd-accel-util
fwd-task_parallelization:fwd-bootstrap
fwd-task_parallelization:fwd-chains
fwd-task_parallelization:fwd-complexity
fwd-task_parallelization:fwd-control
fwd-task_parallelization:fwd-conversion
fwd-task_parallelization:fwd-c_syntax
fwd-task_parallelization:fwd-effects-convex
fwd-task_parallelization:fwd-effects-generic
fwd-task_parallelization:fwd-effects-simple
fwd-task_parallelization:fwd-effects-util
fwd-task_parallelization:fwd-pipsdbm
fwd-task_parallelization:fwd-properties
fwd-task_parallelization:fwd-regions_to_loops
fwd-task_parallelization:fwd-ricedg
fwd-task_parallelization:fwd-ri-util
fwd-task_parallelization:fwd-semantics
fwd-task_parallelization:fwd-syntax
fwd-task_parallelization:fwd-text-util
fwd-task_parallelization:fwd-transformations
endif
