#! /bin/sh
#
# $Id$
#
# create couples (function library) of uses and definitions for all libraries
# used in PIPS (default option -a), including Linear and NewGen, or for
# all PIPS libraries (option -p)

# Remi Triolet, Francois Irigoin, Corinne Ancourt, Fabien Coelho

USAGE="Usage: $0 [-p|a]"
tmpdir=${PIPS_TEMPDIR:-/tmp}

LIBS="$PIPS_ROOT/Lib/$PIPS_ARCH/*.a $NEWGEN_ROOT/Lib/$PIPS_ARCH/*.a $LINEAR_ROOT/Lib/$PIPS_ARCH/*.a"

while getopts ap opt
do
  case $opt in
    p)	LIBS="$PIPS_ROOT/Lib/$PIPS_ARCH/*.a";;
    a) ;;
    \?)	echo $USAGE >&2
	exit 2;;
  esac
done

nm -go $LIBS | fgrep " T " | sed 's/:.* / /;s/^\/.*\///' | 
	awk '{ print $2 , $1}' | sort > $tmpdir/libs.d

nm -go $LIBS | fgrep " U " | sed 's/:.* / /;s/^\/.*\///' | 
	awk '{ print $2 , $1}' | sort > $tmpdir/libs.u

join $tmpdir/libs.u $tmpdir/libs.d > $tmpdir/libs.j

# that is all
#
