#! /bin/sh
#
# $Id$
#
# build a .so file for the specified .a files.
# quite experimental at the time. 
#

script=`basename $0`
verb=echo

################################################################# UTILS

verbose()
{
  $verb "[$script] " "$@"
}

usage()
{
  cat  <<-EOF
	${script} libraries...
EOF
}

############################################################## DO THE JOB

# convert a .a to a .so
convert()
{
   name=`dirname ${1}`/`basename ${1} .a`

   rm -f ${name}.so
   ofiles=`ar t ${name}.a`
   ar xv ${name}.a
   gcc -g -shared -o ${name}.so ${ofiles}
   rm -f ${ofiles}
}


for l ; do
  verbose converting $l
  convert $l
done

