#!/bin/sh
# 
# $RCSfile: checked-out,v $ (version $Revision$)
# $Date: 1997/01/01 22:55:46 $, 

USERNAME=$1
# echo $USERNAME

PIPS_DOCDIR=$PIPS_DEVEDIR/Documentation

if [ -z "$USERNAME" ]
then
	find $PIPS_DOCDIR -name 'p.*' -ls 
	find $PIPS_DEVEDIR -name 'p.*' -ls 
	find $LINEAR_DIR/Development -name 'p.*' -ls
	find $NEWGEN_DIR -name 'p.*' -ls 
else
	find $PIPS_DOCDIR -name 'p.*' -ls | grep "$USERNAME"
	find $PIPS_DEVEDIR -name 'p.*' -ls | grep "$USERNAME"
	find $LINEAR_DIR/Development -name 'p.*' -ls | grep "$USERNAME"
	find $NEWGEN_DIR -name 'p.*' -ls | grep "$USERNAME"
fi
