#! /bin/sh

# Shell script to clean Pips, Linear and Newgen. Uses "make clean" or 
# "make clobber".
# In development phase, should NOT be used with -d nor -a
# sa. $UTILDIR/search
#
# Bruno BARON, 21.10.91

# Options are available:
#  -n: do nothing but show what would be done
#
#  -P: take care of Pips (default)
#  -L: take care of Linear (default)
#  -N: take care of NewGen
# suboptions of -P and -L:
#  -p: take care of Production (default)
#  -d: take care of Development
#  -a: do everything (Production + Development)
# suboptions of -L
#  -c: clobber (stronger than clean)

USAGE="Usage: $0 [-PLN] [-p|d|a] [-n] [-c] (default is -PL -p)"

MAKE_OPTION=""
DEVELOPMENT=""
PRODUCTION=""
PIPS=""
LINEAR=""
NEWGEN=""
CLEAN="clean"

while getopts ndpaPLNc opt
do
	case $opt in
	n)	MAKE_OPTION="-n";;
	d)	DEVELOPMENT=TRUE;;
	p)	PRODUCTION=TRUE;;
	a)	DEVELOPMENT=TRUE
		PRODUCTION=TRUE;;
	P)	PIPS=TRUE;;
	L)	LINEAR=TRUE;;
	N)	NEWGEN=TRUE;;
	c)	CLEAN="clobber";;
	\?)	echo $USAGE >&2
		exit 2;;
	esac
done
shift `expr $OPTIND - 1`
if [ $# -ge 1 ]
then
	echo $USAGE >&2
	exit 2
fi

# set up defaults
if [ -z "${PIPS}${LINEAR}${NEWGEN}" ]
then
PIPS=TRUE
LINEAR=TRUE
fi

if [ -z "${PRODUCTION}${DEVELOPMENT}" ]
then
PRODUCTION=TRUE
fi

if [ -n "$PIPS" ]
then
	# get rid of object files and libraries in Production
	if [ -n "$PRODUCTION" ]
	then

	cd $PRODDIR/Src/Lib
	echo; pwd
	for FILE in *
	do
		echo " " cleaning $FILE
		(cd $FILE; make $MAKE_OPTION clean)
	done

	# get rid of object files and executables
	cd $PRODDIR/Src/Passes
	echo; pwd
	for FILE in *
	do
		echo " " cleaning $FILE
		(cd $FILE; make $MAKE_OPTION clean)
	done

	# get rid of useless binaries
	cd $PRODDIR/Bin
	echo; pwd
	for FILE in *
	do
		case $FILE in
		pips)	echo preserving pips;;
		wpips)	echo preserving wpips;;
		\?)	if [ -n $MAKE_OPTION]
			then
				echo would remove $FILE
			else
				echo removing $FILE
				rm -f $FILE
			fi;;
		esac
	done

	fi

	# get rid of object files and libraries in Development
	if [ -n "$DEVELOPMENT" ]
	then
	cd $DEVEDIR/Lib
	echo; pwd
	for FILE in *
	do
		echo " " cleaning $FILE
		(cd $FILE; make $MAKE_OPTION clean)
		(cd $FILE; if [-n $MAKE_OPTION]
			   then
				echo Delete *.database
			   else
				Delete *.database
			   fi)
	done

	# get rid of object files and executables
	cd $DEVEDIR/Passes
	echo; pwd
	for FILE in *
	do
		echo " " cleaning $FILE
		(cd $FILE; make $MAKE_OPTION clean)
		(cd $FILE; if [-n $MAKE_OPTION]
			   then
				echo Delete *.database
			   else
				Delete *.database
			   fi)
	done
	fi
fi

# get rid of object files for LINEAR libraries
if [ -n "$LINEAR" ]
then
	if [ -n "$PRODUCTION" ]
	then
	cd $LINEARDIR/Production
	echo; pwd
	make $MAKE_OPTION $CLEAN
	fi

	if [ -n "$DEVELOPMENT" ]
	then
	cd $LINEARDIR/Production
	echo; pwd
	make $MAKE_OPTION $CLEAN
	fi
fi

# clean NewGen
if [ -n "$NEWGEN" ]
then
	cd $NEWGENDIR
	echo; pwd
	make $MAKE_OPTION clean
fi
