#!/bin/sh
#
# SCCS STuff
# $RCSfile: make-tags,v $ ($Date: 1994/12/09 11:35:48 $) version $Revision$, got on %D%, %T%
# %A%
#
# Tags computation for the PIPS project, using the Development version.
# To be run by cron for user pips on isatis

# Remi Triolet

# Modifications:
#  - add tags for Linear
#  - add recomputation of TAGS for Linear
#  - PIPS_ETAGS variable used
#  - awk -> cut
#  - NEWGENDIR used
#  - find removed, to disallow the recursive enumeration of files
#    (I haven't found a way to do it thru -prune) FC 10/03/94

HOME=`ypcat passwd | egrep '^pips:' | cut -d: -f 6`

# . /etc/profile
. ${HOME}/.profile

TAGS=/tmp/PIPS-TAGS
FILES=/tmp/PIPS-FILES

#
# only directories in this variable
#

PATHNAME_LIST="${DEVEDIR}/Lib/[a-z]* ${DEVEDIR}/Passes/[a-z]* ${INCLUDEDIR} ${EXTEDIR} ${NEWGENDIR}/C"

rm -f $FILES $TAGS

# mere files
# none

# directories

for dir in $PATHNAME_LIST
do
  test -d $dir && ls $dir/*.[chly] >> $FILES
done

# tags generation

${PIPS_ETAGS} -f ${TAGS} `sed '/,/d' ${FILES}` 2>/dev/null

cp ${TAGS} ${PIPSDIR}/Tags/TAGS

rm -f ${TAGS} ${FILES}
(cd $LINEARDIR/Development; rm -f TAGS; make TAGS)
cat ${HOME}/C3/Linear/Development/TAGS >>${PIPSDIR}/Tags/TAGS

#
# that's all
#
