# $Id$

INSTALL_UTL =	analyze_libraries \
		grep_libraries \
		order_libraries \
		order_libraries_from_include \
		pips_at_night \
		pips_at_night_at_cri \
		pips_at_night_at_HPCAS \
		pips_publish_www \
		pips_svn_stat \
		build_so_files \
		pips_branch

# common stuff
ifdef PIPS_ROOT
ROOT    = $(PIPS_ROOT)
else
ROOT    = ../../..
endif

#PROJECT = pips
include $(ROOT)/makes/main.mk
