#
# $Id$
#
# $Log: makefile_macros.GNU,v $
# Revision 1.35  1997/11/13 12:55:55  keryell
# Added include $(ROOT)/Include/makefile_macros.DEFAULT
#
# Revision 1.34  1997/09/09 13:00:47  coelho
# hop!
#
# Revision 1.33  1997/09/09 12:05:48  coelho
# much factored out.
#
# Revision 1.32  1997/07/26 12:16:43  coelho
# SOURCE macros added...
#
# Revision 1.30  1997/05/14 08:33:54  coelho
# use bsd files...
#
# Revision 1.29  1997/04/15 12:10:22  coelho
# -pedantic-errors...
#
# Revision 1.28  1997/03/26 17:25:59  coelho
# simply GNU softwares.
#
#
# this file contains macro definitions 

include $(ROOT)/Include/makefile_macros.DEFAULT
include $(ROOT)/Include/makefile_macros.gnu
include $(ROOT)/Include/makefile_macros.gnutools

# end of it!
#
