#! /bin/sh
# for debug, try: /bin/sh -vx
#
# $RCSfile: pips-makemake,v $ ($Date: 1996/08/20 17:27:42 $, )
# version $Revision$
#
# Automatic generation of Makefile for the PIPS project
#
# Remi Triolet, Bruno Baron
# Fabien Coelho, 08/95
#

SCRIPT=`basename $0`
USAGE="$SCRIPT [-h (HELP!)] [-l|p|i|n|d] [-D|P]"
verbose=':'

MAKEFILE=Makefile
CONFIG_FILE=config.makefile

PIPSMKMK_OPTION=''

help()
{
  cat <<-END_OF_HELP
	$USAGE
	version $Revision$
	Builds $MAKEFILE from $CONFIG_FILE for PIPS.
	  -l|p|i|n|d: libraries|passes|linear|newgen|default
	  -D|P: for Development|Production directories
	  -h: this help
	  -v: verbose
	  contextual defaults for first and second options.
	Usefull macros in $CONFIG_FILE: 
	 - libraries/passes/linear: LIB_{CFILES,HEADERS,OBJECTS}
	   and maybe DERIVED_{HEADERS,CFILES,FILES}
	 - default:
 	   SOURCES
	   SCRIPTS (runable files)
	   INSTALL_{INC,LIB,BIN,DOC,HTM,SHR,UTL} files to be installed
	Many default macros are defined and may be overwritten.
	Many rules are also defined.
	END_OF_HELP
}

verb()
{ echo "$SCRIPT" "$@";}

usage()
{
  echo "usage: $USAGE" >&2
  [ "$2" ] && echo "error: $2" >&2
  exit ${1:-1}
}

warning()
{ echo "$SCRIPT: warning, $@" >&2 ;}

#
# what is to be done...

DIRSIDE=''
DIRTYPE=''
ALL=''
ALL_RULE_TARGET=''

while getopts lpindDPhv opt
do
  case $opt in
    l) DIRTYPE='Lib';
       PIPSMKMK_OPTION="$PIPSMKMK_OPTION -l" ;;
    p) DIRTYPE='Passes';
       PIPSMKMK_OPTION="$PIPSMKMK_OPTION -p" ;;
    i) DIRTYPE='Linear';
       PIPSMKMK_OPTION="$PIPSMKMK_OPTION -i" ;;
    n) DIRTYPE='Newgen';
       PIPSMKMK_OPTION="$PIPSMKMK_OPTION -n" ;;
    d) DIRTYPE='Default';
       PIPSMKMK_OPTION="$PIPSMKMK_OPTION -d" ;;
    D) DIRSIDE="$PIPS_DEVEDIR" ;
       unset production ;
       PIPSMKMK_OPTION="$PIPSMKMK_OPTION -D" ;;
    P) DIRSIDE="$PIPS_SRCDIR"; 
       production='yes' ;
       PIPSMKMK_OPTION="$PIPSMKMK_OPTION -P" ;;
    h) help ; exit 0 ;;
    v) verbose=verb ;;
    *) usage 2 "invalid option ($opt)" ;;
  esac
done
shift `expr $OPTIND - 1`

[ $# -eq 0 ] || usage 3 "$# remaining parameters"

current_directory=`pwd`
cd_dirname=`dirname $current_directory`

# set defaults if necessary

[ "${Parts}" ] ||
{
    PART=PIPS
    [ "`echo $current_directory | grep Linear`" ] && PART=LINEAR 
    [ "`echo $current_directory | grep Newgen`" ] && PART=NEWGEN
    $verbose "default PART computed: $PART"
}

[ "${DIRTYPE}" ] || 
{
    DIRTYPE=Default
    for f in Linear Newgen Lib Passes ; do
	[ "`echo $current_directory | grep $f`" ] && DIRTYPE=$f
    done
    $verbose "defaults DIRTYPE computed: $DIRTYPE"
}

[ "${DIRSIDE}" ] || 
{
  if [ "`echo $current_directory | grep Development`" ]
  then
    DIRSIDE=$PIPS_DEVEDIR ;
  else
    production='yes' ;
    DIRSIDE=$PIPS_ROOT/Src ;
  fi
  $verbose "default DIRSIDE computed: $DIRSIDE"
}

$verbose "defining vars..."

PART=PIPS

install_inc_dir='$(PIPS_ROOT)/Include'
install_lib_dir='$(PIPS_ROOT)/Lib'
install_bin_dir='$(PIPS_ROOT)/Bin'
install_src_dir='$(PIPS_ROOT)/Src'
install_shr_dir='$(PIPS_ROOT)/Share'
install_doc_dir='$(PIPS_ROOT)/Doc'
install_htm_dir='$(PIPS_ROOT)/Doc/Html'
install_rtm_dir='$(PIPS_ROOT)/Runtime' ;

install_utl_dir='$(PIPS_UTILDIR)'

# [ $DIRTYPE = 'Src' ] && DIRTYPE='Newgen'

case $DIRTYPE in
  Lib) ALL_RULE_TARGET='$(ARCH)/lib$(TARGET).a' ;;
  Passes)  ALL_RULE_TARGET='$(ARCH)/$(TARGET)' ;;
  Scripts) ALL_RULE_TARGET='.runable' ;;
  Runtime) ALL_RULE_TARGET='' ;;
  Linear)  ALL_RULE_TARGET='$(ARCH)/lib$(TARGET).a' ;
           PART=LINEAR ;
	   install_src_dir='$(LINEAR_ROOT)/Src';
           install_inc_dir='$(LINEAR_ROOT)/Include' ;
           install_bin_dir='$(LINEAR_ROOT)/Bin' ;
           install_lib_dir='$(LINEAR_ROOT)/Lib' ;
	   install_doc_dir='$(LINEAR_ROOT)/Doc' ;
	   # install_htm_dir='$(LINEAR_ROOT)/Doc/Html' ;
	   install_utl_dir='$(LINEAR_ROOT)/Share' ;
	   install_shr_dir='$(LINEAR_ROOT)/Share';
	   install_rtm_dir='$(LINEAR_ROOT)/Runtime' ;;
  Newgen)  ALL_RULE_TARGET='' ;
	   PART=NEWGEN ;
	   install_src_dir='$(NEWGEN_ROOT)/Src';
           install_inc_dir='$(NEWGEN_ROOT)/Include' ;
           install_bin_dir='$(NEWGEN_ROOT)/Bin' ;
	   install_doc_dir='$(NEWGEN_ROOT)/Doc' ;
	   # install_htm_dir='$(NEWGEN_ROOT)/Doc/Html' ;
	   install_utl_dir='$(NEWGEN_ROOT)/Share' ;
           install_lib_dir='$(NEWGEN_ROOT)/Lib' ;
	   install_shr_dir='$(NEWGEN_ROOT)/Share' ;
	   install_rtm_dir='$(NEWGEN_ROOT)/Runtime' ;;
  Default) ALL_RULE_TARGET='';;
  *) usage 5 "unexpected directory type $DIRTYPE"
esac

$verbose "PART: ${PART}"
$verbose "DIRSIDE: $DIRSIDE"
$verbose "DIRTYPE: $DIRTYPE"
$verbose "pwd: $current_directory"

[ -f $CONFIG_FILE ] || usage 6 "no $CONFIG_FILE in $current_directory" ;

# needed because of f.. - in directory names...
dir_real_name=`basename $current_directory`
dir_simple_name=`echo $dir_real_name | tr '-' '_'`

# type sed
target_dir=`echo "$current_directory" | 
    sed 's,.*/Development/,,;s,.*/Production/Src/,,;'`

echo "Making $DIRTYPE $PART $MAKEFILE in $dir_real_name ($DIRSIDE $target_dir)"

rm -f $MAKEFILE

##############################################################################

$verbose "common part"

cat >> $MAKEFILE <<%
#	---------------------------------------------------------------
#	---------------------------------------------------------------
#
#				    WARNING
#
#		  This makefile has been automatically generated
#
#                        ($RCSfile: pips-makemake,v $ version $Revision$)
#
#			       Do not modify it
#
#        You can modify the file $CONFIG_FILE in the same directory
#
#	---------------------------------------------------------------
#	---------------------------------------------------------------
#
# Copyright (C) Ecole des Mines De Paris
#               Centre d'Automatique et Informatique
#               Section Informatique
#
# This file is part of PIPS
#
# PIPS is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY.  No author or distributor accepts responsibility to anyone for
# the consequences of using it or for whether it serves any particular
# purpose or works at all, unless he says so in writing.
#
# DEFAULTS, may be overwritten by the $CONFIG_FILE content.
#
TARGET=		${dir_real_name}
TARGET_DIR=	${install_src_dir}/${target_dir}
#
# default architecture is taken from PIPS_ARCH env. variable
ARCH=		$(PIPS_ARCH)
#
# installation directories for quick-install
#
INSTALL_INC_DIR= ${install_inc_dir}
INSTALL_SHR_DIR= ${install_shr_dir}
INSTALL_DOC_DIR= ${install_doc_dir}
INSTALL_HTM_DIR= ${install_htm_dir}
INSTALL_UTL_DIR= ${install_utl_dir}
INSTALL_RTM_DIR= ${install_rtm_dir}
INSTALL_LIB_DIR= ${install_lib_dir}/$(ARCH)
INSTALL_BIN_DIR= ${install_bin_dir}/$(ARCH)
# (obsolete?)
MAIN=		main
#
# 
#
CONFIG_FILE=	${CONFIG_FILE}
MAKEFILE=	${MAKEFILE}
SHELL	=	/bin/sh
COPY	=	cp
MOVE	=	mv -f
GMKNODIR=	--no-print-directory
#
# default targets...
all: generate_makefile_if_necessary_and_possible
all: $(ARCH) $ALL_RULE_TARGET
#
recompile: depend header all
recompile: generate_makefile_if_necessary_and_possible
#
full-clean: clean clean-all-compiled
clean-all-compiled: 
	-for d in \`echo $(PIPS_ROOT)/Include/makefile_macros.* | \\
		sed 's,[-_a-zA-z0-9/]*/makefile_macros\.,,g'\`; do \\
	  test -d \$\$d && { \\
	    echo "cleaning \$\$d"; \\
	    $(RM) \$\$d/*.[oa] \$\$d/*pips Makefile.depend.\$\$d; \\
	    test "\`ls -A \$\$d\`" || rmdir \$\$d; } ; \\
	done
#
OLD:; mkdir OLD
SCCS:; mkdir SCCS
get:; sccs get SCCS
# .PHONY is a gnu extension...
.PHONY: install all depend header recompile clobber count info delta
.PHONY: generate_makefile_if_necessary_and_possible
# to override SUN/GNU default rule
.SCCS_GET:
# %:SCCS/s.%:
.SUFFIXED: .tex .dvi .ps .c .h .o .w .a .html
# .INIT is a SUN extension...
.INIT: 
check_install:
# is this appropriate?
# .DEFAULT:; @echo "$MAKEFILE [$(FWD_ROOT)] *** no rule for target $@!" >&2
#
$(ARCH):; mkdir $(ARCH)
#
include $(${PART}_ROOT)/Include/define_libraries
include $(${PART}_ROOT)/Include/makefile_macros.$(ARCH)
include $CONFIG_FILE
#
# prefixed objects:
LIB_OBJECTS:=$(addprefix $(ARCH)/, $(LIB_OBJECTS))
#
# {C,CPP,LD,L,Y}OPT macros allow to *add* things from the command line
# as gmake CPPOPT="-DFOO=bar" ... that will be added to the defaults
# a typical interesting example is to put -pg in {C,LD}OPT
#
PREPROC=	$(CC) -E $(CPPFLAGS) $(CPPOPT) $(TARGET_ARCH)
COMPILE=	$(CC) $(CFLAGS) $(COPT) $(CPPFLAGS) $(CPPOPT) $(TARGET_ARCH) -c
LINK=		$(LD) $(LDFLAGS) $(LDOPT) -o
SCAN=		$(LEX) $(LFLAGS) $(LOPT) -t
TYPECHECK=      $(LINT) $(LINTFLAGS) $(CPPFLAGS) $(TARGET_ARCH) $(LINT_LIBS)
PARSE=		$(YACC) $(YFLAGS) $(YOPT)
ARCHIVE=	$(AR) $(ARFLAGS)
# struct _iobuf -> FILE for sun headers that would not look nice.
PROTOIZE=	$(PROTO) $(PRFLAGS) -E "$(PREPROC)"
#
# Default rules
#
$(ARCH)/%.o:	%.c 
	$(COMPILE) \$< -o \$@
#
# if LATEX, MAKEIDX, LX2HTML or DVIPS are not avaible, 
# the following rules would not prevent compilation...
%.dvi: %.tex
	touch \$*.ind
	$(LATEX) \$<
	test -f \$*.idx && { $(MAKEIDX) \$*.idx ; $(LATEX) \$< ; }
	$(LATEX) \$<
	touch \$@
#
%.ps: %.dvi
	$(DVIPS) -o \$@ \$<
	touch \$@
#
%.html: %.tex
	$(RM) -r \$* \$@
	mkdir \$*
	$(LX2HTML) \$<
	chmod -R a+r-wx \$*/*
	chmod a+rx-w \$*
	ln -s \$*/\$@ \$@
# MISC
.runable: $(SCRIPTS)
	-[ "$(SCRIPTS)" ] && chmod a+rx $(SCRIPTS)
	touch .runable
quick-install: .runable
#
%



##############################################################################

[ $DIRTYPE = 'Lib' -o $DIRTYPE = 'Passes' -o $DIRTYPE = 'Linear' ] && 
cat >> $MAKEFILE <<% 
#
LIB_TARGET=	$(ARCH)/lib$(TARGET).a
BIN_TARGET=	$(ARCH)/$(TARGET)
INC_TARGET=	$(TARGET).h
#
INSTALL_INC+=	$(INC_TARGET)
INSTALL_LIB+=	$(LIB_TARGET)
INSTALL_BIN+=	`if [ $DIRTYPE = 'Passes' ] ; then echo '$(BIN_TARGET)' ; fi`
#

.PRECIOUS: $(LIB_TARGET) $(BIN_TARGET)

# .INIT is a SUN extention...
# .INIT: check_os

check_install:
	@if test \`echo *.a | wc -w\` -gt 1 ; \\
	then \\
	  echo "install failed: additional local libraries prevent it" >&2;\\
	  exit 1;\\
	fi

$(LIB_TARGET): $(INC_TARGET) $(DERIVED_CFILES) $(DERIVED_HEADERS)

$(LIB_TARGET): $(LIB_OBJECTS) $(TARGET_OBJECTS)
	$(RM) $(LIB_TARGET)
	$(ARCHIVE) $(LIB_TARGET) $(LIB_OBJECTS) $(TARGET_OBJECTS)
	-$(RANLIB) $(LIB_TARGET)

%


##############################################################################

[ $DIRTYPE = 'Linear' ] && cat >> $MAKEFILE <<% 

CFILES=		$(LIB_CFILES)
OBJECTS=	$(LIB_OBJECTS)
INCLUDES=	$(LIB_HEADERS)
SOURCES+= 	$(INCLUDES) $(CFILES) $(DOCS)
#

%


##############################################################################

[ $DIRTYPE = 'Lib' ] && cat >> $MAKEFILE <<% 
#
CFILES=		$(MAIN).c $(LIB_CFILES)
OBJECTS=	$(MAIN).o $(LIB_OBJECTS)
INCLUDES=	$(LIB_HEADERS)
SOURCES+= 	$(INCLUDES) $(CFILES) $(DOCS)
#

test: all
	$(LINK) $(ARCH)/pips -lpips $(PIPS_LIBS) 
	@echo 

wtest: all
	$(LINK) $(ARCH)/wpips $(WPIPS_ADDED_LDFLAGS) -lwpips \\
		$(PIPS_LIBS) $(WPIPS_ADDED_LIBS)
	@echo 

ttest: all
	$(LINK) $(ARCH)/tpips -ltpips \\
		$(PIPS_LIBS) $(TPIPS_ADDED_LIBS)
	@echo 

# obsolete rule I guess. test is better. FC.
$(BIN_TARGET): $(LIB_TARGET) $(ARCH)/$(MAIN).o
	$(LINK) $(BIN_TARGET) $(ARCH)/$(MAIN).o \\
		$(LIB_TARGET) $(PIPS_LIBS)
	@echo 

clobber: clean
	-Delete *.database

%

#############################################################################

[ $DIRTYPE = 'Lib' -o $DIRTYPE = 'Linear' ] && cat >> $MAKEFILE <<% 
#

clean-compiled:
	$(RM) $(OBJECTS) $(LIB_TARGET) $(BIN_TARGET) \\
		$(ARCH)/pips $(ARCH)/[tw]pips

clean: generate_makefile_if_necessary_and_possible clean-compiled
	-$(RM) TAGS $(BIN_TARGET) $(DERIVED_HEADERS) $(DERIVED_CFILES) \\
		$(DERIVED_FILES) *.~[0-9]~ $(LIB_IFILES) $(INC_TARGET) core

INC_CFILES += $(LIB_CFILES)

%




##############################################################################

[ $DIRTYPE = 'Passes' ] && cat >> $MAKEFILE <<% 
#
# a little bit rough...
#
$(ARCH)/$(TARGET): $(ARCH)/lib$(TARGET).a \\
	$(PIPS_ROOT)/Lib/$(ARCH)/*.a \\
	$(LINEAR_ROOT)/Lib/$(ARCH)/*.a \\
	$(NEWGEN_ROOT)/Lib/$(ARCH)/*.a
#
CFILES=		$(LIB_CFILES)
OBJECTS=	$(LIB_OBJECTS)
INCLUDES=	$(LIB_HEADERS)
SOURCES+= 	$(INCLUDES) $(CFILES) $(DOCS)
#

$(PIPS_BINDIR):
	mkdir $(PIPS_BINDIR)

$(BIN_TARGET): $(INC_TARGET) $(LIB_TARGET)
	$(LINK) $(BIN_TARGET) $(LIB_TARGET) $(TARGET_LIBS)
	@echo 

clean-compiled:
	$(RM) $(OBJECTS) $(LIB_TARGET) $(BIN_TARGET) 

clean: clean-compiled
	-$(RM) TAGS $(INC_TARGET) $(DERIVED_HEADERS) $(DERIVED_CFILES) \\
		$(DERIVED_FILES) *.~[0-9]~ core

INC_CFILES += $(LIB_CFILES)

%


##############################################################################

[ $DIRTYPE = 'Default' ] && cat >> $MAKEFILE <<% 

clean:
	$(RM) core *~

%



##############################################################################

[ \( $DIRTYPE = 'Passes' -o $DIRTYPE = 'Lib' -o $DIRTYPE = 'Linear' \) -a "$production" ] &&
cat >> $MAKEFILE <<%

.PRECIOUS: $(${PART}_LIBDIR)/$(LIB_TARGET) $(${PART}_BINDIR)/$(BIN_TARGET)

$(${PART}_INCLUDEDIR)/$(TARGET).h: header
	@pips_install_file -f $(${PART}_INCLUDEDIR) $(TARGET).h

$(${PART}_LIBDIR)/$(LIB_TARGET): $(LIB_TARGET) 
	@pips_install_file -r $(RANLIB) $(${PART}_LIBDIR)/$(ARCH) $(LIB_TARGET)

$(LIB_OBJECTS): $(TARGET).h

recompile: $(${PART}_INCLUDEDIR)/$(TARGET).h $(${PART}_LIBDIR)/$(LIB_TARGET) 

%



##############################################################################

[ $DIRTYPE = 'Passes' -a $DIRSIDE = $PIPS_SRCDIR ] &&
cat >> $MAKEFILE <<%

$(TARGET_OBJECTS): $(TARGET).h

$(PIPS_BINDIR)/$(ARCH):
	mkdir \$@

$(PIPS_BINDIR)/$(BIN_TARGET): $(BIN_TARGET) $(PIPS_BINDIR)/$(ARCH)
	@pips_install_file -x $(PIPS_BINDIR)/$(ARCH) $(BIN_TARGET)

recompile: $(PIPS_BINDIR)/$(BIN_TARGET)

%



##############################################################################
#
# Common to all: installation and Makefile generation
#

cat >> $MAKEFILE <<%

ALL_SOURCES =	$(SOURCES) $(CONFIG_FILE)

$(TARGET_DIR):
	mkdir $(TARGET_DIR)

check_os:
	@if test -n "$(PIPS_CHECK_OS)"; \\
	then echo "Cannot run make under this OS release"; \\
	     echo "$(PIPS_CHECK_OS)"; exit 1; \\
	fi

.quick-install: $(INSTALL_INC) $(INSTALL_LIB) $(INSTALL_BIN) $(INSTALL_SHR) \
	$(INSTALL_DOC) $(INSTALL_UTL) $(INSTALL_RTM) $(INSTALL_HTM) 
	#
	# installing files where needed
	# 
	# plain files
	@pips_install_file -f $(INSTALL_INC_DIR) $(INSTALL_INC) 
	@pips_install_file -f $(INSTALL_DOC_DIR) $(INSTALL_DOC) 
	@pips_install_file -f $(INSTALL_HTM_DIR) $(INSTALL_HTM) 
	@pips_install_file -f $(INSTALL_UTL_DIR) $(INSTALL_UTL) 
	@pips_install_file -f $(INSTALL_SHR_DIR) $(INSTALL_SHR)
	@pips_install_file -f $(INSTALL_RTM_DIR) $(INSTALL_RTM)
	# libs...
	@pips_install_file -r $(RANLIB) $(INSTALL_LIB_DIR) $(INSTALL_LIB)
	# executables...
	@pips_install_file -x $(INSTALL_BIN_DIR) $(INSTALL_BIN)
	touch .quick-install

tar:
	$(TAR) cf $(TARGET).tar $(ALL_SOURCES) Makefile
	$(ZIP) $(TARGET).tar

quick-install: .quick-install

.makefile: $(PIPS_UTILDIR)/pips-makemake
	# 
	# regenerating Makefile
	#
	$(PIPS_UTILDIR)/pips-makemake ${PIPSMKMK_OPTION}
	touch .makefile

generate_makefile_if_necessary_and_possible:
	-@[ -x $(PIPS_UTILDIR)/pips-makemake ] && \\
		$(MAKE) $(GMKNODIR)  .makefile 

count:
	@wc -l $(ALL_SOURCES)

#
# some quick entries for SCCS:
info:
	@sccs info

# try to delta all checked out files
delta:
	@test ! "\`sccs tell\`" || sccs delget \`sccs tell\`

%



##############################################################################
#

[ "$production" ] && cat >> $MAKEFILE <<EOF
#
# print out the files for a release...
FWD_ROOT=.
RELEASE+= $(ALL_SOURCES) $(DEDUCED_CFILES) $(DEDUCED_HEADERS) Makefile

release:
	@for f in $(RELEASE) ; do echo $(FWD_ROOT)/\$\$f ; done
	    
EOF

##############################################################################
#
# partie specifique a Development
#

[ ! "$production" ] && cat >> $MAKEFILE <<%

check_sccs:
	@[ ! "\`sccs tell\`" ] || \\
	{ echo; echo "sccs files being edited, cannot install"; echo; \\
	  exit 1;}

# install installs sources, so depends on sources. FC
# to insure the library is compiled before hand, a make is added.
.install: $(ALL_SOURCES) check_install check_sccs
	$(MAKE) $(GMKNODIR) all $(TARGET_DIR) 
	@echo ""; echo; echo -n "Description of changes: " ; \\
	read comments ; \\
	install_pips_sources \\
		-rv -s \`pwd\` -t $(TARGET_DIR) -y "\$\$comments" \\
		$(ALL_SOURCES)
	-@cd $(TARGET_DIR) ; pips-makemake $PIPSMKMK_OPTION -P
	touch .install
	$(MAKE) quick-install

install:  .install

#
# diff between dev and prod sources:

diff:
	-@for f in $(ALL_SOURCES) ; \\
	do \\
	  echo "DIFFERENCES BETWEEN DEV AND PROD FOR \$\$f:" ; \\
	  $(DIFF) \$\$f $(TARGET_DIR)/\$\$f ; \\
	done

%



##############################################################################
#
# La partie commune aux bibliotheques et aux passes :

[ $DIRTYPE = 'Lib' -o $DIRTYPE = 'Passes' -o $DIRTYPE = 'Linear' ] && 
cat >> $MAKEFILE <<%
#

$(${PART}_LIBDIR):
	mkdir $(${PART}_LIBDIR)

lint:
	$(TYPECHECK) $(CFILES) | 
		sed '/possible pointer alignment/d;/gen_alloc/d'

TAGS: $(INCLUDES) $(CFILES)
	etags $(INCLUDES) $(CFILES)
	ctags $(INCLUDES) $(CFILES)

$(TARGET)-local.h:
	[ -f $(TARGET)-local.h ] || touch $(TARGET)-local.h

# headers are not generated automatically, bacause it should be
# done each time a c file is touched, which is too much...
# thus it does depend only of the -local.h.
# header file reconstruction should be required explicitely
# with the header rule.
# some filtering is performed to avoid variations that depends on
# includes...

build-header-file:
	@$(COPY) $(TARGET)-local.h $(INC_TARGET);
	{ \\
	echo "/* header file built by $(PROTO) */";\\
	echo "#ifndef ${dir_simple_name}_header_included";\\
	echo "#define ${dir_simple_name}_header_included";\\
	cat $(TARGET)-local.h;\\
	$(PROTOIZE) $(INC_CFILES) | \\
	  sed 's/struct _iobuf/FILE/g;s/__const/const/g;/_BUFFER_STATE/d;' ;\\
	echo "#endif /* ${dir_simple_name}_header_included */";\\
	} > $(INC_TARGET).tmp
	$(MOVE) $(INC_TARGET).tmp $(INC_TARGET)

# .header carrie all dependencies for INC_TARGET:
.header: $(TARGET)-local.h $(DERIVED_HEADERS) $(INC_CFILES) 
	$(MAKE) $(GMKNODIR) build-header-file
	touch .header

# checks for the header file, and build if necessary...

# header: checks for INC_TARGET dependencies (.header) and for
# INC_TARGET existance !
header: .header $(INC_TARGET)

$(INC_TARGET): $(TARGET)-local.h 
	$(RM) .header
	$(MAKE) $(GMKNODIR) .header

%



##############################################################################

[ $DIRTYPE = 'Lib' -o $DIRTYPE = 'Passes' -o $DIRTYPE = 'Newgen' -o $DIRTYPE = 'Linear' ] && cat >> $MAKEFILE <<%
#

# indirect depend bacause I do not trust make for the inclusion of
# Makefile.depend if that very file does not exist.

.depend: $(CFILES) $(DERIVED_CFILES) $MAKEFILE.depend.$(ARCH)
	touch \$@

depend: .depend

# default rule if the dependence file is not there...
# forces the regeneration:
# - the dependences' generation needs the headers
# - the headers are generated thru the Makefile.
# - the Makefile needs the dependences.
# how to get out of this?
$MAKEFILE.depend.$(ARCH):
	# creates an empty dependence file, it is ok for going on and
	# will prevent any recursion for generating the same dependences.
	touch \$@ 
	# the headers are needed. 
	test ! "$(INC_TARGET)" -o -f "$(INC_TARGET)" || \\
	    $(MAKE) $(GMKNODIR) $(INC_TARGET)
	# may need the derived files
	test ! "$(DERIVED_CFILES)" || $(MAKE) $(GMKNODIR) $(DERIVED_CFILES)
	# now it's okay fo building all the dependences.
	test ! "$(CFILES)$(DERIVED_CFILES)" || \\
	        $(PREPROC) -M $(CFILES) $(DERIVED_CFILES) |\\
		sed 's,^\(.*\.o:\),\$\$(ARCH)/\1,' > \$@

#
# dependences are stored in another file which is simply included.
# the file differs for each "architectures"
include $MAKEFILE.depend.$(ARCH)
%



##############################################################################

touch .makefile

### force dependence list generation
rm -f $MAKEFILE.depend* .depend
${PIPS_MAKE:-gmake} depend

### end good case
echo

# end of $RCSfile: pips-makemake,v $
#
