#! /usr/local/bin/bash
#
# $Id$
#
# what to do at night from the pips account at cri on chailly.
#

# to get the environment when launched by cron.

test -f ~/.bashrc && source ~/.bashrc

#

script=/projects/Pips/Production/Utils/pips_at_night
mailto=pips_validation
remote=rsh
verb=:
more=

#
# FUNCTIONS

function usage()
{
    cat <<-EOF 
	$0 [-a address] [-dDhnvV] [keyword]
	    -a address: email address for messages
	    -d: debug script (just do echo)
	    -D: debug forwarded to pips_at_night
	    -h: this help
	    -v: verbose
	    -V: verbose forwarded to pips_at_night
	    -n: do nothing in pips_at_night
	    keyword: usual|long|short|compile|validate|debug
	EOF
    exit ${1:-1}
}

function verb()
{
    echo "[pips_at_night_at_cri]" "$@" `date`;
}

#
# OPTIONS

while getopts a:dDhvVn opt
do
    case ${opt} in
        a) mailto=${OPTARG} ;;
	d) script=echo ;;
	D) more=${more}D ;;
	h) usage 0 ;;
	v) verb=verb ;;
	V) more=${more}v ;;
	n) more=${more}CNLPV ;;
	*) usage 1;;
    esac
done

shift $(( $OPTIND - 1 ))

#
# what host dir archs
function doit()
{
    local what=$1 host=$2 dir=$3 archs=$4

    $verb "[doit $#] ${script} ${mailto}" \""$@"\"

    ${PIPS_PING:-ping} ${host} && ${remote} ${host} \
	${script} -${what}${more}va ${mailto} -d ${dir} -c \""${archs}"\"
}

#
# FUNCTIONS for the various jobs to be performed.

# GENERAL cleaning:  host dir archs
function general()
{
    ${verb} "[general] $@"
    doit CNLPV "$@" ;
}

# COMPILE: host dir archs
function compile()
{
    ${verb} "[compile] $@"
    doit GV "$@" ;
}

# VALIDATE (in background): host dir archs
function validate()
{
    ${verb} "[validate] $@"
    doit GCNLP "$@" &
    ${verb} "[validate] background pid: $!"
}

# COmpile and VALIDate: host dir arch
function covalid()
{
    ${verb} "[covalid] $@"
    compile "$@" ;
    validate "$@" ;
}

#
# DO THE JOB!

job=${1:-usual}

case ${job} in
    usual)
	${verb} "USUAL stuff" ;
	general chailly 	/projects/Pips . ;
	covalid recanati 	/projects/Pips/Experiments2 GNUSOL2LL ;
	covalid chailly 	/projects/Pips . ;
	covalid coulommiers 	/tmp LINUXI86 ;
	compile recanati 	/projects/Pips/Experiments2 SOL2LL ;
	compile chailly 	/projects/Pips "GNU SUN4" ;;
    long)
	${verb} "LONG stuff (more compilations)" ;
	general chailly 	/projects/Pips . ;
	covalid chailly 	/projects/Pips GNU ;
	covalid recanati 	/projects/Pips/Experiments2 GNUSOL2LL ;
	covalid coulommiers 	/tmp LINUXI86 ;
	compile recanati 	/projects/Pips SOL2LL ;
	compile chailly 	/projects/Pips ". SUN4 GPROF" ;;
    short)
	${verb} "SHORT stuff (one validation)" ;
	covalid chailly 	/projects/Pips . ;
	compile recanati 	/projects/Pips/Experiments2 GNUSOL2LL ;
	compile coulommiers 	/tmp LINUXI86 ;;
    compile)
	${verb} "COMPILE stuff" ;
	compile coulommiers 	/tmp LINUXI86 ;
	compile chailly 	/projects/Pips "GNU . SUN4 GPROF" ;
	compile recanati 	/projects/Pips "GNUSOL2LL SOL2LL" ;;
    validate)
	${verb} "VALIDATE stuff (with necessary compilation)" ;
	covalid chailly 	/projects/Pips . ;
	covalid coulommiers 	/tmp LINUXI86 ;
	covalid recanati 	/projects/Pips/Experiments2 GNUSOL2LL ;;
    debug)
	${verb} "DEBUG stuff..." ;
	validate chailly 	/projects/Pips . ;;
    *)
	${verb} "unexpected job=${job}" ;
	usage 2 ;;
esac

${verb} waiting

wait

${verb} done

# DONE
#
