#! /bin/bash
#
# $Id$
#
# Copyright 1989-2009 MINES ParisTech
#
# This file is part of PIPS.
#
# PIPS is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# PIPS is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PIPS.  If not, see <http://www.gnu.org/licenses/>.
#

# checks that pips does compile.

# TODO
# - nice?

prod=${1:-.}
dest=${2:-coelho@cri.ensmp.fr}

# report current-state message
# current-state: ok skip locked KO:*
function report()
{
  local current=$1 msg=$2 previous='unknown' repos

  # log report anyway...
  echo "$(date +%Y%m%d%H%M%S): $current ($SECONDS seconds) $msg" >> LOG

  # out if locked
  [ $current = 'locked' ] && {
    echo "message: $msg" | mailx -s 'PIPS compilation status is locked' $dest
    exit 0
  }

  # no compilation, nothing to report
  [ $current = 'skip' ] && { rmdir .lock ; exit 0 ; }

  # no change, no report
  test -f STATE && read previous < STATE
  [ "$previous" -a "$current" = "$previous" ] && { rmdir .lock ; exit 0 ; }

  # generate report
  {
    # summary
    echo PIPS compilation status has changed to $current

    # details
    echo previous state: $previous
    echo new state: $current
    echo message: $msg

    # revisions
    echo
    echo version:
    cat CURRENT
    echo
    echo previous:
    cat PREVIOUS

    if [ $current != 'ok' ]
    then
      # show stderr/stdout?
      test -f err && {
        echo
        echo err:
        tail -10 err
      }

      test -f out && {
        echo
        echo out:
        tail -10 out
      }

      # show recent commits
      echo
      echo last commits:
      for repos in pips newgen linear pips/makes
      do
        echo $repos:
	svn log --revision COMMITTED $repos
      done
    fi
  } | mailx -s "PIPS compilation status is $current" $dest

  # record new state
  echo $current > STATE

  # good bye! always 0 for cron
  rmdir .lock
  exit 0
}

# check for working copy
[ -d $prod -a -d $prod/.svn ] || report 'KO:no-wc' "working copy '$prod' not found"
cd $prod || report 'KO:cd-prod' "cannot 'cd $prod'"

# manual locking based on mkdir
mkdir .lock > /dev/null 2>&1 || report 'locked' "working copy '$prod' is already locked..."

rm -f out err
svn up >> out 2>> err || report 'KO:svn-up' "cannot 'svn up'"

[ -f CURRENT ] || touch CURRENT
mv CURRENT PREVIOUS
{
  echo pips: $(svnversion -c pips)
  echo newgen: $(svnversion -c newgen)
  echo linear: $(svnversion -c linear)
  echo nlpmake: $(svnversion -c pips/makes)
} > CURRENT

if ! cmp -s CURRENT PREVIOUS
then
  # something may have changed, let us recompile
  make unbuild > out 2> err || report 'KO:make-unbuild' "cannot 'make unbuild'"
  make build > out 2> err || report 'KO:make-build' "cannot 'make build'"
  test -x pips/bin/$(./pips/makes/arch.sh)/tpips || report 6 "no tpips found!"

  # clean up
  rm -f out err
  report 'ok' "pips is fine"
else
  # no updates
  report 'skip' "no commit since last check"
fi
