#! /bin/sh
#
# install a file only if different from the one already installed.
#
# Fabien COELHO, 03/08/95
#
# $RCSfile: pips_install_file,v $ (version $Revision$)
# ($Date: 1996/08/13 15:19:33 $, )
#

RUN=':'
script=`basename $0`

usage()
{
  echo "usage: $script -(f|l|x|r prgm)  directory files ($2)";
  exit ${1:-1}
}

while getopts flxr: opt
do
  case $opt in
    f) RUN=':' ;;
    l) RUN='ranlib' ;;
    x) RUN='chmod a+rx-w' ;;
    r) RUN="$OPTARG" ;;
    *) usage 4 "unexpected option ($opt)" ;;
  esac
done

shift `expr $OPTIND - 1`

[ $# -eq 0 ] && usage 2 "invalid number of arguments"
directory=$1
shift
[ -f $directory ] && usage 3 "$directory is not a directory"
[ -d $directory ] || mkdir $directory

# test if different

for file
do
  target=$directory/`basename $file`
  if test -f $target && cmp -s $file $target
  then
    echo "$script: skipping $file"
  else
    echo "$script: copying $file"
    rm -f $target
    cp $file $directory
    eval "$RUN $target"
    test -x $file && chmod a+rx-w $target
  fi
done

# that is all
#
