#! /bin/bash -vx
#
# $Id: pips_at_night_at_cri 13052 2008-09-29 07:46:21Z coelho $
#
# what to do at night from the pips account at TB/HPCAS.

umask 022

# A nice side effect of 32-bit system is that crazy processes die when
# reaching 2 GB of memory usage. :-)

# On a 64-bit system there is no longer such a limit, so put an arbitrary
# one to avoid host crashing during validation. Do not use more than 2 GB
# per process:
ulimit -v 2000000
ulimit -d 2000000

#email=pips-validation@cri.ensmp.fr
email=rk@enstb.org
target=~/PIPS

# set environment...
test -f $target/pipsrc.sh && source $target/pipsrc.sh

start=$(date)

#pips_at_night -t $target -m $email -u -c -v "$@" > out.$$ 2> err.$$
/home/keryell/projets/PIPS/MYPIPS/prod/pips/src/Scripts/dev/pips_at_night -t $target -d -c -v "$@"
status=$?

if [ $status -ne 0 ] ; then
  result="failed ($status)"
else
  result='succeeded'
fi

# Compile the Doxygen documentation and publish the documentation:
(
    pips_publish_www
    cd $target/prod;
    make doxygen
    DOXYGEN_PUBLISH_LOCATION_DIR=/var/www/pips/doxygen make doxygen-publish
)

mv out.$$ $target/out
mv err.$$ $target/err

end=$(date)

{
  echo "target=$target"
  echo "out=$target/out"
  echo "err=$target/err"
  echo "email=$email"
  echo "start=$start"
  echo "end=$end"
  echo "result=$result"
  echo
  echo "software revisions used in this validation:"
  echo "pips: $(svnversion $target/prod/pips)"
  echo "newgen: $(svnversion $target/prod/newgen)"
  echo "linear: $(svnversion $target/prod/linear)"
  echo "nlpmake: $(svnversion $target/prod/pips/makes)"
  echo "valid: $(svnversion $target/validation)"
} | echo ${PIPS_MAIL:-Mail} -s "[pips] `hostname` night job $result" $email
