#! /bin/sh -vx
#
# $Id$
#
# Copyright 1989-2009 MINES ParisTech
#
# This file is part of PIPS.
#
# PIPS is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# PIPS is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PIPS.  If not, see <http://www.gnu.org/licenses/>.
#

# Publish the WWW pages on the PIPS web site.

if [ -z "$PIPS_ROOT" ] ; then
    echo The PIPS_ROOT variable must be defined first
    exit
fi

cd $PIPS_ROOT

# Make files as readable by group member so that on the web site group
# members can overwrite the files:
chmod -R g+w doc html

# Add the sticky bit for group to inherit the parent group with BSD semantics:
find doc html -type d -exec chmod g+ws '{}' +

# Publish without deleting:
rsync -av doc/. html/. ssh.cri.ensmp.fr:~pips/public_html
