#! /usr/local/bin/bash
#
# $Id$
#
# what to do at night from the pips account at cri on chailly.
#

script=/projects/Pips/Utilities/pips_at_night
mailto=pips_validation
remote=rsh
verb=:
more=

#
# FUNCTIONS

function usage()
{
    echo "pips_at_night_at_cri [-gGvn]";
    exit ${1}
}

function verb()
{
    echo "[pips_at_night_at_cri]" "$@" `date`;
}

#
# OPTIONS

while getopts gGvn opt
do
    case ${opt} in
        g) mailto=coelho ;;
	G) script=echo ;;
	v) verb=verb ;;
	n) more=CNLPV ;;
	*) usage 1;;
    esac
done

# what host dir archs
function doit()
{
    local what=$1 host=$2 dir=$3 archs=$4

    $verb "[doit $#] ${script} ${mailto}" \""$@"\"

    if [ $(hostname) = ${host} ]
    then 
	${script} -${what}${more}va ${mailto} -d ${dir} -c \""${archs}"\"
    else
	${PIPS_PING:-ping} ${host} && ${remote} ${host} \
	    ${script} -${what}${more}va ${mailto} -d ${dir} -c \""${archs}"\"
    fi
}

# COmpile and VAlidate
# host dir archs
function docova()
{
    ${verb} "[docova] compilation $@"
    doit V "$@" ;

    ${verb} "[docova] validation $@"
    doit CNLP "$@" &
}

# COMPile
# host dir archs
function docomp()
{
    ${verb} "[docomp] compilation $@"
    doit V "$@" ;
}

#
# DO IT!

docova coulommiers /tmp LINUXI86
docova recanati /projects/Pips/Experiments2 GNUSOL2LL
docova chailly ${HOME} .

# remaining compilations
docomp recanati /projects/Pips/Experiments2 SOL2LL
docomp chailly ${HOME} "GNU SUN4 GPROF"

${verb} waiting

wait

${verb} done

# DONE
#
