#! /bin/bash
#
# $Id$
#
# what to do at night from the pips account at cri.

umask 022

start=$(date)
email=coelho@cri.ensmp.fr
target=~/PIPS
test -f $target/pipsrc.sh && source $target/pipsrc.sh

pips_at_night -t $target -V VOPT=$email -u -c -v \
    > $target/out 2> $target/err

end=$(date)

{
  echo "  target=$target"
  echo "  out=$target/out"
  echo "  err=$target/err"
  echo "  email=$email"
  echo "  start=$start"
  echo "  end=$end"
} | ${PIPS_MAIL:-Mail} -s '[pips] night job summary' $email
