#! /bin/sh
#
# $RCSfile: pips_at_night,v $ version $Revision$
# ($Date: 1996/07/11 12:47:45 $, )
# 
# what to do at night...
# (c) Fabien COELHO July 1996
#
# source environment if needed.

[ "$PIPS_DIR" ] || . /projects/Pips/pipsrc.sh

user=`whoami`
email=${REPLYTO:-$user}
script=`basename $0`
verbose=:

verb()
{
    echo "$script" "$@"
}

usage()
{
    ret=$1
    shift
    cat <<-EOF
	$script (version $Revision$) - "$@"
	  -h: this help
	  -v: verbose
	  -a email : report to this address
EOF
    exit $ret
}

while getopts hva: OPT
do
    case $OPT in
	h) usage 0 "some help" ;;
	a) email=$OPTARG ;;
	v) verbose=verb ;;
	*) usage 2 "invalid option" ;;
    esac
done

REPORT=/tmp/${script}.${user}.$$
rm -f ${REPORT}

#
# do the job

{
$verbose starting $script for $email 
$verbose date: `date`

$verbose deleting old workspaces...
find ${PIPS_HOME}/Pips -name '*.database' -type d -mtime +7 -print | 
    xargs ${PIPS_UTILDIR}/Delete

$verbose removing core files older than one week
find ${PIPS_HOME}/Pips -name core -mtime +7 -print | 
    xargs rm -f

$verbose recompiling NEWGEN - Production
{
make-pips -no ${REPORT} FWD_MSG='Newgen:[P,SUN4]' ARCH=SUN4 clean recompile
make-pips -no ${REPORT} FWD_MSG='Newgen:[P,.]' ARCH=. clean recompile
} 2>&1 | mail -s "$script: newgen recompile night report" $email

$verbose recompiling LINEAR - Production
{
make-pips -lo ${REPORT} FWD_MSG='Linear:[P,SUN4]' ARCH=SUN4 clean recompile
make-pips -lo ${REPORT} FWD_MSG='Linear:[P,.]' ARCH=. clean recompile
} 2>&1 | mail -s "$script: linear recompile night report" $email

$verbose recompiling PIPS - Production
{
make-pips -po ${REPORT} FWD_MSG='Pips:[P,SUN4]' ARCH=SUN4 clean recompile
make-pips -po ${REPORT} FWD_MSG='Pips:[P,.]' ARCH=. clean recompile
} 2>&1 | mail -s "$script: pips recompile night report" $email

# summary
mail -s "$script: recompile night report summary" $email < ${REPORT}
rm -f ${REPORT}

# Validate Pips
$verbose Validating PIPS
Validate -vti 50 -a ${email}

$verbose date: `date`
$verbose end of  $script for $email 
} 2>&1 | mail -s "$script: night report" ${email}
