#! /bin/sh
# $RCSfile: remove_from_sccs_file,v $ (version $Revision$)
# $Date: 1996/07/16 11:29:15 $, 

MOTIF="$1"
shift

set -e

for f
do
  dir=`dirname $f`
  file=`basename $f`
  echo doing $file in $dir
  ( cd $dir 
    sccs edit $file
    sed "/$MOTIF/d" < $file > $file.tmp
    mv -f $file.tmp $file
    sccs delget -y"$0: $MOTIF" $file
  )
done
