#! /bin/sh

# Sauvegarde des re'sultats dans $TEMPDIR. Reutilisation avec -l
#
# -l: last search is restored (this case, other options are NOT effective)
# 
# Le PATH de recherche est defini avec:
# -P: search in $PIPS_DIR (default)
# -L: search in $LINEARDIR (default)
# -N: search in $NEWGENDIR (default)
# -d: directory from which search occures
#
# Les fichiers trouve verifient
# alternativement (operateur ou):
# -c: files named core
# -o: files named *.o
# -p: plain files named pips
# -w: workspaces: directories named *.database
# -~: files named *~
# -n name: fichier de nom name
# et conjonctivement (operateur et):
# -h: huge files: more than 1Mo
# -m N: files not modified for less than N days
#
# -e: The end of command must be punctuated by a simple semicolon, eg "rm {} ;"
# -D: Delete workspaces
#
# Exemples:
# -  search-pips -w -m 30 -e "rm {} ;"
#
# Whiches:
# -k: ok: replaces -exec with -ok in find.
# -s: safe: some files and directories are filtered
#
# Bugs:
# - Probleme pour "quoter" les chaines du type *.o dans les variables shell. 
# Il faudrait que find accepte les variables true et false (voir ${}).
#
# Bruno Baron, novembre 1991
#
# Modifications:
#  - nettoyage de Pips/Production/Bin: seuls pips et wpips sont conserves

USAGE="Usage: $0 [-l] [-PLN] [-d directory] [-copw~] [-n name]... [-hm] [-e cmd_to_exec]"

usage () {
echo "Usage: search [-l]"
echo "               [-PLN] [-d directory]" 
echo "               [-copw~] [-n name]..."
echo "               [-hm]"
echo "               [-e cmd_to_exec]"
}

LAST=""
SAFE=""
PIPS=""
LINEAR=""
NEWGEN=""
DIRECTORY=""
CORE=""
OBJECT=""
PIPSFILE=""
WSPACE=""
TILDE=""
NAME=""

HUGE=""
MONTH=""

EXEC=""
DELETE=""

while getopts lsPLNcopw~hm:Dd:n:e: OPT
do
	case $OPT in
	l)	LAST=TRUE;;
	s)	SAFE=TRUE
		echo -$OPT not available yet >&2
		exit 1;;
	P)	PIPS=TRUE;;
	L)	LINEAR=TRUE;;
	N)	NEWGEN=TRUE;;
	d)	DIRECTORY=$OPTARG;;
	c)	CORE="-o -name core";;
	o)	OBJECT="-o -name '*.o'";;
	p)	PIPSFILE="-o ( -name pips -a -type f )";;
	w)	WSPACE="-o -name '*.database'";;
	~)	TILDE="-o -name '*~'";;
	n)	NAME="$NAME -o -name $OPTARG";;
	h)	HUGE="-size +2000";;
	m)	MONTH="-mtime +$OPTARG";;
	e)	EXEC="-exec $OPTARG";;
	D)	# option -prune because find cannot search a directory 
		# after it has been deleted.
		DELETE="-prune -exec Delete {} ;";;
	\?)	usage >&2
		exit 2;;
	esac
done
shift `expr $OPTIND - 1`
if [ $# -ge 1 ]
then
	# echo \$#=$# \$OPTIND=$OPTIND
	usage >&2
	exit 2
fi

# set OUTPUT to a file in $TEMPDIR
if [ ! -d $PIPS_TEMPDIR ]
then 
echo "\$PIPS_TEMPDIR=$PIPS_TEMPDIR is not a directory" >&2
exit 1
else 
  WHOAMI=`whoami`
  OUTPUT=$PIPS_TEMPDIR/`date +"search.%y%m%d"`.$WHOAMI
  # touch $OUTPUT
  #
  # clean old searches
  # ls $TEMPDIR/search.*.$WHOAMI | grep -v $OUTPUT | xargs rm -f
fi

# set SEARCHPATH
SEARCHPATH=""
if [ -n "$DIRECTORY" ]
then
	if [ -d "$DIRECTORY" ]
	then SEARCHPATH="$DIRECTORY"
	else 
	echo "$DIRECTORY is not a directory" >&2
	exit 1
	fi
else	if [ -z "$PIPS$LINEAR$NEWGEN" ]
	then 
	PIPS=TRUE; LINEAR=TRUE; NEWGEN=TRUE
	fi
fi
if [ -n "$PIPS" ]
then SEARCHPATH="$SEARCHPATH $PIPS_DIR"
fi
if [ -n "$LINEAR" ]
then SEARCHPATH="$SEARCHPATH $LINEARDIR"
fi
if [ -n "$NEWGEN" ]
then SEARCHPATH="$SEARCHPATH $NEWGENDIR"
fi
# PIPS_HOME=/home/users/pips 


if [ -n "$LAST" ]
then
	# Reuse previous search results, accumulated in $OUTPUT
	if [ -f "$OUTPUT" ]
	then
	cat $OUTPUT
	else
	echo Last $0 cannot be restored
	fi
else
# search
if [ -n "$NAME$CORE$OBJECT$WSPACE$TILDE$PIPSFILE" ]
then # search with find
ALWAYS="-name foofoo"
echo "find $SEARCHPATH \( $ALWAYS $NAME $CORE $OBJECT $WSPACE $TILDE $PIPSFILE \) $HUGE $MONTH $EXEC $DELETE -print | tee $OUTPUT" >&2

find $SEARCHPATH \( $ALWAYS $NAME $CORE $OBJECT $WSPACE $TILDE $PIPSFILE \) $HUGE $MONTH $EXEC $DELETE -print | tee $OUTPUT
else
echo "find $SEARCHPATH $HUGE $MONTH $EXEC -print | tee $OUTPUT" >&2
find $SEARCHPATH $HUGE $MONTH $EXEC -print | tee $OUTPUT
fi
fi

# Memo:
# -name 'gmon.out'
# -name 'mon.out'

