// Check the use of information generated by points-to analysis

// Not ready yet, because the interprocedural points-to analysis is
// not implemented yet

// Same as pointer01, but the tpips file uses points-to information

int x;
int y;
int z;

void foo(int *p)
{
  (*p)++;
}

int main()
{
  x= 1, y=2, z=3;
  int *p = (int *)malloc(sizeof(int));
  foo(p);
  p = &x;
  foo(p);
  return x+y+z; // no information left about x, y and z
}
