#!/bin/sh
Delete $WSPACE >&2
if Pips -f $FILE -w $WSPACE -m $NAME -s prcpe -b PF >&2
then
	echo "--- Proper effects for $NAME"
	Display -l prop
	exit_status=0
else
	exit_status=1
fi
Delete $WSPACE
exit $exit_status
