#! /bin/sh
#
# $RCSfile: epips,v $ (version $Revision$)
# $Date: 1995/11/28 14:05:45 $, 
#

${EPIPS_EMACS:-emacs} \
     "$@" \
     -l ${EPIPS_LISP:-${PIPS_UTILDIR}/epips.el} \
     -iconic \
     -name epips \
     -f epips-launch-alone

# that is all
#
