#! /bin/sh
#
# $Id$
#

${EPIPS_EMACS:-emacs} \
     "$@" \
     -l ${EPIPS_LISP:-${PIPS_ROOT}/share/epips.el} \
     -iconic \
     -name Epips \
     -title Epips \
     -f epips-launch-alone

# that is all
#
