#! /bin/sh
#
# $RCSfile: epips,v $ (version $Revision$)
# $Date: 1996/08/20 09:13:02 $, 
#

${EPIPS_EMACS:-emacs} \
     "$@" \
     -l ${EPIPS_LISP:-${PIPS_ROOT}/Share/epips.el} \
     -iconic \
     -name Epips \
     -f epips-launch-alone

# that is all
#
