#! /bin/sh
#
# $Id$
# $Log: hpfc_generate_h,v $
# Revision 1.5  1997/03/20 07:51:51  coelho
# better RCS headers.
#
#

tr '[A-Z]' '[a-z]' |
sed -n '/function/s,^      [ 	]*\([a-z\*0-9]*\)[ 	]*function[ 	]*\([a-z0-9_ ]*\).*$,      external \2      \1 \2,p' |
tr '' '\012'

#
# that is all
#
