#! /bin/sh
#
# $Id$
#
# Copyright 1989-2014 MINES ParisTech
#
# This file is part of PIPS.
#
# PIPS is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# PIPS is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PIPS.  If not, see <http://www.gnu.org/licenses/>.
#

# output a description file for qsub.

npes=`sed -n 's,      parameter(REALMAXSIZEOFPROCS = \(.*\)),\1,p' \
	global_parameters.h`
npes=`expr $npes + 1`

pwd=`pwd`

cat <<-EOF
	#QSUB -r ${1:-hpfc}
	#QSUB -eo
	#QSUB -l mpp_p=${npes}
	#QSUB -l mpp_t=200
	#QSUB -s /bin/sh
	TARGET=cray-t3d
	export TARGET
	cd ${pwd}
	${1}_main -npes ${npes} 2> run.err > run.out
EOF

