#! /bin/sh
#
# $RCSfile: hpfc_generate_init,v $ ($Date: 1994/09/08 13:11:51 $, )
# version $Revision$
# got on %D%, %T%
# $Id$
#
# generate the initialization file
#

script=`basename $0`
unset NAME 

usage()
{
  echo "Usage: $script [ -n name ] dirname" 1>&2
  exit 1
}

while getopts n: OPT
do
  case $OPT in
    n) NAME=$OPTARG ;;
    *) usage ;;
  esac
done

shift `expr $OPTIND - 1`

[ "$#" -eq 1 ] || usage

dirname=$1
init=$dirname/param_init.m4

NAME="${NAME:-`basename $dirname .database`}"
NAME=`echo $NAME | tr 'A-Z' 'a-z'`

{
  echo "      subroutine HPFC_INIT_COMMON_PARAM()"
  echo "      include \"hpfc_commons.h\""
  for file in $dirname/*_parameters.h
  do
    echo "      include \"`basename $file`\""
  done
  for file in $dirname/*_init.h
  do
    echo "      include \"`basename $file`\""
  done
  echo "      NODE_PROGRAM_NAME=\"${NAME}_node\""
  echo "      NODE_ARCHITECTURE=\"PVM_ARCHITECTURE\""
  echo "      HPFC_GROUP_NAME=\"${NAME}_group\""
  echo "      end"
} > $init

$HPFC_TOOLS/hpfc_add_warning $init
