// lhs and rhs with store dependent subscripts
// also tests elimination of syntactically equivalent pointer_values
// generated by b[++i] = a (b[*] == a(may) is redundant with a==b[*] (may))

// FI: I add to initialize partially b to avoid an undefined assignment

#include <stdlib.h>

int main()
{
  int *a;
  int i = 5;
  int * b[10];
  b[i] = &i;
  a = b[i];
  b[++i] = a;
  return(0);
}
