program main
  INTEGER :: VARIABLE_WITH_A_VERY_LONG_NAME01
  INTEGER :: VARIABLE_WITH_A_VERY_LONG_NAME02
  INTEGER :: VARIABLE_WITH_A_VERY_LONG_NAME03
  INTEGER :: VARIABLE_WITH_A_VERY_LONG_NAME04

  VARIABLE_WITH_A_VERY_LONG_NAME01 = 1
  VARIABLE_WITH_A_VERY_LONG_NAME02 = 2
  VARIABLE_WITH_A_VERY_LONG_NAME03 = 3

  VARIABLE_WITH_A_VERY_LONG_NAME04 =  VARIABLE_WITH_A_VERY_LONG_NAME01 +  VARIABLE_WITH_A_VERY_LONG_NAME02 + &
  VARIABLE_WITH_A_VERY_LONG_NAME03

  print *, VARIABLE_WITH_A_VERY_LONG_NAME04

end program main
