C
C     TWO-ELECTRON INTEGRAL DERIVATIVE (QUANTUM CHEMISTRY) BENCHMARK.
C     H. B. SCHLEGEL, WAYNE STATE UNIVERSITY.
C
      SUBROUTINE ACLEAR(N,A)
      REAL*8 A(1)
      DO 10 I=1,N
   10 A(I)=0.D0
      RETURN
      END
