#!/bin/bash
# Copyright 2007, 2008, 2009 Alain Muller, Frederique Silber-Chaussumier
#
#This file is part of STEP.
#
#The program is distributed under the terms of the GNU General Public
#License.

# Ce script filtre le code généré par PIPS pour remplacer l'include de textuel par la directive INCLUDE
# - le premier argument indique le répertoir d'instalation
# - les arguments suivant indique les fichiers à filtrer

INSTAL_DIR=$1
shift 1

mkdir -p $INSTAL_DIR;

while [[ $# -gt 0 ]];
do
    if [ $(basename $1) = $(basename $1 .c) ] ; then
	awk 'BEGIN {cut=0} cut == 0 && /! include "STEP.h"/ {cut=1} cut == 0 {print $0;} cut == 1 && /! end include "STEP.h"/ {cut=0}' $1 | \
	    sed 's,!       include "STEP.h",      include "STEP.h",g' | \
	    sed 's,!       implicit none,      implicit none,g' | \
	    sed 's,! MIL-STD-1753 Fortran extension not in PIPS\n,,' >$INSTAL_DIR/step.tmp
    else
	echo "#include \"step_api.h\"" >$INSTAL_DIR/step.tmp
	cat $1 >> $INSTAL_DIR/step.tmp
    fi
    mv $INSTAL_DIR/step.tmp $INSTAL_DIR/$(basename $1)
    shift
done
