#! /bin/sh
#
# $RCSfile: hpfc_delete,v $ version $Revision$
# $Date: 1994/11/04 15:59:55 $, 
# got on %D%, %T%
#

script=`basename $0`
VERBOSE=':'
DEBUG=':'

usage()
{
  cat 2>&1 <<-EOF
	Usage: $script [-vDh] ws...
	  version is $Revision$
	  -v: verbose
	  -D: debug
	  -h: help
	  ws: workspace(s)
	EOF
  exit ${1:-1}
}

verbose()
{
  echo "$script: $@"
}

debug()
{
  echo "$script: $@" 1>&2
}

while getopts vDh OPT
do
  case $OPT in
    v) VERBOSE='verbose' ;; 
    D) DEBUG='debug' ;;
    h|*) usage 1 ;;
  esac
done

shift `expr $OPTIND - 1`

for ws
do
  WORKSPACE=`dirname $ws`/`basename $ws .hpfc` 
  $VERBOSE "deleting $WORKSPACE"
  [ -d "$WORKSPACE.hpfc" ] && rm -rf "$WORKSPACE.hpfc"
done

#
# That is all
#
