#! /bin/sh
#
# Installation in directory...
#
# $RCSfile: hpfc_install,v $ ($Date: 1995/08/08 17:50:03 $, )
# version $Revision$
#

# defaults

SCRIPT=`basename $0`

unset DIRECTORY SRCDIR BASEDIR REFFILE TOINSTALL TOMAKE

VERBOSE=':'
DEBUG=':'
SRCDIR=${HPFC_INCLUDE:-$PIPS_EXTEDIR}
MAKE='gmake'
M4='m4'

#

if [ -f "${PIPS_CURRENT_PROGRAM:-.pipsprogram}" ] 
then
  BASEDIR="$PWD/`sed -n 's,^PGM=\(.*\)\$,\1,p' .pipsprogram`.database"
fi

# get options

usage()
{
  cat <<-EOF
	Usage: $SCRIPT [options]
	   version $Revision$
	   -h: help
	   -i: install
	   -m: make
	   -v: verbose
	   -d: debug
	   -q: quiet
	   -n name: target name
	   -t dir: target directory
	   -b dir: database (default current database)
	   -s dir: where other sources are (default HPFC_INCLUDE then EXTEDIR)
	   -f file: reference file (default none)
	EOF
  exit ${1:-1}
}

while getopts himvdqt:s:b:f:n: OPT
do
  case $OPT in
    h) usage 0 ;;
    i) TOINSTALL=1 ;;
    m) TOMAKE=1 ;;
    v) VERBOSE='echo' ;;
    d) DEBUG='echo' ;;
    q) VERBOSE=':' ;;
    t) DIRECTORY="$OPTARG" ;;
    s) SRCDIR="$OPTARG" ;;
    b) BASEDIR="$OPTARG" ;;
    f) REFFILE="$REFFILE $OPTARG" ;;
    n) NAME="$OPTARG" ;;
    *) usage
  esac
done

shift `expr $OPTIND - 1`

#
$DEBUG checking

[ "$#" -eq 0 ] || usage
[ "$BASEDIR" ] || usage

NAME=`echo ${NAME:-\`basename $BASEDIR .database\`} | tr 'A-Z' 'a-z'`

[ "$DIRECTORY" ] ||
{
  DIRECTORY=$BASEDIR/hpfc
  [ ! -d "$DIRECTORY" ] && mkdir $DIRECTORY
}

#
$DEBUG installating

if [ "$TOINSTALL" ]
then
  $VERBOSE "installing in $DIRECTORY"

  $VERBOSE "cleaning $DIRECTORY"
  rm -f $DIRECTORY/*
  
  touch $BASEDIR/_host.h $BASEDIR/_node.h

  $VERBOSE "copying files in $DIRECTORY"

  {
    echo "TARGET = $NAME" 
    cat $SRCDIR/hpfc_Makefile_init 
  } > $DIRECTORY/Makefile

  cp $SRCDIR/hpfc_check.f \
     $SRCDIR/hpfc_Makefile \
     $SRCDIR/hpfc_*.h \
     $SRCDIR/hpfc_architecture_m4_macros \
     $BASEDIR/param_init.m4 \
     $BASEDIR/*_host.f \
     $BASEDIR/*_host.h \
     $BASEDIR/*_node.f \
     $BASEDIR/*_node.h \
     $BASEDIR/*_parameters.h \
     $BASEDIR/*_init.h \
     $DIRECTORY

  $DEBUG "$REFFILE"
  [ "$REFFILE" ] && cp `echo "$REFFILE" | cut -d " " -f 2` $DIRECTORY/$NAME.f

  touch $DIRECTORY/hpfc_Makefile

  chmod u+w $DIRECTORY/*
fi

#
$DEBUG making

if [ "$TOMAKE" ] 
then
  $VERBOSE "making"
  cd $DIRECTORY
  $MAKE Makefile
  $MAKE all
fi

#
# that is all
#
