#! /bin/sh
#
# $Id$
#

script=`basename $0`
VERBOSE=':'
DEBUG=':'

usage()
{
  cat 2>&1 <<-EOF
	Usage: $script [-vDh] ws...
	  version is $Revision$
	  -v: verbose
	  -D: debug
	  -h: help
	  ws: workspace(s) (default *.hpfc)
	EOF
  exit ${1:-1}
}

verbose()
{
  echo "$script: $@"
}

debug()
{
  echo "$script: $@" 1>&2
}

while getopts vDh OPT
do
  case $OPT in
    v) VERBOSE='verbose' ;; 
    D) DEBUG='debug' ;;
    h|*) usage 1 ;;
  esac
done

shift `expr $OPTIND - 1`

[ $# -eq 0 ] && set *.hpfc

for ws
do
  WORKSPACE=`echo $ws | sed 's,\.hpfc/*$,,'`
  $VERBOSE "deleting $WORKSPACE"
  [ -d "$WORKSPACE.hpfc" ] && rm -rf "$WORKSPACE.hpfc"
done

#
# That is all
#
