#! /bin/sh
#
# Installation in directory...
#
# $Id$
# $Log: hpfc_install,v $
# Revision 1.37  1997/11/22 15:32:13  coelho
# fix for new database organization.
#
# Revision 1.36  1997/10/27 15:47:03  coelho
# unsplit should work fine ?
#
# Revision 1.35  1997/10/27 13:55:24  coelho
# new version with Src
#
# Revision 1.33  1997/03/20 09:48:43  coelho
# *_both.f files also copied.
#
# Revision 1.32  1997/03/19 17:51:37  coelho
# better RCS headers
#
#

# defaults

unset tdir srcdir basedir reffiles toinstall tomake unsplit

verb=':'
debug=':'
srcdir=${HPFC_RUNTIME:-$PIPS_ROOT/Runtime/hpfc}
MAKE=${HPFC_MAKE:-${PIPS_MAKE:-gmake}}
M4=${HPFC_M4:-m4}

verbose()
{ echo "[hpfc_install]:" "$@" >&2;}

#

if [ -f "${PIPS_CURRENT_PROGRAM:-.pipsprogram}" ] 
then
  basedir="$PWD/`sed -n 's,^PGM=\(.*\)\$,\1,p' .pipsprogram`.database"
fi

# get options

usage()
{
  cat <<-EOF
	Usage: $RCSfile: hpfc_install,v $ [options]
	   version $Revision$
	   -h: help
	   -i: install
	   -m: make
	   -v: verbose
	   -d: debug
	   -q: quiet
	   -o: regenerate an origin file
	   -n name: target name
	   -t dir: target directory (default hpfc)
	   -b dir: database (default current database)
	   -s dir: where other sources are (default HPFC_INCLUDE then EXTEDIR)
	   -f file: reference file (default none)
	EOF
  exit ${1:-1}
}

while getopts himvdqot:s:b:f:n: OPT
do
  case $OPT in
    h) usage 0 ;;
    i) toinstall=1 ;;
    m) tomake=1 ;;
    v) verb='verbose' ;;
    d) debug='verbose' ;;
    q) verb=':' ;;
    o) unsplit=':' ;;
    t) tdir="$OPTARG" ;;
    s) srcdir="$OPTARG" ;;
    b) basedir="$OPTARG" ;;
    f) reffiles="$reffiles $OPTARG" ;;
    n) name="$OPTARG" ;;
    *) usage
  esac
done

$debug "args:" "$@"
shift `expr $OPTIND - 1`

#
$debug checking

[ "$#" -eq 0 ] || usage
[ "$basedir" ] || usage

name=`echo ${name:-\`basename $basedir .database\`} | tr 'A-Z' 'a-z'`

[ "$tdir" ] ||
{
  tdir=$basedir/hpfc
  $verb "cleaning $tdir"
  rm -rf $tdir
  mkdir $tdir
}

#
$debug installating

if [ "$toinstall" ]
then
  $verb "installing in $tdir"

  {
    echo "NAME = $name" 
    cat $srcdir/hpfc_Makefile_init 
  } > $tdir/Makefile

  cp $basedir/Src/* $tdir

  [ "$unsplit" ] && set $basedir/[A-Z][A-Z]*/*.f_initial
  [ "$reffiles" ] && set `echo "$reffiles" | cut -d " " -f 2`

  $debug rebuilding initial source file
  for f 
  do
     $debug "considering $f"
    egrep -s '(^[!cC\*][Ff][Cc][Dd]\$[ 	]*[Ff][Aa][Kk][Ee][ 	]*$|hpfc9)' \
	$f || { $debug "adding $f" ; cat $f ; } 
  done > $tdir/$name.f

  chmod ug+w $tdir/*
fi

#
$debug making

if [ "$tomake" ] 
then
  $verb "making"
  cd $tdir
  $MAKE Makefile
  $MAKE all
fi

#
# that is all
#
