#! /bin/sh
#
# $RCSfile: hpfc_directives,v $ ($Date: 1995/04/18 12:02:29 $, )
# version $Revision$
# got on %D%, %T%
#
# Filter to switch from hpf directives to subroutine calls to be parsed
# by a Fortran 77 parser. I guess some perl or awk might be much nicer
# and more efficient, but I'm not very good at it:-) Looks like an exercice
# of style, "yes I can do it with seds and trs";-) It may be thought as
# clever or stupid:-)
# Only one subroutine or function should be put in the pipe. 
# ??? I do not deal with "R E A L" like Fortran lexical problems.
# ??? There may be problems with if and do instructions...
#
# FC 02/95.
#
# F77 and HPF directives -> 
# calls to HPFC special subroutines and functions -> 
# HPFC subs and functs analyzed and removed -> 
# analyzes on the correct transformed code
#

#
# _ is hpfc:
#
# _a: align
# _b: realign
# _c: cyclic
# _d: distribute
# _e: redistribute
# _i: independent
# _k: block 
# _n: new
# _p: processors
# _s: *
# _t: template
# _u: pure
# _y: dynamic
#
# _o: temporary for logical
#
# missing: inherit
#
# move static directives AFTER declarations, since I need to parse them
# as statements.
#

#
# commands:
#
# the sed version should be able to handle very large lines... 
# gnu sed is okay.
# idem tr.

SED=${HPFC_SED:-sed}
TR=${HPFC_TR:-tr}
RM=rm
BASENAME=basename

#
# temporary files prefix

SCRIPT=`$BASENAME $0`

TMP=/tmp/$SCRIPT.$$
$RM -f $TMP.*

#
# directive normalization
#
$SED 's,^[Cc!\*][Hh][Pp][Ff]\$\(.\)[ 	]*,chpf$\1,' |
#
# and continuation handling:
# put on one line
#
$TR '\012' '' | 
#
# remove not desired cr (& and 6 column styles)
#
$SED 's,&[ 	]*chpf\$., ,g
      s,chpf\$[^ ], ,g' | 
#
# and back to a normal file
#
$TR '' '\012' | 
#
# massive transformations
#
$SED '/^chpf\$/s,\([ 	\,(]\)[Bb][Ll][Oo][Cc][Kk]\([ 	\,()]\),\1_k\2,g
      /^chpf\$/s,\([ 	\,(]\)[Bb][Ll][Oo][Cc][Kk]\([ 	\,()]\),\1_k\2,g
      /^chpf\$/s,_k\([\,)]\),_k()\1,g
      /^chpf\$/s,\([ 	\,(]\)[Cc][Yy][Cc][Ll][Ii][Cc]\([ 	\,()]\),\1_c\2,g
      /^chpf\$/s,\([ 	\,(]\)[Cc][Yy][Cc][Ll][Ii][Cc]\([ 	\,()]\),\1_c\2,g
      /^chpf\$/s,_c\([\,)]\),_c(1)\1,g
      /^chpf\$/s,\*\([\,)]\),_s()\1,g
      s,^chpf\$ [Dd][Yy][Nn][Aa][Mm][Ii][Cc] \(.*\),      _y(\1),
      s,^chpf\$ [Pp][Uu][Rr][Ee] \(.*\),      _u(\1),
      s,^chpf\$ [Tt][Ee][Mm][Pp][Ll][Aa][Tt][Ee] \(.*\),      _o \1      _t(\1),
      s,^chpf\$ [Pp][Rr][Oo][Cc][Ee][Ss][Ss][Oo][Rr][Ss] \(.*\),      _o \1      _p(\1),
      s,^chpf\$ [Aa][Ll][Ii][Gg][Nn] \(.*\) [Ww][Ii][Tt][Hh] \(.*\),      _a(\1\,\2),
      s,^chpf\$ [Rr][Ee][Aa][Ll][Ii][Gg][Nn] \(.*\) [Ww][Ii][Tt][Hh] \(.*\),      _b(\1\,\2),
      s,^chpf\$ [Dd][Ii][Ss][Tt][Rr][Ii][Bb][Uu][Tt][Ee] \(.*\) [Oo][Nn][Tt][Oo] \(.*\),      _d(\1\,\2),
      s,^chpf\$ [Rr][Ee][Dd][Ii][Ss][Tt][Rr][Ii][Bb][Uu][Tt][Ee] \(.*\) [Oo][Nn][Tt][Oo] \(.*\),      _e(\1\,\2),
      s,^chpf\$ [Ii][Nn][Dd][Ee][Pp][Ee][Nn][Dd][Ee][Nn][Tt][ 	]*\([^( ,][^()\,]*\),      _i(\1),
      s,^chpf\$ [Ii][Nn][Dd][Ee][Pp][Ee][Nn][Dd][Ee][Nn][Tt][ 	]*\(.*\),      _i\1,
      s,^      _i\,,      _i()\,,
      s,^      _i(\([^)]*\))[ 	]*\,[ 	]*[Nn][Ee][Ww][ 	]*(\([^)]*\)),      _i(\1)      _n(\2),
      s,_\([abdeintpyou]\),call hpfc\1,g
      s,_\([cks]\),hpfc\1,g' |
#
# handles multi lines breaking (independent with new...)
#
$TR '' '\012' |
#
# separates static directives from others
#
$SED "/^      call hpfc[adptuy]/w $TMP.1
      /^      call hpfc[adptuy]/d" > $TMP.0

#
# line before which the static directives will be inserted
# i.e. last line of the declarations.
#
# first, find the last declaration line 
# (program and subroutine needed if none!)

LINE=`
$SED -n '/^ .... [ 	]*[Ii][Nn][Tt][Ee][Gg][Ee][Rr][ 	\*]/=
         /^ .... [ 	]*[Rr][Ee][Aa][Ll][ 	\*]/=
         /^ .... [ 	]*[Ss][Tt][Rr][Ii][Nn][Gg][ 	\*]/=
         /^ .... [ 	]*[Ss][Uu][Bb][Rr][Oo][Uu][Tt][Ii][Nn][Ee][ 	]/=
         /^ .... [ 	]*[Pp][Rr][Oo][Gg][Rr][Aa][Mm][ 	]/=
         /^ .... [ 	]*[Ll][Oo][Gg][Ii][Cc][Aa][Ll][ 	\*]/=
         /^ .... [ 	]*[Cc][Oo][Mm][Pp][Ll][Ee][Xx][ 	\*]/=
         /^ .... [ 	]*[Bb][Yy][Tt][Ee][ 	\*]/=
         /^ .... call hpfco /=' $TMP.0 | 
$SED -n '$p'`

#
# then deal with continuations if any.
# comments and blank lines are also skipped, or why should I not ?

LAST_LINE=`
$SED -n "1,$LINE b
         s,^\( ....[^ ]\),\1,
         s,^\([^ ]\),\1,
         s,^\([ 	]*\)\$,\1,
         t cont
         q
         : cont
         =" $TMP.0 | 
$SED -n '$p'`

LINE=${LAST_LINE:-$LINE}

#
# final output

{
  $SED -n "1,$LINE p" $TMP.0
  $SED -n p $TMP.1
  $SED "1,$LINE d" $TMP.0
} | 
#
# breaks generated lines which are too long
# first insert some marks, after comma or parenthesis
# there should be no identifiers larger than 15 characters (55+15=70)
#
$SED '/^ .... call hpfc.[( ].\{50,\}$/s/\([^]\{55\}[^,()]*[,()]\)/\1     x /g;
      /^ .... call hpfco /s,call hpfco,logical,' |
#
# later replaced by CR
#
$TR '' '\012'

#
# clean temporary files
$RM -f $TMP.*

#
# That is all
#
