#! /bin/sh
# 
# $RCSfile: hpfc,v $ (version $Revision$)
# $Date: 1995/04/24 13:37:41 $, 
#
# hpfc scripts very front-end
# just an easy way not to have to remember the name of some scripts.
#

script=`basename $0`

# help message

usage()
{
  cat >&2 <<-END
	usage: $script [-vdq] function [options] [arguments]
	  version is $Revision$, function among (3 significant characters):
	  h|help: gives this help
	  c|compile: compile
	  f|full: compile, compile and link
	  D|debug: compile with debug option
	  C|clean: clean directories
	  d|delete: delete hpfc directory
	  F|filter: show filter result
	  m|make: compile and link
	  r|run: run...
	  v|validate: used by the validation...
	  p|pvm: pvm control
	  i|interactive: interactive mode
	  s|ls: list directory content
	  pwd: print working directory
	END
  exit ${1:-1}
}

# default may be overwritten in the environment

HPFC_MODE=${HPFC_MODE:-demo}
export HPFC_MODE

# options

while getopts vdq OPT
do
  case $OPT in
    v) HPFC_MODE=void ;;
    q) HPFC_MODE=demo ;;
    d) HPFC_MODE=debug ;;
    *) usage 4
  esac
done

shift `expr $OPTIND - 1`

# default: interactive

[ "$#" -eq 0 ] && exec hpfc_interactive

# else exec the required command

key=$1
shift

case $key in
  h|hel*) usage 0 ;;
  c|com*) hpfc_compile -k $HPFC_MODE "$@" ;;
  f|ful*) hpfc_compile -k $HPFC_MODE -k full "$@" ;;
  D|deb*) hpfc_compile -k $HPFC_MODE "$@" ;;
  v|val*) hpfc_compile -k validate "$@" ;;
  C|cle*) Delete "$@" ; hpfc_del "$@" ;;
  d|del*) hpfc_delete "$@" ;;
  F|fil*) hpfc_directives < "$@" ;;
  m|mak*) cd `basename $1 .hpfc`.hpfc ; make all ;;
  r|run*) echo 'not implemented' ;;
  p|pvm*) echo "$@" | pvm ; echo ;;
  i|int*) hpfc_interactive ;;
  s|ls*) ls ;;
  pwd*) pwd ;;
  *) usage 2
esac

# that is all
#
