#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Authors:
# - Grégoire Péan <gregoire.pean@hpc-project.com>
# - Ronan Keryell <ronan.keryell@hpc-project.com>
#

'''
Par4All Frontend Script
'''

import string, sys, os, re, optparse
from p4a_util import *
from p4a_processor import *
from p4a_builder import *
from p4a_git import *
from p4a_version import *

import p4a

def main():
    '''The function called when this program is executed by its own'''

    parser = optparse.OptionParser(description = __doc__,
                                   usage = "%prog [options] [files]")

    main_group = optparse.OptionGroup(parser, "General Options")

    main_group.add_option("--project-name", "--project", "-p",
                          metavar = "NAME", default = None,
                          help = "Name for the project (and for the program database). If you do not specify the project, a random name will be used.")

    main_group.add_option("--keep-database", "-k",
                          action = "store_true", default = False,
                          help = "Keep database directory after processing.")
    
    main_group.add_option("--remove-first", "-r",
                          action = "store_true", default = False,
                          help = "Remove existing database directory before processing.")

    main_group.add_option("--verbose", "-v", action = "count",
                          default = get_verbosity(),
                          help = "Run in verbose mode (you can have several -v, such as -vvv which will display the most debugging information).")

    main_group.add_option("--nocolor", action = "store_true", default = False,
                          help = "Disable coloring of terminal output.")

    main_group.add_option("-V", dest = "script_version", action = "store_true", default = False,
                          help = "Display script version and exit.")

    parser.add_option_group(main_group)

    cpp_group = optparse.OptionGroup(parser, "Preprocessing Options")

    cpp_group.add_option("--cpp", metavar = "PREPROCESSOR", default = None,
                         help = "C preprocessor to use (defaults to gcc -E).")

    cpp_group.add_option("-I", dest="include_dirs",
                         action = "append", metavar = "DIR", default = [],
                         help = "Add an include search directory. Same as the compiler -I option. Several are allowed.")

    cpp_group.add_option("-D", dest="defines", action = "append",
                         metavar = "NAME[=VALUE]", default = [],
                         help = "Add a preprocessor define. Same as passing the preprocessor a -D option. Several are allowed.")

    cpp_group.add_option("-U", dest="undefines", action = "append",
                         metavar = "NAME", default = [],
                         help = "Remove a preprocessor define. Same as passing the preprocessor a -U option. Several are allowed.")

    cpp_group.add_option("--cppflags", action = "append",
                         metavar = "FLAGS", default = [],
                         help = "Add additional flags for the C preprocessor. Several are allowed.")

    cpp_group.add_option("--skip-recover-includes", action = "store_true",
                         default = False,
                         help = "By default, try to recover standard #include. To skip this phase, use this option.")

    parser.add_option_group(cpp_group)

    proc_group = optparse.OptionGroup(parser, "Processing Options")

    proc_group.add_option("--accel", "-A", action = "store_true",
                          default = False,
                          help = "Parallelize with output using the Par4All accel run-time that can execute code for various hardware accelerators such as GPU or even OpenMP emulation.")

    proc_group.add_option("--cuda", "-C", action = "store_true",
                          default = False,
                          help = "Enable CUDA generation. Implies --accel.")

    proc_group.add_option("--openmp", "-O", action = "store_true",
                          default = False,
                          help = "Parallelize with OpenMP output. If combined with the --accel option, generate Par4All accel run-time call with OpenMP implementation instead of native OpenMP output. If --cuda is not specified, this option is set by default.")

    proc_group.add_option("--simple", "-S", dest = "simple",
                          action = "store_true", default = False,
                          help = "This cancels --openmp and --cuda and does a simple transformation (no parallelization): simply parse the code and regenerate it.")

    proc_group.add_option("--fine", "-F", action = "store_true",
                          default = False,
                          help = "Use a fine-grained parallelization algorithm instead of a coarse-grained one.")

    proc_group.add_option("--include-modules", metavar = "REGEXP",
                          default = None,
                          help = "Process only the modules which names match the regular expression.")

    proc_group.add_option("--exclude-modules", metavar = "REGEXP",
                          default = None,
                          help = "Exclude the modules matching the regular expression from the parallelization.")

    proc_group.add_option("--noprocess", "-N", action = "store_true",
                          default = False,
                          help = "Bypass all processing (no parallelizing). This voids all processing options. Merely useful for testing compilation/linking option.")

    parser.add_option_group(proc_group)

    compile_group = optparse.OptionGroup(parser, "Compilation Options")

    compile_group.add_option("--output-file", "-o", action = "append",
                             metavar = "FILE", default = [],
                             help = "This enables automatic compilation of binaries. There can be several of them. Output files can be .o, .so, .a files or have no extension in which case an executable will be built.")

    compile_group.add_option("--cc", metavar = "COMPILER", default = None,
                             help = "C compiler to use (defaults to gcc).")

    compile_group.add_option("--cxx", metavar = "COMPILER", default = None,
                             help = "C++ compiler to use (defaults to g++).")

    compile_group.add_option("--nvcc", metavar = "COMPILER", default = None,
                             help = "NVCC compiler to use (defaults to nvcc). Note that the NVCC compiler is used only to transform .cu files into .cpp files, but not compiling the final binary.")

    compile_group.add_option("--fortran", metavar = "COMPILER", default = None,
                             help = "Fortran compiler to use (defaults to gfortran).")

    compile_group.add_option("--ar", metavar = "ARCHIVER", default = None,
                             help = "Archiver to use (defaults to ar).")
    
    compile_group.add_option("--icc", action = "store_true", default = False,
                             help = "Automatically switch to Intel's icc/xild/xiar for --cc/--ld/--ar.")

    compile_group.add_option("--debug", "-g", action = "store_true",
                             default = False,
                             help = "Add debug flags (-g compiler flag).")

    compile_group.add_option("--nofast", "--notfast", action = "store_true",
                             default = False,
                             help = "Do not add optimized compilation flags automatically.")
    
    compile_group.add_option("--no-default-flags", action = "store_true",
                             default = False,
                             help = "Do not add some C flags such as -fPIC, -g, etc. automatically.")
    
    compile_group.add_option("--cflags", action = "append",
                             metavar = "FLAGS", default = [],
                             help = "Specify flags to pass to the C compiler. Several are allowed. Note that --cppflags will be automatically prepended to the actual flags passed to the compiler.")

    compile_group.add_option("--cxxflags", action = "append",
                             metavar = "FLAGS", default = [],
                             help = "Specify flags to pass to the C++ compiler. Several are allowed. By default, C flags (--cflags) are also passed to the C++ compiler.")

    compile_group.add_option("--nvccflags", action = "append",
                             metavar = "FLAGS", default = [],
                             help = "Specify flags to pass to the NVCC compiler. Several are allowed. Note that --cppflags will be automatically prepended to the actual flags passed to the compiler.")

    compile_group.add_option("--fortranflags", action = "append",
                             metavar = "FLAGS", default = [],
                             help = "Specify flags to pass to the Fortran compiler. Several are allowed. Note that --cppflags will be automatically prepended to the actual flags passed to the compiler.")

    compile_group.add_option("--extra", action = "append",
                             metavar = "FILE", default = [],
                             help = "Add additional file for compilation. Several are allowed. They will not be parallelized and will be passed as is.")

    compile_group.add_option("--arch", "-m", metavar = "32|64", default = None,
                         help = "Specify compilation target architecture (defaults to current native architecture).")

    compile_group.add_option("--keep-build-dir", "-K", action = "store_true", default = False,
                         help = "Do not remove build directory after compilation. If an error occurs, it will not be removed anyways.")

    parser.add_option_group(compile_group)

    link_group = optparse.OptionGroup(parser, "Linking Options")

    link_group.add_option("--ld", metavar = "LINKER", default = None,
                          help = "Linker to use (defaults to ld).")

    link_group.add_option("-L", dest = "lib_dirs", action = "append",
                          metavar = "DIR", default = [],
                          help = "Add a library search directory. Same as the linker -L option. Several are allowed.")

    link_group.add_option("-l", dest = "libs", action = "append",
                          metavar = "LIB", default = [],
                          help = "Specify an input library to link against. Same as the linker -l option. Several are allowed.")

    link_group.add_option("--ldflags", action = "append",
                          metavar = "FLAGS", default = [],
                          help = "Specify additional flags to pass to the linker. Several are allowed.")

    link_group.add_option("--extra-obj", action = "append",
                          metavar = "FILE", default = [],
                          help = "Add an additional object file for linking. Several are allowed.")

    parser.add_option_group(link_group)
    
    cmake_group = optparse.OptionGroup(parser, "CMake Options")

    cmake_group.add_option("--cmake", action = "store_true", default = False,
                          help = "If output files are specified (with -o), setting this flag will have p4a produce a CMakeLists.txt file in current directory (or in any other directory specified by --cmake-dir). This CMakeLists.txt file will be suitable for building the project with CMake. NB: setting --make alone will NOT build the project.")
    
    cmake_group.add_option("--cmakeflags", action = "append",
                          metavar = "FLAGS", default = [],
                          help = "Specify additional flags to pass to CMake. Several are allowed.")
    
    cmake_group.add_option("--cmake-dir", metavar = "DIR", default = None,
                          help = "Output/lookup the CMakeLists.txt file in this directory instead of the current working directory.")
    
    cmake_group.add_option("--cmake-gen", action = "store_true", default = False,
                          help = "If output files are specified (with -o), setting this flag will make p4a try to locate a CMakeLists.txt file in current directory (or in any other directory specified by --cmake-dir), and generate Makefiles in a specific directory (--cmake-gen-dir).")
    
    cmake_group.add_option("--cmake-gen-dir", metavar = "DIR", default = None,
                          help = "Generate Makefiles in this directory instead of <project name>.gen by default.")
    
    cmake_group.add_option("--cmake-build", action = "store_true", default = False,
                          help = "Implies --cmake-gen. Generate Makefiles from the found CMakeLists.txt and run 'make' on them.")    

    parser.add_option_group(cmake_group)

    (options, args) = parser.parse_args()

    if options.nocolor:
        p4a_term.disabled = True
    
    set_verbosity(options.verbose)
    
    if options.script_version:
        print(guess_file_revision(__file__))
        return

    p4a.main(options, args)


if __name__ == "__main__":
    try:
        main()
    except p4a_error:
        error(str(sys.exc_info()[1]))
        error("To get verbose output, try passing -v, -vv, or -vvv")
        sys.exit(1)
    except:
        raise
    finally:
        stop_all_spinners() # Make sure no spinner thread is hindering script from exiting.


# Some Emacs stuff:
### Local Variables:
### mode: python
### mode: flyspell
### ispell-local-dictionary: "american"
### tab-width: 4
### End:
