#! /bin/sh

# To compile p4a with my own copy of PIPS, in debug mode, with 4 processes
# and in verbose mode.

# Can take other arguments from the command line.

# Guess that you have a copy of the svn trunks in
# ../../PIPS/git-svn-work and the Polylib in ../polylib
# --pips-conf-opts=--enable-fortran95 
src/simple_tools/p4a_setup.py --polylib-src ../polylib \
    --nlpmake-src ../../PIPS/git-svn-work/nlpmake \
    --newgen-src ../../PIPS/git-svn-work/newgen \
    --linear-src ../../PIPS/git-svn-work/linear \
    --pips-src ../../PIPS/git-svn-work/pips \
    -g -j4 -vvv -z $*
