#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Authors:
# - Grégoire Péan <gregoire.pean@hpc-project.com>
#

'''
Clone the Par4All public Git repository, build it, package it, and optionally publish it.
'''

import string, sys, os, re, optparse, tempfile, shutil, time
from p4a_util import *
from p4a_rc import *
from p4a_git import *
from p4a_version import *
from p4a_opts import *

import p4a_coffee


def main():
    '''The function called when this program is executed by its own'''

    parser = optparse.OptionParser(description = __doc__, usage = "%prog [options]")

    p4a_coffee.add_module_options(parser)

    add_common_options(parser)

    (options, args) = parser.parse_args()

    if process_common_options(options, args):
        p4a_coffee.main(options, args)


if __name__ == "__main__":
    try:
        main()
    except p4a_error:
        error(str(sys.exc_info()[1]))
        if sys.exc_info()[1].code == -2:
            error("Interrupted")
        else:
            error("To get verbose output, try passing -v, -vv, or -vvv")
            if report_enabled():
                send_report_email()
        sys.exit(sys.exc_info()[1].code)
    except:
        raise
    finally:
        stop_all_spinners() # Make sure no spinner thread is hindering script from exiting.


# Some Emacs stuff:
### Local Variables:
### mode: python
### mode: flyspell
### ispell-local-dictionary: "american"
### tab-width: 4
### End:
