#!/bin/sh
# p4a_scpp  - P4A Selective C PreProcessor
# Authors: Serge Guelton <serge.guelton@hpc-project.com>

CPP=${CPP:-cpp}
SED=${SED:-sed}
GREP=${GREP:-grep}
BEAUTIFIER=${BEAUTIFIER:-"indent -linux"}

p4a_guard="// et les gardiens, qui les gardera"
p4a_shield="// En Taro Adun"
p4a_sink_begin="\/\/ My life for Aiur"
p4a_sink_end="\/\/ For Adun!"

p4a_re="p4a.*"
p4a_input=-
P4A_CPPFLAGS=-I${P4A_ACCEL_DIR:-.}

# process arguments
for arg in $* ; do
	case $arg in
		-h|--help)
	cat << EOF
p4a_scpp - P4A Selective C PreProcessor
usage: p4a_scpp [-h|--help] [--no-beautifier] [--cuda|--opencl|--openmp] [cpp flags] [--include-re=regexp] [input_file=stdin]
sample: p4a_scpp -DP4A_ACCEL_OPENMP hello_world.p4a.c
sample: p4a_scpp -DP4A_ACCEL_OPENMP hello_world.p4a.c
        p4a_scpp --no-beautifier -DNDEBUG --include-re=stdio\\\\.h /usr/include/stdlib.h | indent -linux
EOF
			exit 0
			;;
		--no-beautifier)
			BEAUTIFIER=cat
			;;
		--include-re=*)
			p4a_re="`echo "$arg"| cut -c 14-`"
			;;
		--cuda|--opencl|--openmp)
			# Transform for example --opencl into -DP4A_ACCEL_OPENCL:
			P4A_CPPFLAGS="$P4A_CPPFLAGS -DP4A_ACCEL_`echo $arg | sed s/--// | tr 'a-z' 'A-Z'`"
			;;
		-*)
			P4A_CPPFLAGS="$P4A_CPPFLAGS $arg"
			;;
		*)
			p4a_input=$arg
			;;
	esac
done

# check the include regular expression
if test -z "$p4a_re" ; then
	echo "missing include regular exception"
	/bin/sh $0 --help
	exit 1
fi

# guard all # command , then remove the one we are interested in, process them and remove remaining guards.
$SED -r -e "s%(\#\s*((define)|(line)|(pragma)|(if)|(else)|(endif)|(include)))%$p4a_guard \1%g" "$p4a_input" |\
	$SED -r -e "s%$p4a_guard (\#\s*include\s*[\"<]$p4a_re[\">])%$p4a_shield\1\n$p4a_sink_begin\n\1\n$p4a_sink_end%g" | \
	$CPP -CC $P4A_CPPFLAGS |\
	$SED -r -e "s%$p4a_guard (\#\s*((define)|(line)|(pragma)|(if)|(else)|(endif)|(include)))%\1%g" -e "/$p4a_sink_begin/,/$p4a_sink_end/ d" -e "s,^$p4a_shield,,g" |\
	$BEAUTIFIER |\
	$GREP -v "#[0-9][0-9]*"

