#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Authors:
# - Grégoire Péan <gregoire.pean@hpc-project.com>
#

'''
Par4All packing script: allows you to create .deb or .tar.gz packages of Par4all.
'''

import string, sys, os, re, optparse, tempfile, shutil, time, traceback
from p4a_util import *
from p4a_rc import *
from p4a_git import *
from p4a_version import *
from p4a_opts import *

import p4a_pack


def main():
    '''The function called when this program is executed by its own'''

    parser = optparse.OptionParser(description = __doc__, 
        usage = "%prog <--deb|--tgz|-stgz> [--version=0.1] [--append-date] [--dir=/current/install/dir] [--prefix=/final/install/dir] [--publish] [other options] [optional additional files to publish]; run %prog --help for options")

    p4a_pack.add_module_options(parser)

    add_common_options(parser)

    (options, args) = parser.parse_args()

    if process_common_options(options, args):
        p4a_pack.main(options, args)


if __name__ == "__main__":
    try:
        main()
    except p4a_error:
        (t, e, tb) = sys.exc_info()
        error(str(e))
        debug("".join(traceback.format_exception(t, e, tb)))
        if e.code == -2:
            error("Interrupted")
        else:
            suggest_more_verbosity()
            send_report_email_if_enabled()
        sys.exit(e.code)
    except EnvironmentError: # IOError, OSError.
        (t, e, tb) = sys.exc_info()
        error(str(e))
        debug("".join(traceback.format_exception(t, e, tb)))
        suggest_more_verbosity()
        send_report_email_if_enabled()
        sys.exit(e.errno)
    except KeyboardInterrupt:
        error("Interrupted")
        sys.exit(-2)
    except SystemExit:
        raise
    except: # All other exceptions.
        (t, e, tb) = sys.exc_info()
        error("Unhandled " + e.__class__.__name__ + ": " + str(e))
        error("".join(traceback.format_exception(t, e, tb)))
        suggest_more_verbosity()
        send_report_email_if_enabled()
        sys.exit(255)


# Some Emacs stuff:
### Local Variables:
### mode: python
### mode: flyspell
### ispell-local-dictionary: "american"
### tab-width: 4
### End:
