#!/bin/sh

echo "PRETTYPRINT_BLOCK_IF_ONLY TRUE" > properties.rc
if Pips -f tested_file -w tested_name -m tested_name -s mustreg \
	-s prcr -b PF >&2
then
	echo "--- Regions for TESTED_NAME" 
	Display -l regi
	exit_status=0
else
	exit_status=1
fi
Delete tested_name
rm properties.rc
exit $exit_status
