      subroutine dummy

c     Check translation mechanism when variable are not visible in the
c     current procedure.

c     Check that information generated by tests in transformer is
c     linked to old or new values

      common /foo/i,j,ndummy(2), m, n

      call bar

      print *, i, j, m, m

      end

      subroutine bar
      common /foo/i,j,k,l,m,n
      if(i.gt.j) then
         i = i + 1
         j = j + 2
         k = k + 3
         l = l + 4
      else
         stop
      endif

      if(m.eq.n) then
         print *, m-n
      else
         stop
      endif

      end
