C     Information generated by the test was not exploited 

      subroutine simple(n)
      integer n, i, j
      real a(100), b(100)
      real m
      m = sqrt(0.37*n)
      do i = 1, n
         if (j .lt. 5) then
            a(i) = b(i)*3+5
         endif
      enddo
      end
