#! /bin/sh
#

PDIR="$PIPS_ROOT/Validation/Wp65"

[ -r "model.rc" ] && { echo File model.rc already exists >&2 ; exit 1; }

cp $PDIR/tested_file.rc model.rc
Init -d -f $PDIR/tested_file.f tested_file >&2
[ -f $PDIR/tested_file.options ] && . $PDIR/tested_file.options >&2
Pips -m TESTED_FILE -p WP65 -w tested_file >&2
status=$?
cat \
  tested_file.database/TESTED_FILE/TESTED_FILE.wp65 \
  tested_file.database/TESTED_FILE/TESTED_FILE.bank
rm model.rc
Delete tested_file
exit $status

