#! /bin/sh
#
# $RCSfile: make-pips,v $ version $Revision$
# $Date: 1996/07/11 13:51:53 $, 
#
# (c) Fabien COELHO July 1996
#
# changed a lot. it happens that -r does what you expect from it...
# for building pips on installation, do make-pips -b
# type '$RCSfile: make-pips,v $ -h' for help.

umask 2
script=`basename $0`
unset sides parts commands dirs libs pips newgen linear msg
verb=':'
job=$PIPS_MAKE

#
# misc utils

verbose()
{
    echo "$script: $@" >&2
}

error()
{
    ret=$1
    shift
    verbose "$@"
    exit $ret
}

#
# check environment

[ "$NEWGEN_DIR" ] || error 4 "newgen environment not set!"
[ -d "$NEWGEN_DIR" ] || error 5 "invalid newgen environment!"

[ "$LINEAR_DIR" ] || error 6 "linear environment not set!"
[ -d "$LINEAR_DIR" ] || error 7 "invalid linear environment!"

[ "$PIPS_DIR" ]   || error 8 "pips environment not set!"
[ -d "$PIPS_DIR" ] || error 9 "invalid pips environment!"

#
# get options

usage()
{
    ret=$1
    shift
    cat >&2 <<-EOF
	$script (version $Revision$): $@
	usage: $script [options] [targets]
	  -h: print this help and exit
	  -v: verbose
	  -N: do nothing, print what would be done
	 possible softs
	  -p: Pips (default)
	  -l: Linear
	  -n: Newgen
	 possible sides
	  -P: Production (default)
	  -R: Release
	  -D: Development
	 misc
	  -b: build (Production, Pips+Linear+Newgen, recompile)
	  -r: recompile (Production, Pips, clean+recompile)
	  -d dir: specifies a directory
	  -o file: log file to report to (default is /dev/tty)
	  -m msg: message
	 targets: make targets to require (e.g. clean all recompile diff...)
EOF
    exit $ret
}

while getopts hvNRPDplnbd:o:m: OPT
do
    case $OPT in
	h) usage 0 "here is some help!" ;;
	v) verb=verbose ;;
	N) job="echo $PIPS_MAKE" ;;
	R) sides="$sides RELEASEDIR"; msg="R${msg}" ;;
	P) sides="$sides SRCDIR"; msg="P${msg}" ;;
	D) sides="$sides DEVEDIR"; msg="D${msg}" ;;
	p) parts="$parts PIPS" ; pips='1' ;;
	l) parts="$parts LINEAR" ; linear='1' ;;
	n) parts="$parts NEWGEN" ; newgen='1' ;;
	b) commands="$commands recompile" ;
	   parts="NEWGEN LINEAR PIPS" ;
	   sides="SRCDIR" ;
	   pips='1' ; linear='1' ; newgen='1' ;;
	r) commands="$commands clean recompile" ;
	   parts="PIPS" ;
	   sides="SRCDIR" ;
	   pips='1' ; linear='1' ; newgen='1' ;;
	o) commands="FWD_REPORT=$OPTARG $commands" ;;
	m) msg="$msg[$OPTARG]" ;;
	d) dirs="$dirs $OPTARG" ;;
	*) usage 2 "invalid option" ;;
    esac
done
shift `expr $OPTIND - 1`

commands="$@ $commands"

#
# defaults:

[ "$sides" ] || { sides="SRCDIR" ; msg="P$msg" ; }
[ "$parts" ] || { parts="PIPS" ; pips='1' ; }

[ "$pips" ] && 
{ libs="$libs Lib Passes Scripts Runtime $PIPS_ORDERED_LIBS"; msg="Pips:$msg";}

[ "$linear" ] && { libs="$libs $LINEAR_ORDERED_LIBS"; msg="Linear:$msg";}
[ "$newgen" ] && { libs="$libs $NEWGEN_ORDERED_LIBS"; msg="Newgen:$msg";}

[ "$libs" ]  && libs="FWD_DIRS=\"$libs\""

#
# build the directories to visit

$verb "sides=$sides"
$verb "parts=$parts"

for p in $parts ;
do 
    for s in $sides ;
    do
	dirs="$dirs "`eval echo \$"${p}_${s}"`
    done
done

#
# do the job here

$verb "dirs=$dirs"
$verb "msg=$msg"
$verb "commands=$commands"

for d in $dirs
do
    $verb "dealing with $d"
    test -d $d || error 3 "no $d directory!" 
    $job -C $d $libs FWD_MSG="$msg" $commands
done

$verb "done"

# end of $RCSfile: make-pips,v $
#
