# $Id$

INSTALL_UTL = 	make-pips \
		make_release \
		make_pips_release \
		install_pips

INSTALL_DOC =	install.README \
		install.INSTALL

# common stuff
ifdef PIPS_ROOT
ROOT    = $(PIPS_ROOT)
else
ROOT    = ../../..
endif

#PROJECT = pips
include $(ROOT)/makes/main.mk
