int main(int toto) {
   // Generated by Pass VARIABLE_REPLICATION
   int __dpvar__i_0, __dpvar__i_1, __dpvar__i_2, __dpvar__i_3;
   // Generated by Pass VARIABLE_REPLICATION
   int __dpvar__a_0[10], __dpvar__a_1[10], __dpvar__a_2[10], __dpvar__a_3[10];
   // Generated by Pass VARIABLE_REPLICATION
   int __dpvar__r_0, __dpvar__r_1, __dpvar__r_2, __dpvar__r_3;
   // Generated 
   int __return__value;
#pragma distributed on_cluster=0
   {
   __dpvar__i_0 = 0;
   __dpvar__i_0++;
   }
#pragma distributed on_cluster=1
   {
   __dpvar__i_1 = 0;
   __dpvar__i_1++;
#pragma distributed on_cluster=2
   {
   __dpvar__i_2 = 0;
   __dpvar__i_2++;
   }
#pragma distributed on_cluster=3
   {
   __dpvar__i_3 = 0;
   __dpvar__i_3++;
   }

#pragma distributed on_cluster=0
   {
      __dpvar__a_0[__dpvar__i_0] = 42;
      __dpvar__a_1[__dpvar__i_0] = __dpvar__a_0[__dpvar__i_0];
      __dpvar__a_2[__dpvar__i_0] = __dpvar__a_0[__dpvar__i_0];
      __dpvar__a_3[__dpvar__i_0] = __dpvar__a_0[__dpvar__i_0];
      __dpvar__i_0++;
      __dpvar__i_1 = __dpvar__i_0;
      __dpvar__i_2 = __dpvar__i_0;
      __dpvar__i_3 = __dpvar__i_0;
   }
#pragma distributed on_cluster=1
   {
      __dpvar__i_1--;
      __dpvar__i_0 = __dpvar__i_1;
      __dpvar__i_2 = __dpvar__i_1;
      __dpvar__i_3 = __dpvar__i_1;
      __dpvar__r_1 = __dpvar__a_1[__dpvar__i_1]+__dpvar__i_1-1;
      __dpvar__r_0 = __dpvar__r_1;
      __dpvar__r_2 = __dpvar__r_1;
      __dpvar__r_3 = __dpvar__r_1;
   }
   
#pragma distributed on_cluster=0
   __return__value = __dpvar__r_0;
   //i=1, a[1]=42, r=42
   return __return__value;
}
