/*
Declaration des handlers des intrinseques lies a la runtime de STEP pour le prettyprinter
Fichier inclus par : src/Libs/ri-utils/prettyprint.c

Par defaut les appels aux intrinseques sont affiches sans "CALL" or dans le cas de subroutine il est necessaire.
*/

  {DIR_CALL,words_call_intrinsic,0},
  {RT_STEP_get_myloopslice,words_call_intrinsic,0},
  {RT_STEP_get_i_low,words_call_intrinsic,0},
  {RT_STEP_get_i_up,words_call_intrinsic,0},
  {RT_STEP_Init_Fortran_Order,words_call_intrinsic,0},
  {RT_STEP_Init_C_Order,words_call_intrinsic,0},
  {RT_STEP_Critical_Spawn,words_call_intrinsic,0},
  {RT_STEP_Finalize,words_call_intrinsic,0},
  {RT_STEP_Barrier,words_call_intrinsic,0},
  {RT_STEP_Get_Commsize,words_call_intrinsic,0},
  {RT_STEP_Get_rank,words_call_intrinsic,0},
  {RT_STEP_Get_thread_num,words_call_intrinsic,0},
  {RT_STEP_ComputeLoopSlices,words_call_intrinsic,0},
  {RT_STEP_GetLoopBounds,words_call_intrinsic,0},
  /*  {RT_STEP_SizeRegion,words_call_intrinsic,0}, c'est une function ! */
  {RT_STEP_WaitAll,words_call_intrinsic,0},
  {RT_STEP_Begin,words_call_intrinsic,0},
  {RT_STEP_End,words_call_intrinsic,0},
  {RT_STEP_Request,words_call_intrinsic,0},
  {RT_STEP_Release,words_call_intrinsic,0},
  {RT_STEP_Get_Nextprocess,words_call_intrinsic,0},
  {RT_STEP_InitReduction,words_call_intrinsic,0},
  {RT_STEP_Reduction,words_call_intrinsic,0},
  {RT_STEP_Critical_Check_n_threads, words_call_intrinsic,0}, 	
  {RT_STEP_MasterToAllScalar,words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion,words_call_intrinsic,0},
  {RT_STEP_AllToMasterRegion,words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar,words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion,words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar,words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion,words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateScalar,words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateRegion,words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion,words_call_intrinsic,0},
  {RT_STEP_InitInterlaced,words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge,words_call_intrinsic,0},

  {RT_STEP_InitArrayRegions,words_call_intrinsic,0},
  {RT_STEP_Set_SendRegions,words_call_intrinsic,0},
  {RT_STEP_Set_InterlacedSendRegions,words_call_intrinsic,0},
  {RT_STEP_Set_ReductionSendRegions,words_call_intrinsic,0},
  {RT_STEP_Set_RecvRegions,words_call_intrinsic,0},
  {RT_STEP_AllToAll_Full,words_call_intrinsic,0},
  {RT_STEP_AllToAll_FullInterlaced,words_call_intrinsic,0},
  {RT_STEP_AllToAll_Partial,words_call_intrinsic,0},
  {RT_STEP_AllToAll_PartialInterlaced,words_call_intrinsic,0},

  {RT_STEP_InitReduction "_I1",words_call_intrinsic,0},
  {RT_STEP_Reduction "_I1",words_call_intrinsic,0},
  {RT_STEP_Critical_Check_n_threads "_I1",words_call_intrinsic,0}, 	
  {RT_STEP_MasterToAllScalar "_I1",words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion "_I1",words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar "_I1",words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion "_I1",words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar "_I1",words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion "_I1",words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateScalar "_I1",words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateRegion "_I1",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion "_I1",words_call_intrinsic,0},
  {RT_STEP_InitInterlaced "_I1",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge "_I1",words_call_intrinsic,0},
  {RT_STEP_InitReduction "_I2",words_call_intrinsic,0},
  {RT_STEP_Reduction "_I2",words_call_intrinsic,0},
  {RT_STEP_Critical_Check_n_threads "_I2",words_call_intrinsic,0}, 	
  {RT_STEP_MasterToAllScalar "_I2",words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion "_I2",words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar "_I2",words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion "_I2",words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar "_I2",words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion "_I2",words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateScalar "_I2",words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateRegion "_I2",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion "_I2",words_call_intrinsic,0},
  {RT_STEP_InitInterlaced "_I2",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge "_I2",words_call_intrinsic,0},
  {RT_STEP_InitReduction "_I4",words_call_intrinsic,0},
  {RT_STEP_Reduction "_I4",words_call_intrinsic,0},
  {RT_STEP_Critical_Check_n_threads "_I4",words_call_intrinsic,0}, 	
  {RT_STEP_MasterToAllScalar "_I4",words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion "_I4",words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar "_I4",words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion "_I4",words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar "_I4",words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion "_I4",words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateScalar "_I4",words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateRegion "_I4",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion "_I4",words_call_intrinsic,0},
  {RT_STEP_InitInterlaced "_I4",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge "_I4",words_call_intrinsic,0},
  {RT_STEP_InitReduction "_I8",words_call_intrinsic,0},
  {RT_STEP_Reduction "_I8",words_call_intrinsic,0},
  {RT_STEP_Critical_Check_n_threads "_I8",words_call_intrinsic,0}, 	
  {RT_STEP_MasterToAllScalar "_I8",words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion "_I8",words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar "_I8",words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion "_I8",words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar "_I8",words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion "_I8",words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateScalar "_I8",words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateRegion "_I8",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion "_I8",words_call_intrinsic,0},
  {RT_STEP_InitInterlaced "_I8",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge "_I8",words_call_intrinsic,0},
  {RT_STEP_InitReduction "_R4",words_call_intrinsic,0},
  {RT_STEP_Reduction "_R4",words_call_intrinsic,0},
  {RT_STEP_Critical_Check_n_threads "_R4",words_call_intrinsic,0}, 	
  {RT_STEP_MasterToAllScalar "_R4",words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion "_R4",words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar "_R4",words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion "_R4",words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar "_R4",words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion "_R4",words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateScalar "_R4",words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateRegion "_R4",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion "_R4",words_call_intrinsic,0},
  {RT_STEP_InitInterlaced "_R4",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge "_R4",words_call_intrinsic,0},
  {RT_STEP_InitReduction "_R8",words_call_intrinsic,0},
  {RT_STEP_Reduction "_R8",words_call_intrinsic,0},
  {RT_STEP_Critical_Check_n_threads "_R8",words_call_intrinsic,0}, 	
  {RT_STEP_MasterToAllScalar "_R8",words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion "_R8",words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar "_R8",words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion "_R8",words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar "_R8",words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion "_R8",words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateScalar "_R8",words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateRegion "_R8",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion "_R8",words_call_intrinsic,0},
  {RT_STEP_InitInterlaced "_R8",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge "_R8",words_call_intrinsic,0},
  {RT_STEP_InitReduction "_C8",words_call_intrinsic,0},
  {RT_STEP_Reduction "_C8",words_call_intrinsic,0},
  {RT_STEP_Critical_Check_n_threads "_C8",words_call_intrinsic,0}, 	
  {RT_STEP_MasterToAllScalar "_C8",words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion "_C8",words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar "_C8",words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion "_C8",words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar "_C8",words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion "_C8",words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateScalar "_C8",words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateRegion "_C8",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion "_C8",words_call_intrinsic,0},
  {RT_STEP_InitInterlaced "_C8",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge "_C8",words_call_intrinsic,0},
  {RT_STEP_InitReduction "_C16",words_call_intrinsic,0},
  {RT_STEP_Reduction "_C16",words_call_intrinsic,0},
  {RT_STEP_Critical_Check_n_threads "_C16",words_call_intrinsic,0}, 	
  {RT_STEP_MasterToAllScalar "_C16",words_call_intrinsic,0},
  {RT_STEP_MasterToAllRegion "_C16",words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateScalar "_C16",words_call_intrinsic,0},
  {RT_STEP_Critical_set_CurrentUptodateRegion "_C16",words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateScalar "_C16",words_call_intrinsic,0},
  {RT_STEP_Critical_get_CurrentUptodateRegion "_C16",words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateScalar "_C16",words_call_intrinsic,0},
  {RT_STEP_Critical_FinalUptodateRegion "_C16",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion "_C16",words_call_intrinsic,0},
  {RT_STEP_InitInterlaced "_C16",words_call_intrinsic,0},
  {RT_STEP_AlltoAllRegion_Merge "_C16",words_call_intrinsic,0},
