#
# $Id: makefile,v 1.1 2002/10/14 15:03:25 olaru Exp $
#

ROOT  = ..

# Subdirectories
SUBDIRS = \
	arith \
	kernel \
	ehrhart

# C files in this directory
SRCS = \
	count.c 

# oldpolytest.c

# Include the shared compilation rules
include $(ROOT)/vars.mk
include $(ROOT)/default_functions.mk

