#!/bin/sh
if [ -z $@ ]; then
	echo "Usage: $0 <cmd>"
	exit
fi
strace -f -o /tmp/stracelog $@ >/dev/null 2>&1
for x in `dpkg -S $(grep open /tmp/stracelog | perl -pe 's!.* open\(\"([^\"]*).*!$1!' | grep "^/" | sort | uniq | grep -v "^\(/tmp\|/dev\|/proc\)" ) 2>/dev/null | cut -f1 -d":"| sort | uniq`; do 
	echo -n "$x (>=" `dpkg -s $x|grep ^Version|cut -f2 -d":"` "), ";
done
echo
