#! /bin/bash

# Script to deal with Par4All documentation

# Subdirectory where there is some documentation to build or publish:
# doc/organization and doc/simple_tools/p4a_article are deprecated now...
doc_dirs="doc/developer_guide doc/installation_guide doc/p4a_coding_rules doc/simple_tools/p4a_article doc/simple_tools/p4a_slides doc/user_guide src/p4a_accel"



# What to do:
make_target=""

script=${0/*\//}
# verb level 'message to be shown...'
verb=0

# Display help
function usage()
{
  local status=$1 msg=$2
  if [[ $msg ]]
  then
    echo -e "message: $msg\n" >&2
  fi
  if [[ $status == 0 || $status == 1 ]]
  then
    echo -e \
      "$script [options] ...\n" \
      "Build and install the Par4All documentation.\n" \
      "\$P4A_ROOT has to point to the Par4All development directory.\n" \
	"options (displayed in a logical sequential order to apply):\n" \
	"  -h|--help: display the usual help message\n" \
	"  -v|--verbose: be verbose (repeat for more, over 2 is debug)\n" \
	"  --clean: remove previously compiled documentation\n" \
	"  --make: build the documentation\n" \
	"  --publish: publish the documentation on the WWW server"
  fi
  exit ${status:-1}
}

if [[ -z $P4A_ROOT ]]; then
    echo "You need to have \$P4A_ROOT defined to the Par4All top-level directory
"
    exit
fi

if [ $# == 0 ]; then
    usage 1 "You should specify an option"
fi

# Get options:
while [ "$1" ] ; do
  opt=$1
  shift
  case $opt in
      -h|--help) usage 0 ;;
      -v|--verbose) let verb++ ;;
      --clean) make_target+="clean ";;
      --make) make_target+="default "; set -o errexit;;
      --publish) make_target+="publish ";;
      *) usage 1 "unexpected option: $opt"
  esac
done

if (( $verb >= 1)) ; then
    # Put shell tracing on:
    set -vx
fi


for d in $doc_dirs; do
    ad=$P4A_ROOT/$d
    local_make_target=$make_target
    echo "Dealing with $ad..."
    if [ $d == 'src/p4a_accel' ]; then
	# Deal with special case of Doxygen generation:
	local_make_target=`echo $local_make_target | sed -e s/default/doxygen/ -e s/publish/doxygen-publish/`
    fi
    ( cd $ad; make $local_make_target )
done
