#!/bin/bash -x

set -e

DIR=/tmp/p4apub$$
REVISION=0.2

cleanup()
{
	echo "Removing $DIR"
	rm -rf $DIR
}

trap cleanup INT

mkdir -p $DIR
cd $DIR
git clone git://git.hpc-project.com/par4all p4a
cd $DIR/p4a
git checkout -b p4a remotes/origin/p4a
#cd $DIR
#cp -a p4a p4a-own
#cd $DIR/p4a-own
#git checkout -b p4a-own remotes/origin/p4a-own
#src/simple_tools/p4a_setup --clean --rebuild --packages-dir=$DIR/p4a/packages -v
src/simple_tools/p4a_setup --clean --rebuild -j4 -v
#src/simple_tools/p4a_pack --deb --tgz --dir /usr/local/par4all --revision $REVISION --nightly --publish -v
src/simple_tools/p4a_pack --deb --tgz --dir /usr/local/par4all --revision $REVISION --nightly --publish -v
#cd $DIR/p4a
src/simple_tools/p4a_pack --stgz --revision $REVISION --nightly --publish -v

cleanup


