#! /bin/bash -vx
# Test case of the script to build the infrastructure up:

# Stop on error:
set -o errexit

ALL_MODULES="linear polylib"

# Get a clean repository:
git init p3
cd p3

# Get stuff from the old one:
git remote add par4all ../par4all
# Create the tracking branches:
git pull par4all own:p4a-own
git pull par4all own-0.1-alpha:p4a-own-0.1-alpha
git pull par4all master
# Point to the top of the repository:
git branch initial ecd50e4a9fa1e04a9f07d6f5f892b8f7ed4a21a9

# Import the branches of the packages:
../par4all/src/dev/p4a_import_external_gits

# Create the branch to integrate the packages:
git branch p4a-packages initial
git checkout p4a-packages

# Merge into it the packages:
for i in $ALL_MODULES; do
    git merge p4a-$i
done
# This will be also the p4a-packages-0.1-alpha branch:
git branch p4a-packages-0.1-alpha

# Create the branch to integrate Par4All:
git branch p4a initial
git checkout p4a
git merge p4a-packages
git merge p4a-own-0.1-alpha
# This will be also the p4a-0.1-alpha branch:
git branch p4a-0.1-alpha

# Get the last package versions:
p4a_git -p
p4a_git -m

# Integrate them in the package branch:
git checkout p4a-packages

for i in $ALL_MODULES; do
    git branch p4a-0.2-alpha-$i p4a-$i
    git merge p4a-0.2-alpha-$i
done
# This will be also the p4a-packages-0.2-alpha branch:
git branch p4a-packages-0.2-alpha

# Integrate all:
git checkout p4a
git merge p4a-own
git merge p4a-packages
# This will be also the p4a-0.2-alpha branch:
git branch p4a-0.2-alpha

# Have a look to the world creation:
gitk&
exit

# Some wild tests:

# Import
git branch -l linear initial
git checkout linear
git remote add CRI/linear ../CRI-git-svn/linear
git fetch CRI/linear
git read-tree --prefix=packages/PIPS/linear -u 920bf79c5c2b723af34320cff6bee5954b76fdb8
git commit -m "melange"
git merge --strategy=ours 920bf79c5c2b723af34320cff6bee5954b76fdb8
git checkout initial
git checkout -b p4a
git merge linear
git merge own
git checkout -b CRI-linear remotes/CRI/linear/master
git checkout linear
#git pull --log --strategy=subtree CRI/linear master
git merge --log --strategy=subtree CRI-linear
gitk&

exit

git checkout initial
git checkout -b p4a
git merge linear
git merge own
