#! /bin/bash -vx

# Add remotes for git instances:
# - the SVN PIPS-related repositories from Mines ParisTech/CRI
# - the PolyLib library from Strasbourg University/ICPS

# Where to get the git-svn instances from:
GIT_SVN_PIPS_DIR=/home/keryell/projets/Wild_Systems/Par4All/CRI-git-svn

# List of PIPS repositories, sorted in appearance of commit order into the
# target git, so put the most important at end (well very subjective :-)
# ):
PIPS_SVN_REPOSITORIES="validation linear newgen nlpmake pips"

if [[ -z $P4A_ROOT ]]; then
    echo "You need to have \$P4A_ROOT defined to the Par4All top-level directory"
    exit
fi

cd $P4A_ROOT

COMMIT_MESSAGE_FILE=`mktemp`
#echo $COMMIT_MESSAGE_FILE

# Create the remote/CRI/<repository>
import_git() {
    # Get the function parameters:
    REMOTE_NAME=$1
    REMOTE_GIT_URL=$2
    TARGET_LOCAL_DIR=$3

    echo Add the git svn as remote git repository:
    git remote add $REMOTE_NAME $REMOTE_GIT_URL

    echo Fetch the history:
    git fetch $REMOTE_NAME

    echo Extract a copy of the files of the remote repository into the local
    echo repository at packages/PIPS, merge it and update the files in the work
    echo tree:
    git read-tree --prefix=$TARGET_LOCAL_DIR -u $REMOTE_NAME/master

    # Build the merging message:
    echo "Merging from git-svn remotes/$REMOTE_NAME into $TARGET_LOCAL_DIR that is:" > $COMMIT_MESSAGE_FILE

    # Get the last commit message from the remote to branch from:
    git log -n 1 remotes/$REMOTE_NAME/master >> $COMMIT_MESSAGE_FILE

    # Commit with the built merging message:
    git commit --file=$COMMIT_MESSAGE_FILE

    echo Connect the SVN history to this one by fetching it and merging it with
    echo "the our strategy (since what we want is what we've just built up above"
    echo into packages/PIPS and not at the top level as each individual svn
    echo "repository):"
    git pull -s ours $REMOTE_NAME master

    rm $COMMIT_MESSAGE_FILE
}


# Create the remote/CRI/<repository> from <repository> given as parameter:
import_PIPS_git_svn() {
    # Import from $GIT_SVN_PIPS_DIR/<repository> URL as remote name
    # CRI/<repository> into packages/PIPS/<repository> local directory
	# Put the import and merge in a specific branch
	git checkout master
	git checkout -b $1
    import_git CRI/$1 $GIT_SVN_PIPS_DIR/$1 packages/PIPS/$1
	# Revert to main branch
	git checkout master
}

### To import a branch from PIPS :
# import_git CRI/pips-gfc ../CRI-git-svn/roosz-pips-gfc packages/pips-gfc/gcc/fortran
# exit

# Add the PIPS git svn repositories to Par4All:
for i in $PIPS_SVN_REPOSITORIES; do
    import_PIPS_git_svn $i
done

# http://icps.u-strasbg.fr/polylib
# Create a branch pointing to the polylib import:
git checkout master
git checkout -b polylib
# Add the PolyLib git repository to Par4All in the packages/polylib
# directory as the polylib remote:
import_git polylib git://repo.or.cz/polylib.git packages/polylib
# Revert to main branch
git checkout master


# There was a SVN reorganization of the CRI nlpmake repository to
# introduce branches, so put things in the correct order:
git checkout nlpmake
git mv packages/PIPS/nlpmake/trunk/makes packages/PIPS/nlpmake/makes
git rm -r packages/PIPS/nlpmake/{branches,tags}
git commit --message="There was a SVN reorganization of the CRI nlpmake repository
around revision 747-750 to introduce branches,
so put the makes directory at the top-level back"
# Since git do not track directories and trunk is now empty, use a simple
# directory deletion:
rm -rf packages/PIPS/nlpmake/{branches,tags,trunk}
git checkout master

echo 'Do not forget to use "merge -s subtree" when getting new CRI stuff later'
echo "For example you can get the last upstream version with:"
for i in $SVN_REPOSITORIES; do
    echo "    git fetch CRI/$i"
    echo "    git merge -s subtree CRI/$i/master"
done
echo "    git fetch polylib"
echo "    git merge -s subtree polylib/master"


#%%% Local Variables:
#%%% mode: text
#%%% ispell-local-dictionary: "american"
#%%% End:
