#! /bin/bash

# Inspired from setup_pips.sh from Fabien Coelho and get-pips4u.sh from
# Sebastien Varrette <Sebastien.Varrette@uni.lu> and Serge Guelton
# <Serge.Guelton@telecom-bretagne.eu>
#
# Ronan.Keryell@hpc-project.com

# The P4A_MAKE_OPTS environment variable can be used to pass options to
# make, such as --jobs=8

# Stop on error, since going on after errors may lead to havoc
set -o errexit

default_compilation_targets="autoreconf configure install"
# Display help
function usage()
{
  local status=$1 msg=$2
  if [[ $msg ]]
  then
    echo -e "message: $msg\n" >&2
  fi
  if [[ $status == 0 || $status == 1 ]]
  then
    echo -e \
      "$script [options] ...\n" \
	"options (displayed in a logical sequential order to apply):\n" \
	"  To speed up installation, you can skip already installed stuff:\n" \
	"  --skip-polylib: skip the PolyLib installation\n" \
	"  --skip-newgen: skip the NewGen installation\n" \
	"  --skip-linear: skip the Linear installation\n" \
	"  --skip-pips: skip the PIPS installation\n" \
	"  -v|--verbose: be verbose\n" \
	"  -h|--help: display this usage :-)" \
        "  [compilation targets]" \
        "By default: $default_compilation_targets"
  fi
  exit ${status:-1}
}

# Get options:
while [ "$1" ] ; do
  opt=$1
  case $opt in
      --) shift ; break ;; # end of option
      -*) shift ;; # one option, processed by next "case"
      *) break ;; # must be an argument, stop option processing...
  esac

  case $opt in
      -h|--help) usage 0 ;;
      -v|--verbose) verb=1 ;;
      # Could be clever, but KISS :-)
      # Not that this could be environment variable to skip these
      # compilations too:
      --skip-polylib) P4A_SKIP_POLYLIB=1 ;;
      --skip-newgen) P4A_SKIP_NEWGEN=1 ;;
      --skip-linear) P4A_SKIP_LINEAR=1 ;;
      --skip-pips) P4A_SKIP_PIPS=1 ;;
      # error
      *) usage 1 "unexpected option: $opt"
  esac
done

if [[ -n $verb ]]; then
    # Put shell tracing on:
    set -vx
fi

if [[ -z $P4A_ROOT ]]; then
    echo "You need to have \$P4A_ROOT defined to the Par4All top-level directory"
    exit
fi

# Get the compilation targets:
compilation_targets=$@
if [[ -z $compilation_targets ]]; then
    compilation_targets=$default_compilation_targets
    echo "Building default targets: $default_compilation_targets"
fi

# Global things, whatever the targets are.
# Some factoring should be done somedays...

# Where everything is built:
P4A_BUILD=$P4A_ROOT/build
# Where things are installed
P4A_INSTALL_PREFIX=$P4A_ROOT/run

P4A_ETC=$P4A_INSTALL_PREFIX/etc
mkdir -p $P4A_ETC

if test -z "$INSTALL_PREFIX" ; then
    # install prefix passed by --prefix to the configure script:
    INSTALL_PREFIX=$P4A_INSTALL_PREFIX
fi
mkdir -p $INSTALL_PREFIX

# Default flags for the configure script:
PIPS_CONFIGURE_COMMON_FLAGS=" --disable-static"

# Where to find PIPS/pips if not specified:
if [[ -z $P4A_PIPS_SRC ]]; then
    P4A_PIPS_SRC=$P4A_ROOT/packages/PIPS/pips
fi

# Where to find PIPS/nlpmake if not specified:
if [[ -z $P4A_NLPMAKE_SRC ]]; then
    P4A_NLPMAKE_SRC=$P4A_ROOT/packages/PIPS/nlpmake
fi


cd $P4A_ROOT

echo Installing Par4All scripts...
# Install Par4All scripts:
mkdir -p $P4A_INSTALL_PREFIX/bin
cp $P4A_ROOT/src/dev/{p4a_git,p4a_setup,p4a_valgrind} $P4A_INSTALL_PREFIX/bin
cp $P4A_ROOT/src/dev/p4a_git_lib.bash $P4A_ETC
cp $P4A_ROOT/src/postprocessor/p4a_recover_includes $P4A_INSTALL_PREFIX/bin
cp $P4A_ROOT/src/validation/{p4a_validate,p4a_validation} $P4A_INSTALL_PREFIX/bin

# The config files to source later:
P4A_RC_SH=$P4A_ETC/par4all-rc.sh
P4A_RC_CSH=$P4A_ETC/par4all-rc.csh

echo
echo "### creating `basename $P4A_RC_SH` and `basename $P4A_RC_CSH`"
echo

mkdir -p  $P4A_ETC
cat <<EOF > $P4A_RC_SH
# Minimum Par4All rc file for sh-compatible shells

export P4A_ROOT=$P4A_ROOT

# default architecture
#export PIPS_ARCH=$PIPS_ARCH
# software roots
#export EXTERN_ROOT=$P4A_BUILD
#export NEWGEN_ROOT=$P4A_BUILD
#export NEWGEN_ROOT=$PIPS_DIR/newgen
unset NEWGEN_ROOT
#export LINEAR_ROOT=$P4A_BUILD
#export LINEAR_ROOT=$PIPS_DIR/linear
unset LINEAR_ROOT
#export PIPS_ROOT=$P4A_BUILD
#export PIPS_ROOT=$PIPS_DIR/pips
# Hack to have access to makefiles...
#export ROOT=$P4A_ROOT/packages/PIPS
# For pyps:
#export PIPS_NO_PYPS=1
#export PYTHONPATH=$P4A_BUILD/lib

#export INSTALL_DIR=$P4A_BUILD

# Mainly to avoid the non working libraries.make:
#unset WITH_DYNAMIC_LIBRARIES

# fix path
#PATH=$P4A_BUILD/bin:$P4A_BUILD/utils:\$PATH
PATH=\$PATH:\$P4A_ROOT/run/bin
export P4A_ETC=\$P4A_ROOT/run/etc

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:\$P4A_ROOT/run/lib
export PKG_CONFIG_PATH=\$P4A_ROOT/run/lib/pkgconfig
# To fix...
export PYTHONPATH=\$P4A_ROOT/run/lib/python2.5/site-packages/pips


# Temporary place for P4A_accel
export P4A_ACCEL_DIR=\$P4A_ROOT/src/p4a_accel

# Some hack to have p4a_recover_includes working. Directory to move
# somewhere else later...
#export PIPS_CPP_FLAGS=" -I$P4A_ROOT/src/postprocessor/include "
#export PYTHONPATH=/usr/share/pyshared
EOF

# Find the Fortran compiler:
type -t gfortran > /dev/null && export PIPS_F77=gfortran
type -t g77 > /dev/null && export PIPS_F77=g77
if [ -n "$PIPS_F77" ]; then
    echo >> $P4A_RC_SH
    echo "# The Fortran compiler to use:" >> $P4A_RC_SH
    echo "export PIPS_F77=$PIPS_F77" >> $P4A_RC_SH
fi

# Generate also a config file for csh users:
$P4A_PIPS_SRC/src/Scripts/env/sh2csh.pl < $P4A_RC_SH > $P4A_RC_CSH


echo Installing some lacking PIPS script...
# Stuff still lacking from PIPS install:
cp $P4A_PIPS_SRC/src/Scripts/validation/pips* $P4A_INSTALL_PREFIX/bin

# To have the validation running:
mkdir -p  $P4A_INSTALL_PREFIX/makes
cp $P4A_NLPMAKE_SRC/makes/{arch.sh,version.sh} $P4A_INSTALL_PREFIX/makes

PIPS_COMPONENTS="linear newgen pips"
#PIPS_DIR=$P4A_ROOT/packages/PIPS


# Build the package of name $1 that is to be found into directory $2,
# compilation targetw $4, with some $4 options to configure.

# If the P4A_<PACKAGE>_SRC environment variable is set, the its value
# represents the directory to be used to get the source package instead of
# $2.  Useful to compile PIPS components directly from the SVN for
# example.
function build_package() {
    local package=$1
    local dir=$2
    local compilation_targets=$3
    local options=$4
    (
	# Get the package name uppercased:
	local upper_package=${package^^}
	# If the P4A_SKIP_<PACKAGE> is defined, skip its installation:
	eval "local skip_package=\$P4A_SKIP_${upper_package}"
	if [[ -n $skip_package ]]; then
	    echo "Skipping the '$package' package..."
	    echo
	    return
	else
	    echo "Dealing with the '$package' package..."
	fi

	# Find the value of a P4A_<PACKAGE>_SRC variable:
	eval "local src_dir=\$P4A_${upper_package}_SRC"
	if [[ -n $src_dir ]]; then
	    # Overide the source origin from the given environment variable:
	    dir=$src_dir
	fi

	# Find if there are configuration options:
	eval "local config_options=\$P4A_${upper_package}_CONFIGURE_OPTIONS"
	if [[ -n $config_options ]]; then
	    # Overide the source origin from the given environment variable:
	    options=$config_options
	fi

        # For each asked target:
	for target in $compilation_targets; do

	    echo "Launching target '$target' on the '$package' package from '$dir' with configure options '$options':"
	    echo
	    cd $dir
	    dir=`pwd`

	    mkdir -p $P4A_BUILD/$package

	    if [[ $package == pips ]]; then
                # Special case for PIPS:
		(
		    local P4A_FORTRAN=$P4A_BUILD/pips/src/Passes/fortran95
		    mkdir -p $P4A_FORTRAN
		    # Copy with a rsync instead of simply symlinking the
   		    # source directory because the Fortran95 parser build
		    # patches the sources and that would mark the files as
		    # touched in the git repositiry (if any). Use --delete so
		    # that if this setup is run again, the .files are removed
		    # to relauch the patch:
		    rsync --archive --delete $P4A_ROOT/packages/pips-gfc/. $P4A_FORTRAN/gcc-4.4.3
		    # To cheat the Makefile process that would like to
		    # download the sources from the Internet:
		    touch $P4A_FORTRAN/{gcc-4.4.3.md5,gcc-core-4.4.3.tar.bz2,gcc-fortran-4.4.3.tar.bz2}
	            touch $P4A_FORTRAN/gcc-4.4.3/{.dir,.md5-check-core,.md5-check-fortran,.untar-core,.untar-fortran,.untar}
		)
	    fi

	    case $target in
		autoreconf)
		    autoreconf --install
		    ;;

		configure)
		    cd $P4A_BUILD/$package
		    $dir/configure ${PIPS_CONFIGURE_COMMON_FLAGS} $options
		    ;;

		*)
		    cd $P4A_BUILD/$package
		    make $P4A_MAKE_OPTS $target
		    ;;
	    esac
	done
    )
}


# Add a potentially missing link to the PIPS make infrastructure for a
# given component:
function add_link_to_make_infrastructure () {
    local package=$1
    ln -s -f ../nlpmake/makes $P4A_ROOT/packages/PIPS/$package/makes
}


# Make the targets on the PolyLib:
PIPS_CONFIGURE_COMMON_FLAGS="${PIPS_CONFIGURE_COMMON_FLAGS} --prefix=${INSTALL_PREFIX}"
build_package polylib packages/polylib "$compilation_targets"

# Make the targets on NewGen:
add_link_to_make_infrastructure newgen
build_package newgen packages/PIPS/newgen "$compilation_targets"

# Make the targets on Linear:
PIPS_CONFIGURE_COMMON_FLAGS="${PIPS_CONFIGURE_COMMON_FLAGS} PKG_CONFIG_PATH=${INSTALL_PREFIX}/lib/pkgconfig:$PKG_CONFIG_PATH"
add_link_to_make_infrastructure linear
build_package linear packages/PIPS/linear "$compilation_targets"

# Make the targets on PIPS:
PIPS_CONFIGURE_COMMON_FLAGS="${PIPS_CONFIGURE_COMMON_FLAGS} ${PIPS_CONFIG} PATH=${INSTALL_PREFIX}/bin:$PATH "
add_link_to_make_infrastructure pips
#build_package pips packages/PIPS/pips $compilation_targets "--enable-tpips --enable-pyps --enable-hpfc --enable-fortran95"
build_package pips packages/PIPS/pips "$compilation_targets" "--enable-tpips --enable-pyps --enable-hpfc"

cat << EOF
============================================
Par4All is ready
everything got installed in
$INSTALL_PREFIX

According to your shell religion, you should source
$P4A_RC_SH
(for bash, dash, sh...) or
$P4A_RC_CSH
(tcsh, csh...).
============================================
EOF

exit 0
