#! /bin/sh
#
# filters lines bitween header1 and header2
#

if [ $# != 1 ]
then
	echo Usage: $0 file
	exit 1
fi

header1="--- file $1"
header2="---"

sed -e "1,/^${header1}/d;/^${header2}/q" | sed "/^${header2}/d"
