#! /bin/sh
# Script to generate a file to submit to the Cray

USAGE="Usage: $0 pgm.f"

if [ $# != 1 ]
then
	echo $USAGE
	exit 1
fi

BASE=`basename $1 .f`
if [ "$BASE" = $1 ]
then
	echo $USAGE
	exit 1
fi
OUTPUT=$BASE.job

cat <<eob1 > $OUTPUT
# USER=pipscel PW=cri04emp
# QSUB -r mm
# -lM 2mw -lT 100
#
# Unicos script executed on the Cray follows:
# The standard out file is append to the log file.
# After each job all files are deleted.
#
cat <<'endofsource' > $BASE.f
eob1

cat $1 >> $OUTPUT

cat <<eob2 >> $OUTPUT
endofsource
set -x
echo --- compilation:
#cf77 -ZP -S -v $BASE.f
fpp -eib -l $BASE.fpplog $BASE.f > $BASE.fpp
fmp $BASE.fpp > $BASE.fmp
# cft77:
# l'option -ez n'aide pas a lire l'assembleur (+ de lignes) (pas de -g)
# l'option -es (qui remplace -s ?) genere un fichier d'extension .l ?
# on ne reutilise ni .fmp ni .fpp
# cft77 -s $BASE.cal $BASE.f (ne genere pas de fichier .o)
cft77 $BASE.f

# load cft77 version:
segldr $BASE.o

ls -l

echo --- file $BASE.fpp
cat $BASE.fpp
echo --- file $BASE.fpplog
cat $BASE.fpplog
#echo --- file $BASE.fmp
#cat $BASE.fmp
#echo --- file $BASE.cal
#cat $BASE.cal
echo --- output and execution time:
time a.out
eob2
