# $Id$
#
# Copyright 1989-2014 MINES ParisTech
#
# This file is part of PIPS.
#
# PIPS is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# PIPS is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.
#
# See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with PIPS.  If not, see <http://www.gnu.org/licenses/>.
#

INSTALL_UTL =	pips-deal-with-include \
		pips-process-module \
		subroutine_callgraph_level.pl \
		normalisation.pl \
		replace_file_name.pl \
		insert_alias_checks_in_source.pl \
		remove_useless_includes.pl \
		check_for_recursions.pl \
		logfile_to_tpips

# common stuff
ROOT    = ../../..
#PROJECT = pips
include $(ROOT)/makes/main.mk
