# $Id$

INSTALL_UTL =	pips-deal-with-include \
		pips-process-module \
		subroutine_callgraph_level.pl \
		normalisation.pl \
		replace_file_name.pl \
		insert_alias_checks_in_source.pl \
		remove_useless_includes.pl \
		check_for_recursions.pl

# common stuff
ifdef PIPS_ROOT
ROOT    = $(PIPS_ROOT)
else
ROOT    = ../../..
endif

#PROJECT = pips
include $(ROOT)/makes/main.mk
