#! /bin/sh
#
# $RCSfile: pips-process-module,v $ (version $Revision$)
# $Date: 1996/09/21 17:24:56 $, 
#

test "`type perl | grep 'not found'`" && {
    echo "perl not found -- skipping pre processing of file $1"
    exit 0
}

dir=`dirname $0`

perl $dir/pips-deal-with-include $1

# end of $RCSfile: pips-process-module,v $
#
