#! /bin/sh
#
# $Id$
#

test "`type perl | grep 'not found'`" && {
    echo "perl not found -- skipping pre processing of file $1"
    exit 0
}

dir=`dirname $0`

perl $dir/pips-deal-with-include $1

# end of $RCSfile: pips-process-module,v $
#
