#!/bin/sh -vx

#
# Guillaume Oget, Oct. 1995
#

# Modifcations:

USAGE="Usage: $0 workspace"

if [ $# -eq 0 ]
then
	exit 1
fi

wspace=${1}".database"

if [ ! -d ${wspace} ]
then
	exit 1
fi

UNSPLIT_FILE=${wspace}/"unsplited.file.f"
rm -f ${UNSPLIT_FILE}

for i in ${wspace}/*.f
do
	base=`basename $i .f`
	if [ ${UNSPLIT_FILE} != ${wspace}/${base}.f ]
	then
		#
		# Is there a .pref file (upcase prefix)
		#
		up_base=`echo $base |tr a-z A-Z`
		if [ -f ${wspace}/${up_base}".pref" ]
		then
			cat ${wspace}/${up_base}".pref" >> ${UNSPLIT_FILE}
		else
			cat ${wspace}/${base}".f" >> ${UNSPLIT_FILE}
		fi
	fi
done

#OK !
