//Generated by c2fsm -s 
model dummy6 {
var a,t;
//@parameters;
states stop,start,lbl_5;
transition t_17 :={
  from  := start;
  to    := lbl_5;
  guard := true;
  action:= a' = 2, t' = 0;
};
transition t_12 :={
  from  := lbl_5;
  to    := stop;
  guard := (5 <= t);
  action:=;
};
transition t_15 :={
  from  := lbl_5;
  to    := lbl_5;
  guard := (t <= 4);
  action:= a' = a+1, t' = a;
};
}
strategy dumb {
    Region init := { state = start && true };
}

