*DECK MTHLIB
C1MTHLIB
C
C      MTHLIB.FOR IS A COLLECTION OF ROUTINES WHICH GAUSSIAN-82
C      EMPLOYS TO ACCESS THE FLOATING-POINT FORTRAN LIBRARY 
C      FUNCTIONS.  ITS PURPOSE IS TO MAKE CHANGING THE PRECISION
C      OF THE PROGRAM SIMPLIER ON THOSE MACHINES WHERE IT MAKES
C      A DIFFERENCE WHETHER YOU SAY SQRT OR DSQRT, FOR EXAMPLE.
C
C
C     THE CURRENTLY AVAILABLE FUNCTIONS ARE:
C
C     GSQRT,  GLOG,   GLOG10, GEXP,   GSIN,  GCOS,   GTAN,
C     GATAN2, GASIN,  GACOS,  GATAN,  GABS,  GFLOAT, GMAX1,
C     GMIN1,  GMOD,   GSIGN,  IGFIX,  GREAL, GCONJG, GCABS,
C     GIMAG,  GINT,   GCMPLX, GCEXP,  GRAN
C
C     NOTE THAT GMIN1 AND GMAX1 ARE RESTRICTED TO 2 ARGUMENTS.
C     GRAN IS ASSUMED TO RETURN A RANDOM WORKING-PRECISION VALUE
C     0.0 .LE. GRAN .LT. 1.0
C?
      FUNCTION GSQRT (ARG)
C
C     SQUARE ROOT
C
      REAL*8 GSQRT,DSQRT,ARG
      GSQRT = DSQRT (ARG)
      RETURN
      END
