#!/bin/sh
#
# $Id$
#
# Derivation of builder_map.h (stdout) from pipsmake.rc (stdin)

functions=`grep '^[a-z]' | sed 's/ .*//' | sort -u`

# echo $functions >/dev/tty

for f in $functions
do
    echo "extern bool $f(char *);"
done

cat <<EOF

static struct builder_map {
    char *builder_name;
    bool (*builder_func)(char *);
} builder_maps[] = {

EOF

for f in $functions
do
  # echo $func
  F=`echo $f | tr '[a-z]' '[A-Z]'`
  echo "    { BUILDER_$F, $f },"
done

cat <<EOF

    { NULL, NULL }
};
EOF

# end of $RCSfile: make-builder-map,v $
#

